### ISSUE TITLE
#mv Won't Work Across Disks

### ISSUE THREAD

**Issue by tbeseda** [shelljs/shelljs#1]
[`fs#renameSync`](https://github.com/arturadib/shelljs/blob/master/shell.js#L388) won't work across partitions or attached storage. This is by design, as `rename` is paired to the C version of the same method, which isn't able to cross disks either. (See [this closed issue](https://github.com/joyent/node/issues/2703) for more discussion about `rename`.)

A solution could be piping a `readStream` to a `writeStream`, and then cleaning up the source file.  
I'd attach a fix but the trouble is that listening for the `end` event on the pipe and firing a callback would break the synchronous nature of shelljs.

Ideas?

*Great module, by the way. Very helpful!*

**Comment by JoshGalvin** [comment]
Still broken.

**Comment by ariporad** [comment]
@nfischer: Are you working on this?

**Comment by nfischer** [comment]
@ariporad I tried a simple solution with `cp()` and `rm()`, but I was dissatisfied because error messages with either of those steps show `cp: ` or `rm: ` at the start, which isn't very preferable. Feel free to write up a PR though!
