### ISSUE TITLE
Symbolic links are broken!

### ISSUE THREAD

**Issue by nylen** [shelljs/shelljs#100]
The new `ln` function does not work correctly in some cases:

```sh
# Setup
mkdir test-shelljs-ln
cd test-shelljs-ln
mkdir -p dir1/dir2/
echo file1_contents > dir1/file1.txt

# Create a link the old-fashioned way
ln -s ../file1.txt dir1/dir2/link1

# Create a link the new way
npm install 'shelljs@git://github.com/arturadib/shelljs.git#284fc1cc34'
node -e "require('shelljs').ln('-s', '../file1.txt', 'dir1/dir2/link2');"
# shelljs prints this error message:
#ln: Source file does not exist

# Inspect the results
ls -la dir1/dir2/
# output contains the following:
#lrwxrwxrwx 1 me me   12 Dec 27 22:47 link1 -> ../file1.txt
#lrwxrwxrwx 1 me me   32 Dec 27 22:49 link2 -> /home/me/file1.txt

# Clean up
cd ..
rm -r test-shelljs-ln
```

So, there are a couple of problems here:

 * The source of a symbolic link doesn't have to exist relative to the current directory.
 * The source of a symbolic link shouldn't be resolved relative to the current directory.  If you really want to check for the existence of the source file, resolve the  source path relative to the **destination** directory, but POSIX `ln` doesn't do this.

The second issue prevents relative links from being created.  The `link2` created by shelljs above points to a file that does not exist.

**Comment by charlierudolph** [comment]
Bump on this.

I wanted to have the source be relative.

Another error is that when checking whether or not dest exists. 
If the dest is already a symbolic link, it follows it.
Thus is dest is a symbolic link pointing to a path that doesn't exist, it attempts to link and fails.
```
~/test> ln -s invalid a
~/test> touch valid
~/test> node
> shelljs = require('shelljs')
> shelljs.ln('-sf', 'valid', 'a') 
shell.js: internal error
Error: EEXIST, file already exists '/Users/charlesrudolph/projects/a'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:848:18)
    at Object._ln (/Users/charlesrudolph/node_modules/shelljs/src/ln.js:48:8)
    at Object.ln (/Users/charlesrudolph/node_modules/shelljs/src/common.js:186:23)
    at repl:1:9
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
```

**Comment by Schoonology** [comment]
@arturadib - How likely do you think it is that someone is relying on this incorrect behaviour?

Currently, we're resolving both paths and creating a symbolic link to the former by absolute path. The way native `ln` works is to leave the former alone, creating a symbolic link at that path _relative to the symbolic link_. Fixing this bug would result in matching native `ln`.

**Comment by arturadib** [comment]
@Schoonology I think we should stick to the mission of mocking *nix behavior as much as possible. We can make a breaking change by bumping the minor - hopefully npm customers are using `^` :)
