### ISSUE TITLE
Shelljs.cd can't navigate to folders containing folders or files owned by root

### ISSUE THREAD

**Issue by FrancoCorleone** [shelljs/shelljs#1007]
### Node version (or tell us if you're using electron or some other framework):
v12.16.0
### ShellJS version (the most recent version/Github branch you see the bug on):
^0.8.4
### Operating system:
Ubuntu 18.04
### Description of the bug:
shelljs.cd can't navigate to any folder that contains any other folder containing files owned by root. 
This is extremely painful when you use CLI to operate on your project which mounts volumes with root owned files.
### Expected behaviour:
shelljs.cd can navigate to any folder normal user can

**Comment by nfischer** [comment]
Why was this closed? Is this still an issue?

I'm not aware of any reason this problem should be happening. As far as I'm aware, `shell.cd()` should be able to change into any folder where that user has "x" permission. If you can still repro this, please include `ls -l` output (using bash `ls` in your terminal, not `shell.ls()`) for that folder so I can review the permissions.
