### ISSUE TITLE
🐜 Logs not showing on Linux service

### ISSUE THREAD

**Issue by nicolascalev** [shelljs/shelljs#1009]
### Node version (or tell us if you're using electron or some other framework):
v14.5.0

### ShellJS version (the most recent version/Github branch you see the bug on):
v0.8.4

### Operating system:
CentOS 7

### Description of the bug:
I have a node app with cron running with a Linux service, it's querying a database and showing the results with logs.
When I execute the program normally it catches the output and saves it to a log file which is the desired behavior, but when I write a Linux service, the logs are shown with **systemctl status -l** but they are not saved to the log file I created originally with shelljs when I execute **shell.sed()**

### Example ShellJS command to reproduce the error:

```javascript
function asyncExec(cmd) {
    return new Promise((resolve, reject) => {
        shell.exec(cmd, (code, stdout, stderr) => {
            if (stderr) {
                reject(stderr)
            } else {
                resolve(stdout)
            }
        })
    })
}

function generateLogName() {
    return `${moment(Date.now()).format('DD-MM-YYYY_hh-mm-ss')}.log`;
}

var prueba = new CronJob('* * * * * *', async () => {
    var fileName = generateLogName();
    var logDirName = `${__dirname}/prueba/logs/${fileName}`
    shell.touch(logDirName)
    try {
        var res = await asyncExec(`sudo /usr/bin/env node ${__dirname}/prueba/prueba.js`)
        shell.sed('-i', '', res, logDirName)
    } catch (err) {
        shell.sed('-i', '', 'Error de ejecución: \n' + err, logDirName)
    }
})

prueba.start()
```

**Comment by nfischer** [comment]
I think this is WAI intended from ShellJS's perspective. `shell.touch()` creates a file with no contents (no lines). `shell.sed()` operates line-by-line, so I think it's WAI for it to do nothing. I believe `sed` on unix behaves similarly.

**Comment by nfischer** [comment]
If you just want to write to a file, you could try:

```js
(new ShellString('something to log')).to('name_of_file.txt');
```
