### ISSUE TITLE
cp -r doesn't match linux when destination doesn't exist

### ISSUE THREAD

**Issue by gdw2** [shelljs/shelljs#101]
In linux, `new_dir` and `existing_dir` are now copies (`new_dir` didn't exist before):
```
$ mkdir existing_dir
$ touch existing_dir/foo
$ cp -rf existing_dir new_dir
```
With shelljs, `new_dir/existing_dir` and `existing_dir` are copies.  I would expect the linux behavior.  
```
cp('-rf', 'existing_dir', 'new_dir')
```

**Comment by nfischer** [comment]
This should be fixed by #271. Would anyone here be able to confirm that this PR fixes it? As far as I can tell, it seems to be good.
