### ISSUE TITLE
Circular dependency warnings

### ISSUE THREAD

**Issue by hjllary** [shelljs/shelljs#1012]
### Description of the bug:
Getting a huge list of warnings when I try to run a program that uses shelljs. Didn't get these warnings before I upgraded to BigSur on my mac

### Example ShellJS command to reproduce the error:
node main.js
(let me know if it'd help to see the script for main.js)

Warnings:
(node:66043) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:66043) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:66043) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

**Comment by nfischer** [comment]
This was fixed in v0.8.4. Can you double-check (with `npm ls`) you've got the right shelljs version?

**Comment by eyeojeff** [comment]
I dont think this is fixed..

```
root@224ce8a4b7fa:/# npm -g ls
/usr/local/lib
+-- npm@7.3.0
+-- shelljs@0.8.4
`-- violations-command-line@1.13.0

root@224ce8a4b7fa:/# violations-command-line --help > /dev/null
(node:86) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:86) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:86) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
```

**Comment by nfischer** [comment]
@eyeojeff please file a bug against violations-command-line. They're using an old version of shelljs (v0.7.8).

```
$ npm -g install violations-command-line
$ npm -g ls
...
└─┬ violations-command-line@1.13.0
  └─┬ shelljs@0.7.8               <--- here's your problem
...
```
