### ISSUE TITLE
exec not returning exit code properly

### ISSUE THREAD

**Issue by sethen** [shelljs/shelljs#1013]
### Node version (or tell us if you're using electron or some other framework):
v12.20.1
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.4
### Operating system:
Ubuntu 20.04 LTS
### Description of the bug:
`shell.exec` doesn't raise exit code if it is not zero.  
### Example ShellJS command to reproduce the error:

Here is the code I have:

```javascript
#! /usr/bin/env node

const shell = require("shelljs");

shell.exec("jest --config jest.config.json --coverage");
```

Here is what I had to do to make this work properly:

```javascript
#! /usr/bin/env node

const shell = require("shelljs");

shell.exec("jest --config jest.config.json --coverage", function (code) {
	if (code !== 0) {
		shell.exit(1);
	}
});
```

Shouldn't this be the default behavior?

**Comment by nfischer** [comment]
If I understand correctly, you're trying to implement bash's behavior by exiting the script with the error code of the last shelljs command.

> Shouldn't this be the default behavior?

While I see some potential use cases for this, I think most use cases would prefer the way things are (no automatic manipulation of exit status). I think this could be a cool off-by-default feature, so this might be a good candidate for a [shelljs plugin](https://github.com/shelljs/shelljs/wiki/Using-ShellJS-Plugins).

We don't currently expose the error code of the last command, but you could get close to implementing this with something like:

```js
var shell = require('shelljs');

process.on('exit', code => {
  // Note: there's no shell.errorCode() API, so we just return 1 if
  // there's an error.
  var exitCode = shell.error() ? 1 : 0;
  shell.exit(exitCode);
});

// Your script here...
shell.echo('hello world');
```

If you were inclined, we would accept a PR to implement `shell.errorCode()`. This wouldn't be very difficult, and you could follow `shell.error()` as an example.

**Comment by addlistener** [comment]
My use case here. I write bash as default, but later I need everything to work on Windows. So I tried to replace my bash lines with shelljs lines. That's why I need the exit feature.

**Comment by nfischer** [comment]
Closing this one out. This was solved by https://github.com/shelljs/shelljs/pull/1036.

**Comment by nfischer** [comment]
Suggested code (once shelljs v0.9.0 comes out) would look like:

```js
var shell = require('shelljs');

process.on('exit', code => {
  shell.exit(shell.errorCode());
});

// Your script here...
shell.echo('hello world');
```

If you just want the script to die as soon as any command returns non-zero, then do this:

```js
var shell = require('shelljs');

shell.set('-e');

// Your script here...
shell.echo('hello world');
```
