### ISSUE TITLE
cp-Error: dest is not a directory (too many sources)

### ISSUE THREAD

**Issue by markus-hsk** [shelljs/shelljs#1014]
### Node version (or tell us if you're using electron or some other framework):
node -v
v12.16.1

### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.4

### Operating system:
Windows & Linux (Docker Node:10.21.0-buster)

### Description of the bug:
We try to use the cp command for a bigger amount of files in a deep Folder structure (~8900 files). It returns with exit code 1 and error message `cp: dest is not a directory (too many sources)`. It only crashes, if the whole tree has to be copied. If most of the files are already there and it has to move only a few missing ones, it still works on that source-directory. 

At the moment it's not possible to use shelljs for our folder tree.  This result is also equal on both OS - windows and unix. If we do not use shelljs, but the bash command cp for the same directory, that works without any problem. I guess it might be some memory or javascript problem, but could not figure out.

**Comment by nfischer** [comment]
Please share the exact shelljs command you're invoking.

As far as I'm aware, `shell.cp()` should be able to handle just about anything. The `cp: dest is not a directory (too many sources)` error message means you specified a bunch of "source" args for the command but no "destination" arg (which is always required). In practice, this usually means your last arg is a file rather than a directory, which forces `shell.cp()` to interpret this as a "source" rather than a "destination."

**Comment by markus-hsk** [comment]
```javascript
import * as shell from "shelljs";
shell.cp("-R", "src/public/*", "dist/public");
```

I do added a destination argument and as i mentioned, the code works, but only if the destination folder already has many of the source files in it. If the command has to copy a big amount of files it exits with code 1 and the given error message.

**Comment by nfischer** [comment]
Is there a reason you're using `src/public/*` instead of `src/public/`? Does the error go away if you translate it to something like:

```js
shell.cp('-r', 'src/public/', 'dist/'); // this will create "dist/public"
```

**Comment by markus-hsk** [comment]
Tbh my coworker did the coding a few weeks ago. Reason for the * was, that deeper folder structures weren't copied, only the top directories.

But i checked your suggestion and no, it does not create the public directory as you said, look:

![Zwischenablage04](https://user-images.githubusercontent.com/13730463/105143206-ce568580-5afb-11eb-87c6-6aa8fd9bf7c5.jpg)

After that i made a second try with:
```javascript
shell.cp("-r", "src/public/", "dist/public");
```
That resulted in an error response: `cp: cannot create directory 'dist/public': No such file or directory`

**Comment by nfischer** [comment]
That error message suggests the `dist/` folder doesn't already exist. `cp` doesn't know to create that for you, so you need to create that first yourself:

```js
shell.mkdir('dist/'); // this will create "dist/"
shell.cp('-r', 'src/public/', 'dist/'); // this will create "dist/public/"
```

Alternatively, this works too:

```js
shell.mkdir('dist/');
// this also creates "dist/public/", although you could optionally name it "dist/<whatever you want>/"
shell.cp('-r', 'src/public/', 'dist/public/');
```

**Comment by markus-hsk** [comment]
Seems to work as suggested! Thank you

**Comment by nfischer** [comment]
It seems like `shell.cp()` is working as expected, so I'm going to close this. Let me know if you have any suggestions for whether this needs to be clarified in documentation.
