### ISSUE TITLE
Command with caret doesn't work as supposed to with exec()

### ISSUE THREAD

**Issue by Friksel** [shelljs/shelljs#1015]
### Node version (or tell us if you're using electron or some other framework):
14.15.3

### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.4

### Operating system:
Windows 10

### Description of the bug:
Executing a command with a caret, like `pnpm install three@^0.124.0`, isn't working; instead of running that command it seems to run the command without the caret under the hood, which has a different outcome as it's not installing v0.124.0 **or higher**, but installes **exactly** v0.124.0. So the caret in this case is important and may never be stripped.

I tried escaping the caret with `\`, but that didn't help.

Looking in the shellJS module I can't find code where it strips the `^` and I see the command passing through just fine. So not shure what's going on exactly, but when running the command directly in a command line tool, like powershell, it just works as expected.

### Example ShellJS command to reproduce the error:

```javascript
const result = shell.exec('pnpm install three@^0.124.0'); // seems to execute command without caret
```

**Comment by nfischer** [comment]
Works as expected on mac/linux:

```js
> shell.exec('echo this has caret three@^0.124.0'
this has caret three@^0.124.0
```

If this is a special character on Windows, then it's up to your application to properly sanitize the input. `shell.exec()` just executes in the default shell.

I'm not planning to do any more improvement to the `exec()` method. This should already be handled by exec's successor, `shell.cmd()` (you can follow issue #495). If you would like to verify this, we would accept a PR to add a test case for this specific character, following https://github.com/shelljs/shelljs/blob/355bc754d289b5b6be4ee8b5259dfe893c5a740e/test/cmd.js#L123-L133 as a template.

**Comment by Friksel** [comment]
> Works as expected on mac/linux:
> 
> ```js
> > shell.exec('echo this has caret three@^0.124.0'
> this has caret three@^0.124.0
> ```
> 
> If this is a special character on Windows, then it's up to your application to properly sanitize the input. `shell.exec()` just executes in the default shell.
> 
> I'm not planning to do any more improvement to the `exec()` method. This should already be handled by exec's successor, `shell.cmd()` (you can follow issue #495). If you would like to verify this, we would accept a PR to add a test case for this specific character, following
> 
> https://github.com/shelljs/shelljs/blob/355bc754d289b5b6be4ee8b5259dfe893c5a740e/test/cmd.js#L123-L133
> 
> as a template.

@nfischer Hi Nate,

Thanks for responding and sorry for my late response. I wanted to check this first before responding, but it took me longer to come to this than expected.

I'm working on the code right now to try to make the caret work with shellJs.

Great to read from you that exec() works on Linux and Mac. Unfortunately this isn't working on Windows.
AFAIK the caret is no special character on Windows that could cause this to fail. Also, when using a command like `pnpm install three@^0.123.0` there's no issue and pnpm just installs the latest 0.123.x version of three and puts "^0.123.0" in package.json.

So I'm surprised you immediately closed this thread while there's obviously something off somewhere as the caret isn't working. 

This has nothing to do with me sanitizing input or whatever, I try shell.exec(cmd) directly in code, so nothing to sanitize here. Eventhough I still tried to escape the caret with `\` as I wrote above, but also that didn't help. And when I followed the path of the exec() command in the shellJs module I cannot see something changing this either ; everything seems to pass the `^` caret which makes it so strange to me as Windows itself shouldn't have any issue with the caret as no command prompt I'm using here (and I use several) ever had a problem with carets.

Maybe you closed this issue because you wrote you are working on a successor? That's fair and understandable. I'm going to test that one now to see if it works there.

Thanks again for your response. If I find out more I let you know.

**Comment by Friksel** [comment]
To my surprise and pleasure I see that even this works:

``` text
shell.exec('pnpm install three@"^"0.123.0');
```

So to wrap only the caret in double quotes does its job also! Which makes it way easier to replace carets in unknown commands!

I'm going to use this in my code now, but this could also be a great way to make it work in shellJs by default; just replace carets with a caret surrounded by double quotes! Use it to your advantage, or not ;)
