### ISSUE TITLE
How to execute a command under another User than Root ?

### ISSUE THREAD

**Issue by rejebsab** [shelljs/shelljs#1016]
### Description of the bug:
I'd like to execute a command under another user than root, as this later is the default user of shelljs. Example
1) Switch to another user: 
su tester1
2) Display message using tester1
echo "Hello shelljs"

How to do that with shelljs?

Thank you for your help!

**Comment by nfischer** [comment]
We don't have any explicit support for the `su` command. You can try `shell.exec('su')`, but we don't support interactive user input so this may break if password is required. I hope this helps!
