### ISSUE TITLE
`mkdirSyncRecursive()` shouldn't fail when directory exists unexpectedly

### ISSUE THREAD

**Issue by rivy** [shelljs/shelljs#1018]
When using `shx mkdir -p ...`, occasional, unnecessarily terminal, errors can occur if the target directory is created by another process during the execution of `mkdirSyncRecursive()`.

It's an obvious race condition that I've run into occasionally when using `shx` for builds with multiple parallel steps (eg, <https://github.com/rivy/js.xdg-portable/runs/1896221924?check_suite_focus=true>)

Ignoring 'EEXIST' errors in `mkdirSyncRecursive()` can mitigate this problem.

**Comment by nfischer** [comment]
What happens if you use the standard unix `mkdir`? Is it robust against these errors?

Can you provide repro commands (with either shelljs or shx) to repro this bug semi-reliably?

**Comment by rivy** [comment]
I have never seen a problem in the past using a POSIX `mkdir`. That doesn't mean it couldn't happen since Linux seems to avoid such race condition collisions for the most part. A google search reveals conversations from a few years ago saying that `mkdir` is atomic, although `mkdir -p` is not. So, it's possible that it could occur on POSIX systems.

But, regardless, since `-p` says "no error if directory exists", if, at the end, we have the directory we want, even if someone else created it, I don't think it should be an error. And, looking at the [code of one implementation](https://github.com/coreutils/coreutils/blob/b8cedd257ad21e739caaaf77cb5d26514686d942/lib/mkdir-p.c#L263-L304), it does this same thing on such races.

Reproducing such a race collision is obviously not simple. I've got lots of examples where it happens (every few dozen builds when building 4 or 5 things in parallel), as the example noted above. But, I don't have a reliable test. You could `rm -rf TARGET_DIR` and then set off multiple `shx mkdir -p TARGET_DIR`, where TARGET_DIR is deep; it should collide for a sufficient level of "deep" and size of "multiple". Either an `npm` package or a `node` script should do it.

**Comment by nfischer** [comment]
Fair enough. If GNU coreutils works around this in a similar way, I think it's reasonable for shelljs to attempt the same.
