### ISSUE TITLE
question: using exec with async in container

### ISSUE THREAD

**Issue by eric-hc** [shelljs/shelljs#1021]
### Node version (or tell us if you're using electron or some other framework):
`12.16.1`

### ShellJS version (the most recent version/Github branch you see the bug on):
`0.8.4`

### Operating system:
`node:12.16.1-alpine3.11`

### Description of the bug:
I am running a container with some tools like `git`, `mkdocs`, `yarn` installed and use `exec` to run some processes. In the past, I was running them successfully synchronously, but now want to run them `async` and out of the box, `mkdocs` and `yarn` commands are not working. 

### Example ShellJS command to reproduce the error:

```javascript
await shell.exec(`cd temp/somedir; mkdocs gh-deploy`, { async: true });
```
This outputs the following error which makes me think `mkdocs` is not available from the shelljs executor:

```sh
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/mkdocs/__main__.py", line 178, in gh_deploy_command
    cfg = config.load_config(
  File "/usr/lib/python3.8/site-packages/mkdocs/config/base.py", line 186, in load_config
    config_file = _open_config_file(config_file)
  File "/usr/lib/python3.8/site-packages/mkdocs/config/base.py", line 146, in _open_config_file
    config_file = os.path.abspath('mkdocs.yml')
  File "/usr/lib/python3.8/posixpath.py", line 379, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

This was previously working as expected using 

```javascript
await shell.exec(`cd temp/somedir; mkdocs gh-deploy`);
```

Does anybody know why I might be having an issue using `async` with `exec` with some tools within my container?

I ran `shell.which('mkdocs')` and it is showing this

```sh
[String: '/usr/bin/mkdocs'] {
  stdout: '/usr/bin/mkdocs',
  stderr: null,
  code: 0,
  cat: [Function: bound ],
  exec: [Function: bound ],
  grep: [Function: bound ],
  head: [Function: bound ],
  sed: [Function: bound ],
  sort: [Function: bound ],
  tail: [Function: bound ],
  to: [Function: bound ],
  toEnd: [Function: bound ],
  uniq: [Function: bound ]
}
```

and `yarn` is in `/usr/local/bin/yarn`

**Comment by eric-hc** [comment]
Likely my issue is be that running multiple commands is the problem. 

Running unique commands works 😁 

```javascript
await shell.cd(`temp/somedir`);
await shell.exec(`mkdocs gh-deploy`, { async: true });
```

**Comment by nfischer** [comment]
I would've expected this to work out-of-the-box, but separate shelljs commands are definitely preferred. I'm glad you found the solution!

Btw you don't need to `await shell.cd` (it's synchronous) and `await shell.exec` probably doesn't do what you want (exec doesn't return a Promise; you'll need to [wrap it yourself](https://github.com/shelljs/shelljs/issues/2#issuecomment-355507471) to use its callback to resolve a Promise)

**Comment by eric-hc** [comment]
Ahh thanks so much! That actually is a huge help, I was wondering why it wasn't doing what I wanted!

```javascript
shell.exec(`mkdocs gh-deploy`, (code, stdout, stderr) => {
  logger.debug('Exit code:', code);
  logger.debug('Program output:', stdout);
  logger.debug('Program stderr:', stderr);
});
```
This is logging an empty `code`, `stdout`, and `stderr`. Would I need to still wrap it to resolve the `async` promise?
