### ISSUE TITLE
exec command Error: unknown option max-count=1

### ISSUE THREAD

**Issue by dbwcooper** [shelljs/shelljs#1025]
### Node version (or tell us if you're using electron or some other framework):
12.13.1
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.4
### Operating system:
Windows 10
### Description of the bug:
git code
```
 git describe --tags $(git rev-list --tags --max-count=1) 
```
An error was reported using Shelljs.exec, but it was successfully run on Windows Terminal.

### Example ShellJS command to reproduce the error:

```javascript
shell.exec("git describe --tags $(git rev-list --tags --max-count=1)", (code, stdout, stderr) => {
     
});
```
Failed 
![image](https://user-images.githubusercontent.com/22339946/111975372-7eb42a80-8b3b-11eb-8bc5-156242b319f5.png)

Successful on Windows Terminal
![image](https://user-images.githubusercontent.com/22339946/111976160-4e20c080-8b3c-11eb-9b83-c46239c638f5.png)

**Comment by nfischer** [comment]
I'm not sure subshells work in exec. I would advise you to split this into two commands:

```js
var revListOutput = shell.exec('git rev-list --tags --max-count=1');
shell.exec(`git describe --tags ${revListOutput}`, (code, stdout, stderr) => {
});
```

**Comment by dbwcooper** [comment]
> I'm not sure subshells work in exec. I would advise you to split this into two commands:
> 
> ```js
> var revListOutput = shell.exec('git rev-list --tags --max-count=1');
> shell.exec(`git describe --tags ${revListOutput}`, (code, stdout, stderr) => {
> });
> ```

it works, thank you so much, this problem has bothered me for several days.
