### ISSUE TITLE
shelljs does not terminate parent process by exec sudo pkill -P 

### ISSUE THREAD

**Issue by rez1shehni** [shelljs/shelljs#1029]
### Example ShellJS command to reproduce the error: shell.exec(`sudo pkill -P ${pythonProcess.pid}`)

```javascript

```

**Comment by nfischer** [comment]
`exec()` spawns a subprocess to execute the shell command. Your shell command probably is killing its parent process, but the parent process is internal to shelljs and is not the main node process. You'll need to find a different way to kill your specified process, such as finding the right PID and passing that to a `kill` command.
