### ISSUE TITLE
Linting file import extension error

### ISSUE THREAD

**Issue by JessieFrance** [shelljs/shelljs#1032]
### Node version (or tell us if you're using electron or some other framework):
v16.1.0 and v14.17.0 (I tested both).

### ShellJS version (the most recent version/Github branch you see the bug on):
I observed this while cloning both from my own fork and also cloning directly from the ShellJS master branch.

### Operating system:
Ubuntu 16.04

### Description of the bug:

Without making any code changes, I am getting an "import/extensions" linting error on ```npm run lint```. The error says '_Unexpected use of file extension "js" for "../src/exec-child.js"_', and references this test file/code line:
https://github.com/shelljs/shelljs/blob/124d3349af42cb794ae8f78fc9b0b538109f7ca7/test/exec.js#L68

I see that the linting Travis CI tests passed recently (April 15), so I'm guessing there must have been some recent changes within a linting dependency (maybe eslint-plugin-import). Regardless, this looks like a simple fix, and I would be happy to file a PR.

**Comment by nfischer** [comment]
Huh, interesting find. Yeah, it looks like this was some dependency that broke us.

**Comment by nfischer** [comment]
Fixed by #1033.
