### ISSUE TITLE
shelljs incompatible with esbuild

### ISSUE THREAD

**Issue by cgranade** [shelljs/shelljs#1035]
### Node version (or tell us if you're using electron or some other framework):

```
$ node --version
14.3.0
$ npm --version
7.18.1
$ npx vsce --version
1.94.0
$ npx esbuild --version
0.12.9
$ npm ls shelljs
[redacted]
└─┬ yeoman-generator@5.3.0
  └── shelljs@0.8.4
```

### Operating system:

Windows 10

### Description of the bug:

When using esbuild to compile a VS Code extension, the result JavaScript file raises an error when `shelljs` is loaded:

![image](https://user-images.githubusercontent.com/31516/123311878-7e318400-d4dc-11eb-9064-35464319fbeb.png)

Running `esbuild` without `--minify` shows that the cause of the error is the following code emitted into `main.js` by `esbuild`:

```javascript
// node_modules/shelljs/shell.js
var require_shell = __commonJS({
  "node_modules/shelljs/shell.js"(exports2) {
    var common = require_common3();
    require_commands().forEach(function(command) {
      require("./src/" + command);
    });
    exports2.exit = process.exit;
    exports2.error = require_error2();
    exports2.ShellString = common.ShellString;
    exports2.env = process.env;
    exports2.config = common.config;
  }
});
```

In particular, the above fails as `./src/` does not exist in the resulting `main.js`, such that the call to `require` fails.

The above code in turn is generated by `esbuild` from the original source at https://github.com/shelljs/shelljs/blob/master/shell.js#L23.

**Comment by nfischer** [comment]
It sounds like this is a bug with esbuild. We do not support JavaScript bundler tools because they make incorrect assumptions about our project structure and fail to include modules we require.
