### ISSUE TITLE
ShellJS documentation website is currently not working 

### ISSUE THREAD

**Issue by fineon** [shelljs/shelljs#1049]
### Node version (or tell us if you're using electron or some other framework):
Nodejs LTS 14.7.6
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.4
### Operating system:
Windows 10
### Description of the bug:
Currently the Documentup website is not displaying ShellJS documentation. If this is not working, where else can I read the documentation? Thank you.
[https://documentup.com/shelljs/shelljs](https://documentup.com/shelljs/shelljs)
![image](https://user-images.githubusercontent.com/38566281/137568863-b93aa1e3-33cf-4685-b1d8-5f2c790339af.png)
### Example ShellJS command to reproduce the error:

```javascript

```

**Comment by nfischer** [comment]
You can read the documentation right here on the GitHub repo: https://github.com/shelljs/shelljs. Documentup was just hosting a copy of the README.md markdown.

Looks like all of https://documentup.com/ is down. Maybe the service is no longer maintained? I think this was set up before I started maintaining this project, so maybe we can just link to the README instead.

**Comment by fineon** [comment]
I see. Hope you don't mind if I create a few pull requests to update the documentation with the correct links and references? If documentup.com is down then I think all references to it should be removed.

**Comment by nfischer** [comment]
Pull requests would be much appreciated! Thanks!
