### ISSUE TITLE
Using a custom echo function with exec

### ISSUE THREAD

**Issue by nodesocket** [shelljs/shelljs#1051]
### Node version (or tell us if you're using electron or some other framework):

v14.17.6

### ShellJS version (the most recent version/Github branch you see the bug on):

0.8.4

### Operating system:

Linux (Ubuntu)

### Description of the bug:

Is it possible to feed the output from `exec()` into a custom function? I want to keep the behavior of `silent: false` but instead of `console.log()` I'd like to pass the output string into my own logging function `Log.info(<exec-output-here>)`.

**Comment by nfischer** [comment]
You could use the async version of `exec()`, which will give you the ability to register event handlers for output. Then you could just write the output to the file yourself, or whatever you need to do with it.

I don't think we're going to provide generalized support for this, but let me know if you have trouble getting this working and I can try my hand at some sample code.

**Comment by nodesocket** [comment]
@nfischer thanks so much for the reply.

> You could use the async version of exec(), which will give you the ability to register event handlers for output. Then you could just write the output to the file yourself, or whatever you need to do with it.

Yah, I am not quite following this. If I am using something like:

```
const deploy = shell.exec(`./deploy.sh`);
```

I'd like to use a custom logger function `Log.info(<stdout>)` and `Log.error(<stderr>)`.

**Comment by nfischer** [comment]
We do not support this for the sync version of `exec()`. You need to use `{ async: true }`. This code example from [the docs](https://github.com/shelljs/shelljs#execcommand--options--callback) should get you most of the way there:

> ```js
> var child = exec('some_long_running_process', {async:true});
> child.stdout.on('data', function(data) {
>   /* ... do something with data ... */
> });
> ```

Replace "do something with data" with the call to your custom logger function to handle stdout. You can handle stderr as well in a similar fashion (add `child.stderr.on('data', ...` after this).
