### ISSUE TITLE
[BUG] not compatible with pnpm on windows

### ISSUE THREAD

**Issue by xialvjun** [shelljs/shelljs#1062]
```
PS C:\Users\01418019\code\learning> mkdir xxx


    Directory: C:\Users\01418019\code\learning

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           2022/1/10    19:53                xxx

PS C:\Users\01418019\code\learning> cd xxx
PS C:\Users\01418019\code\learning\xxx> pnpm init -y
Wrote to C:\Users\01418019\code\learning\xxx\package.json:

{
  "name": "xxx",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


PS C:\Users\01418019\code\learning\xxx> pnpm add shelljs
Packages: +20
++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\01418019\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm

dependencies:
+ shelljs 0.8.5

Progress: resolved 20, reused 20, downloaded 0, added 20, done
PS C:\Users\01418019\code\learning\xxx> mkdir dist


    Directory: C:\Users\01418019\code\learning\xxx

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           2022/1/10    19:54                dist

PS C:\Users\01418019\code\learning\xxx> pnpx shjs rm -rf dist
ShellJS: script not found (rm)

PS C:\Users\01418019\code\learning\xxx> node -v
v14.18.1
```

### Node version (or tell us if you're using electron or some other framework):
v14.18.1

### ShellJS version (the most recent version/Github branch you see the bug on):
v0.8.5

### Operating system:
Windows 10

### Description of the bug:

Shows `ShellJS: script not found (rm)`.

### Example ShellJS command to reproduce the error:

Above

**Comment by nfischer** [comment]
`shjs` is a tool to execute a JavaScript file, ex. `shjs path/to/my/script.js`. This expects its first argument to be a path to a JavaScript file so this error message is telling you it can't find a file named `rm`.

I think you're actually intending to run a single command though (i.e., delete that folder). You probably want to use https://github.com/shelljs/shx instead, which is designed to run one-off commands like this, ex. `shx rm -rf dist`.

Let me know if I've misunderstood, in which case I'm happy to reopen and take another look.
