### ISSUE TITLE
how to remove or supress theese warnings?

### ISSUE THREAD

**Issue by minicloudsky** [shelljs/shelljs#1064]
> node build/dev-server.js

> Starting dev server...
(node:57216) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:57216) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:57216) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

 DONE  Compiled successfully in 29158ms

**Comment by nfischer** [comment]
@minicloudsky it looks like you might have pasted over the issue template. Can you review the template and include that information here? Like @Etheryte pointed out, this should have been fixed by v0.8.4 (and the fix is included in v0.8.5). Let me know what ShellJS version you're using and I can take a closer look.
