### ISSUE TITLE
updating to 0.8.5 is causing an error where we are "unable to write hash to file"

### ISSUE THREAD

**Issue by Mister-CK** [shelljs/shelljs#1084]
### The following 'then' fails, making it impossible to sign and causing the pipline to fail
    
```
.then(function (hashOutput) {
      const hash = label + ' ' + env + ' ' + version + ' ' + platform + ':\n' + hashOutput + '\n';
      hash.toEnd('_distributions/'+label+'-'+env+'-'+version+'-'+platform+'-hash.txt');
      gutil.log(gutil.colors.green('Package succesfully signed'));
      done();
    })
    .catch(function () {
      errorHandler('Error: unable to write hash to file');
    });
```

### Example ShellJS command to reproduce the error:
The following line fails, I am not sure how to simply reproduce this, without running our whole pipeline
`      hash.toEnd('_distributions/'+label+'-'+env+'-'+version+'-'+platform+'-hash.txt');
`

This is not an urgent issue for us, since we just downgraded to 0.8.4, which works fine. But I think it's important you are aware of this issue.

**Comment by Mister-CK** [comment]
nevermind, different issue

**Comment by nfischer** [comment]
Ok cool, I'll mark as wontfix. Let me know if you think this is a bug in ShellJS though and I can look more closely. Shouldn't be specific to 0.8.5 though because the only difference between that and 0.8.4 was a single patch limited to `shell.exec()`.

**Comment by Mister-CK** [comment]
I thought it was a bug in shelljs, because it was a shelljs command that failed (toEnd()), but on reversing the commits I found that it was updating jshint from 2.13.1 to 2.13.4 that somehow broke that command in the pipeline.
