### ISSUE TITLE
Shelljs type error after version upgrade

### ISSUE THREAD

**Issue by alihamza1214** [shelljs/shelljs#1090]
### Node version (or tell us if you're using electron or some other framework):
12.16.1
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.4
### Operating system:
windows
### Description of the bug:
this.connection = new require('ssh2')();
                                           ^
TypeError: (intermediate value) is not a function
\node_modules\ssh2shell\lib\ssh2shell.js:664:44)

### Example ShellJS command to reproduce the error:
var SSH2Shell = require('ssh2shell'),
    //Create a new instance passing in the host object
    SSH = new SSH2Shell(host)

**Comment by nfischer** [comment]
We don't maintain the "ssh2" module. I think you have the wrong repo.
