### ISSUE TITLE
Can the shelljs/make docs be re-added?

### ISSUE THREAD

**Issue by dead-claudia** [shelljs/shelljs#1091]
Related: https://github.com/shelljs/shelljs/issues/340

I already know its API well (it's super simple and, for the little refresher I need, [the source file is self-explanatory](https://github.com/shelljs/shelljs/blob/master/make.js)), but it might still be worth leaving docs there.

(And yes, I'm literally still greenfielding projects with this, because it's simple and it works. I've *never* run into a bug with it.)

**Comment by nfischer** [comment]
Is this what you're looking for? https://github.com/shelljs/shelljs/wiki/The-make-utility

Let me know if that's satisfactory or if I should reopen this.

**Comment by dead-claudia** [comment]
Oh, I missed that. Thanks for the link!
