### ISSUE TITLE
why shell.exec 'java -version' result output is in the stderr

### ISSUE THREAD

**Issue by cdk8s-zelda** [shelljs/shelljs#1093]
### Node version (or tell us if you're using electron or some other framework):

- node: 16.14.2
- electron: 16.2.3

### ShellJS version (the most recent version/Github branch you see the bug on):

- 0.8.5

### Operating system:

- macOS 12.3.1

### Description of the bug:

- shell.exec 'java -version' result output is in the stderr

### Example ShellJS command to reproduce the error:

```javascript
const shell = require('shelljs');
let execBinPath = (shell.which('java').toString());
shell.config.execPath = execBinPath;

shell.exec('java -version', function (code: any, stdout: any, stderr: any) {
  console.log('Exit code:', code);
  console.log('Program output:', stdout);
  console.log('Program stderr:', stderr);

  if (code !== 0) {
    alert('error!');
    alert(stderr);
  } else {
    console.log('success!');
    alert(stdout);
  }
});
```

```
console result：

/usr/bin/java
Exit code: 0
Program output: 
Program stderr: java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
success!

```

**Comment by nfischer** [comment]
This code looks wrong to me:

> ```javascript
> let execBinPath = (shell.which('java').toString());
> shell.config.execPath = execBinPath;
> ```

`shell.config.execPath` is supposed to point to the NodeJS binary, not to the executable you want to run (`/usr/bin/java`). Try removing those lines of code and see if it works as expected.

**Comment by nfischer** [comment]
If you're running inside of electron, then you'll need to set `execPath` to `/usr/bin/node` or wherever your node install lives. See https://github.com/shelljs/shelljs/wiki/Electron-compatibility
