### ISSUE TITLE
I want to enter keyboard keys after running a command how to do it using shelljs?

### ISSUE THREAD

**Issue by AtiaK** [shelljs/shelljs#1096]
await shell.cd(`~/documents/expotestapp`)
    .exec(`expo build:android -t app-bundle`)

I want to automate the build want to add all options /inputs in exec function

**Comment by nfischer** [comment]
Are you asking about interactive input (issue #424)? An example of "interactive input" would be how `npm init` prompts you to type in your module name and other info like that.

If I didn't understand correctly, would you be able to clarify further?

**Comment by AtiaK** [comment]
Thank you for your response, I'm asking for provding all required options of command through shell js

**Comment by Tate-Young** [comment]
+1

**Comment by AtiaK** [comment]
Thank you for your response @Tate-Young
