### ISSUE TITLE
Stdout isn't the same as running it through CLI

### ISSUE THREAD

**Issue by tansanDOTeth** [shelljs/shelljs#1100]
### Node version (or tell us if you're using electron or some other framework):
v16.13
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.5
### Operating system:
macOS 12.5
### Description of the bug:
I am using the exec function to run `git clone ...` and the stdout does not show the full messages.

Expected:
```bash
$ git clone https://github.com/shelljs/shelljs.git
Cloning into 'shelljs'...
remote: Enumerating objects: 4863, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 4863 (delta 73), reused 121 (delta 65), pack-reused 4718
Receiving objects: 100% (4863/4863), 1.36 MiB | 983.00 KiB/s, done.
Resolving deltas: 100% (3325/3325), done.
```

Actual:
```bash
Cloning into 'shelljs'...
```

### Example ShellJS command to reproduce the error:

```javascript
sh.exec("git clone https://github.com/shelljs/shelljs.git", {}, (code, stdout, stderr) => {
    console.log("stdout", stdout)
});
/*
stdout:
Cloning into 'shelljs'...
stdout
*/

```

**Comment by nfischer** [comment]
What does `stderr` show? On my machine, `git clone` prints the output to stderr instead of stdout. I'm using git version 2.25.1 on Ubuntu.

I'm closing this because I assume this is just going to `stderr` instead of `stdout`, but please reopen if you find this is not the case.
