### ISSUE TITLE
is there any way to create multiple shelljs instance?

### ISSUE THREAD

**Issue by kknono** [shelljs/shelljs#1105]
### Node version (or tell us if you're using electron or some other framework):
v16.17.0
### ShellJS version (the most recent version/Github branch you see the bug on):
latest
### Operating system:
centos/ macos
### Description of the bug:
cannot create  multiple shelljs instance
### Example ShellJS command to reproduce the error:

```javascript




```
backgroud:
A: one thread execute  shelljs.cd(A path) && shelljs.exec('npm run build')(need 10s)
B: another thread execute shelljs.cd(B path) && shelljs.exec('npm run build')(need 10s)

when execute at same time, error confused.

so, can we create different instance? like:  const shellA=new shelljs().   const shellB=new shelljs(). and they do in separate terminal？

best regards

**Comment by nfischer** [comment]
This is not generally supported.

The best way to do this would be to create two separate JavaScript files which each use shelljs, and then to use a 3rd script to execute the two others via `shell.exec()` (or something similar). This will execute the two scripts in separate processes with independent copies of ShellJS.

**Comment by nfischer** [comment]
Please see #865 for more discussion on this topic.
