### ISSUE TITLE
the code on [npm.js  ](https://www.npmjs.com/package/shelljs) is not up-to-date(Compare with [github]

### ISSUE THREAD

**Issue by cmdreay** [shelljs/shelljs#1115]
### Node version (or tell us if you're using electron or some other framework):
v12.18.1
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.5
### Operating system:
win10
### Description of the bug:
the code on [npm.js  ](https://www.npmjs.com/package/shelljs) is not up-to-date(Compare with [github](https://github.com/shelljs/shelljs))，can you update it?
### Example ShellJS command to reproduce the error:

```javascript
// see [npm](https://www.npmjs.com/package/shelljs?activeTab=explore) mv.js line 115,116
cp('-r', src, thisDest);
rm('-rf', src);
// the correct code on github is
cp({ recursive: true }, src, thisDest); 
rm({ recursive: true, force: true }, src);
```

**Comment by nfischer** [comment]
I haven't pushed an update for a while. There are some blocking issues on tip-of-tree that need to be resolved before the 0.9 update. You can watch https://github.com/shelljs/shelljs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3Av0.9.0 to see progress.
