### ISSUE TITLE
npm WARN EBADENGINE Unsupported engine

### ISSUE THREAD

**Issue by abbaty48** [shelljs/shelljs#1116]
### Node version (or tell us if you're using electron or some other framework):
Node version: v19.2.0
I am using Electron-forge  with react

### ShellJS version (the most recent version/Github branch you see the bug on):
Shelljs version: ^0.8.5

### Operating system:
Windows11

### Description of the bug:
Am getting an errror:

STDERR:  npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'node-abort-controller@3.1.0',
npm WARN EBADENGINE   required: { node: '<14.7.0' },
npm WARN EBADENGINE   current: { node: 'v19.2.0', npm: '7.24.2' }
npm WARN EBADENGINE }

### Example ShellJS command to reproduce the error:
 
```javascript
 shell.exec(
                      'echo shell.exec works && npm install',
                      (code, stdout, stderr) => {
                        console.log('CODE: ', code);
                        console.log('STDOUT: ', stdout);
                        console.log('STDERR: ', stderr);
                      }
                    );
```

**Comment by nfischer** [comment]
It looks to me like the `npm install` command is providing warning output and `shell.exec()` is printing this output as you have coded. Can you explain what you were expecting to happen instead?

**Comment by abbaty48** [comment]
@nfischer, I am expecting the `code` to return any non-zero (success). what i think is that, shelljs is expecting a node of version <14.7.0 installed on my pc while am having v19.2.0 installed, and if i installed node <14.7.0 my electron wouldn't run.

**Comment by abbaty48** [comment]
if I open a terminal and run `npm install` i got the result as:
```
`npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.

added 233 packages, and audited 385 packages in 41s

5 packages are looking for funding
  run `npm fund` for details

21 vulnerabilities (11 moderate, 8 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.`
```

-- but if i use shelljs to execute the `npm install`  i got this error:
STDERR: npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE package: 'node-abort-controller@3.1.0',
npm WARN EBADENGINE required: { node: '<14.7.0' },
npm WARN EBADENGINE current: { node: 'v19.2.0', npm: '7.24.2' }
npm WARN EBADENGINE }

**Comment by nfischer** [comment]
> @nfischer, I am expecting the `code` to return any non-zero (success).

You have that backward. 0 means success. Non-zero means failure. This is the standard unix convention.

> what i think is that, shelljs is expecting a node of version <14.7.0 installed on my pc while am having v19.2.0 installed, and if i installed node <14.7.0 my electron wouldn't run.

ShellJS should be compatible with either nodejs version. The error message is not coming from ShellJS though. The error message is coming from the `npm` binary. See the below error message:

```
npm WARN EBADENGINE package: 'node-abort-controller@3.1.0',
npm WARN EBADENGINE required: { node: '<14.7.0' },
```

This means that `npm` is running using nodejs 19.2.0. No problem so far, but you're running the `npm install` command and this is installing `node-abort-controller@3.1.0`. The `node-abort-controller` project claims it is incompatible with node > 14.7.0. It indicates this compatibility in its package.json file using the `engines` attribute. `npm` realizes that the package wants node < 14.7.0 but you're using node > 14.7.0, so it prints `npm WARN EBADENGINE` to tell you this is a problem. Take a look at this documentation: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines

BTW you should take a look at https://www.npmjs.com/package/node-abort-controller. This page says you **should not** use the package if you're using node > 14.7.0 (and it explains why).

> if I open a terminal and run `npm install` i got the result as:

The only explanation for this is that you have configured ShellJS differently than your terminal environment. I can think of 2 possible explanations:

1. Your terminal is running npm using a lower NodeJS version. If this is the case, then you should probably either upgrade that node version or configure ShellJS to use that same node version (you can choose whichever option you prefer); or
2. You have configured npm (in the terminal) to ignore the `package.engines` warning and have configured npm (when run by ShellJS) to check this warning. It could be the case that you've done so accidentally; maybe there is some configuration in your dotfiles, something configured by `nvm` (if you're using that sort of thing), or maybe even npm itself is configured to behave differently in an interactive session.

Either way, this isn't something we'll be able to support in `shell.exec()`. This sounds like it's best to check your environment.

**Comment by abbaty48** [comment]
@nfischer thank you, I was mistaken, I told 0 was failed, I have already moved with that. Thank you
