### ISSUE TITLE
run string  --> shelljs -e 'echo("hello")'

### ISSUE THREAD

**Issue by dearfrankg** [shelljs/shelljs#112]
run string  --> shelljs -e 'echo("hello")'

**Comment by nfischer** [comment]
This is related to #244. @dearfrankg would that be a suitable alternative?

**Comment by nfischer** [comment]
Closing this, since I think our new repo, [shelljs/shx](https://github.com/shelljs/shx), should be a suitable alternative. Please reopen if this is not sufficient.
