### ISSUE TITLE
shell.exec(`mv a/m.js b/`) cannot return error stdout

### ISSUE THREAD

**Issue by TulipLi** [shelljs/shelljs#1147]
### Node version (or tell us if you're using electron or some other framework):
16.14.0
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.5
### Operating system:
gitlab CI
### Description of the bug:
when I run this command ```shell.exec('mv a/m.js b/)```
and a/m.js is not exist, then will console no such file or directory,
but when I use
```javascript
const res = shell.exec(`mv a/m.js b/`)
console.log('res:' + res)
// this return an empty string
// res:''
```
what I want is to get the error code or error message to do something.
### Example ShellJS command to reproduce the error:

```javascript
const res = shell.exec(`mv a/m.js b/`)
console.log('res:' + res)
// this return an empty string
// res:''
```

seems like delete ```{ continue: true }``` can fix this issue
<img width="679" alt="image" src="https://github.com/shelljs/shelljs/assets/24578248/79dd6c98-56a0-40b5-ae6f-db496e6d4b49">

```
if (!fs.existsSync(src)) {
      common.error('no such file or directory: ' + src);
      return; // skip file
}
```

**Comment by nfischer** [comment]
Did you try `console.log('res:' + res.stderr)`? The `.stderr` property is where the error message lives.

Check out https://github.com/shelljs/shelljs#shellstringstr

**Comment by nfischer** [comment]
I'm going to assume the `.stderr` property solves this for you. Let me know if you're still seeing issues and we can look again.
