### ISSUE TITLE
shelljs.exec or child_process.exec not executing 

### ISSUE THREAD

**Issue by majumadhusudanan2024** [shelljs/shelljs#1154]
### Example ShellJS command to reproduce the error:

```javascript

```

I'm invoking shell commands using shelljs.exec() and child_process.exec() from macOS menulet app (menubar app). Menubar runs  indefinitely till user quit the application.

Recently we found an issue related with exec() function (shellJS and child_process). This function is not returning / not executing the success function when machine/application is kept idle for long hours.

There is no error or exception coming in logs. In the below code snippet, callback function ((error, stdout, stderr) ) never executes, if machine/app is kept idle for long hours. I can replicate the issue on demand also.

console.log("Before executing EXEC [L]");
    exec("ls -la", (error, stdout, stderr) => {
      if (error) {
          console.log(`error: ${error.message}`);
          return;
      }
      if (stderr) {
          console.log(`stderr: ${stderr}`);
          return;
      }
      console.log(`stdout: ${stdout}`);

      console.log("****Finished execution EXEC()");
  });

What should be the issue? How do i troubleshoot this issue to get more detailed logs? 

The following are the environment details:

NodeJS : v20.10.0
macOs version : sonoma 14.3
ShellJS version : 0.8.5

**Comment by nfischer** [comment]
If this bug reproduces with `child_process.exec()`, then unfortunately there's nothing we can do as part of the ShellJS project. You would need to raise this issue as a bug against nodejs itself.

**Comment by majumadhusudanan2024** [comment]
Reopened https://github.com/nodejs/node/issues/52149
