### ISSUE TITLE
Attempted to import the Node standard library module "fs"

### ISSUE THREAD

**Issue by camzilla1050** [shelljs/shelljs#1156]
### Node version (or tell us if you're using electron or some other framework):
react-native
node  --version: v20.12.2
expo-cli --version: 6.3.10

### ShellJS version (the most recent version/Github branch you see the bug on):
shelljs version": "0.8.5"

### Operating system:
Manjaro Linux

### Description of the bug:
"fs" module "version": "0.0.1-security" added in node_modules but not recognized 
Look that only 2 files in the module fs, no index.js present 
fs
├── package.json
└── README.md

### Example ShellJS command to reproduce the error:

```javascript
var shell = require('shelljs');
shell.echo('hello world');

```
### Error on terminal :
```javascript
$ yarn start 

Android Bundling failed 2730ms (node_modules/expo/AppEntry.js)
The package at "node_modules/shelljs/src/common.js" attempted to import the Node standard library module "fs".
It failed because the native React runtime does not include the Node standard library.

```

**Comment by nfischer** [comment]
ShellJS only works in a nodejs environment. If you're trying to use this in the browser (via React), then it won't work. ShellJS needs file system access, and `fs` is the file system module.

Can you tell me what you're trying to achieve with shelljs in the browser? Maybe there's another module which can handle that use case.
