### ISSUE TITLE
Please update dependency

### ISSUE THREAD

**Issue by Thaina** [shelljs/shelljs#1162]
### Node version (or tell us if you're using electron or some other framework):
18.20.2

### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.5

### Operating system:
Windows

### Description of the bug:

```
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

It seem `inflight` was dependency of `glob@7` so maybe just need update to `glob@10` ?

### Example ShellJS command to reproduce the error:
npm install shelljs

**Comment by nfischer** [comment]
Duplicate of issue #1149
