### ISSUE TITLE
package.json version is outdated

### ISSUE THREAD

**Issue by kitsguru** [shelljs/shelljs#1170]
Current package.json still says version is 0.8.3, yet 0.8.5 has been released.

**Comment by nfischer** [comment]
0.8.4 and 0.8.5 were both created from a release branch. These were small bug fix releases where the patches landed on the `master` branch, but then I cherrypicked the commits to the release branch and bumped the version number there. Here's a link to the release branch if you need to inspect the code: https://github.com/shelljs/shelljs/tree/0.8-release. And here's a list of the commits on that branch, where you will see that 0.8.4 and 0.8.5 represent the last 4 commits on that branch: https://github.com/shelljs/shelljs/commits/0.8-release/

**Comment by kitsguru** [comment]
The release branch is 4 commits ahead of master and 78 commits behind. Which branch should I actually use for my project. I think 0.8.5 is on NPM.

**Comment by nfischer** [comment]
If you're using shelljs as a dependency, then you should install the latest version (0.8.5) using `npm install`. The GitHub `master` branch is for development and isn't yet ready to cut another release.
