### ISSUE TITLE
Use make to call asynchronous tasks

### ISSUE THREAD

**Issue by jiyinyiyong** [shelljs/shelljs#121]
Quite some tasks in Node are running asynchronously that makes it hard to chain with `target.task`.
Like RequireJS which uses `.done` to add callback, and Browserify which use `exorcist` and `fs.createWriteStream` to finish writing file.
Is there are good solution for `shelljs/make` to make it easier to script rather than hacking with callbacks or something else?

**Comment by nfischer** [comment]
I'm tentatively labeling this as "won't fix" since we're thinking of deprecating the `make` functionality. If someone still wants this as an option, please bump this thread and we'll gladly revisit this.
