### ISSUE TITLE
Use case for global installed shelljs

### ISSUE THREAD

**Issue by coodoo** [shelljs/shelljs#123]
I find the description to have shelljs installed globally quite interesting - especially the avoiding bash script part, could any one shed a light on how some of the use cases could be? Thanks.

**Comment by nfischer** [comment]
@coodoo not sure if this is still an issue, but I thought I'd share how I use shelljs.

I've installed it globally with `npm install -g shelljs`. I also modified my `NODE_PATH` variable to point to where it's installed.

Now I can run a REPL like this from any directory:

```javascript
$ node
> require('shelljs/global');
> pwd();
'/home/user/path/to/dir'
> ls();
[ 'file.txt',
  'file2.txt' ]
> exit(0);
$
```

Also, in any directory, I can write a simple shelljs script:

```Bash
# assume file.js is an already existing shelljs script
$ cat file.js
require('shelljs/global');
echo('hello world');
$ shjs file.js
hello world
```

I also have rewritten some of my shell scripts in `~/bin/` to be shelljs scripts. I give those `+x` permission and I make sure they have the node shebang (`/usr/bin/env node`), and now I can run those from anywhere as well.

Hope this helps :+1:
