### ISSUE TITLE
installed shelljs on osx but reported error: npm ERR! 404 '%5B-g%5D' is not in the npm registry.

### ISSUE THREAD

**Issue by kaisatec** [shelljs/shelljs#124]
GET https://registry.npmjs.org/%5B-g%5D
npm http GET https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/shelljs
npm http 404 https://registry.npmjs.org/%5B-g%5D
npm ERR! 404 '%5B-g%5D' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 12.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "[-g]" "shelljs"
npm ERR! cwd /Users/myname
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/myname/npm-debug.log
npm ERR! not ok code 0

node v0.10.22
npm 1.3.14
your comment welcome

**Comment by Sonirjodxpro** [comment]
I have get the same question . do you fixed the question?

**Comment by nfischer** [comment]
I don't know what `%5B-g%5D` is. I don't think this is a ShellJS bug, but rather an npm registry issue.
