### ISSUE TITLE
shelljs and node 0.10.28

### ISSUE THREAD

**Issue by joques** [shelljs/shelljs#125]
Hi,
can I use shelljs with a node version higher than 0.10.26? I've upgraded yesterday from 0.10.26 to 0.10.28 and now my shelljs exec function stalls. I went back and checked the changes to node and realized that there were some changes in 0.10.27 regarding child process. I just don't know if these changes have been integrated to shelljs.
Which version of node.js should be used with shelljs 0.3.0?
thanks

**Comment by nfischer** [comment]
@joques is this still an issue? I ran it on my system (ShellJS `v0.6`, node `v0.10.28`, Ubuntu 15.10) with no issues, so I suspect this either got resolved, or is specific to your system. Here's what I ran:

```Javascript
require('shelljs/global');
echo(exec('hostname', {silent: true}).stdout);
```
