### ISSUE TITLE
add timeout option for exec

### ISSUE THREAD

**Issue by dcharbonnier** [shelljs/shelljs#132]
http://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by manovotny** [comment]
Gosh I want this feature so bad right now. :frowning: 

Might have to roll up my sleeves and make a pull request!

**Comment by HQidea** [comment]
+1
and maybe it can also pass other options to child_process.exec[Sync]

**Comment by lizzie** [comment]
+1

**Comment by nfischer** [comment]
:+1: I think this would be a good feature to add. I see a trend that most people want the native options to be exposed, so I suspect we'll modify `exec()` to support all native options. I'll tag this issue in a PR over the next couple weeks.

**Comment by ariporad** [comment]
Ok, this in fixed in #335, so I'm going to close this.

**Comment by westlakem** [comment]
Ok, but how do I specify the timeout?

**Comment by nfischer** [comment]
@westlakem 

https://github.com/shelljs/shelljs/blob/d7b6a1f3784fa6f9d1abcc07fcec6d08e89bf294/test/exec.js#L130
