### ISSUE TITLE
shjs command always exits with zero code

### ISSUE THREAD

**Issue by ndelitski** [shelljs/shelljs#133]
Lets write a simple test ``test.js``
```js
process.exit(1)
```
then after i type ``shjs test.js || echo 1`` console gives me no output, but ``node test.js || echo 1`` ended with 1 code as expected. Tested in Linux and Windows. 

Maybe I do not catch up something... But obviously ``shjs`` must persist exit code from script it running and i see this logic in ``shjs`` file, but in `./bin/shjs` new child node process doesn't pass exit code to main process. Is the failed child process should not ruin parent process with error exit code? Maybe because it is asynchronous...

So I wait until the subprocess is completed and manualy close main process with the same exit code then all works perfect.
```js
exec('node ' + scriptName + ' ' + args.join(' '), {async: true}, function(code) {
      exit(code);
});
```

**Comment by mastern2k3** [comment]
bump,
I'm using shjs with TeamCity, and this behavior is hiding errors, fixing this would be great..

**Comment by ndelitski** [comment]
any progress so far?

**Comment by nfischer** [comment]
This should now be fixed in master

**Comment by jonaskello** [comment]
I'm also running in to this. Could we have a new npm package with this fix?

**Comment by ariporad** [comment]
@jonaskello: We're working at a new release, we want to do a few more things.

**Comment by patrixd** [comment]
I think this is happening again in the las version of `bin/shjs`.
