### ISSUE TITLE
Can't install shelljs locally instead of globally

### ISSUE THREAD

**Issue by facundofarias** [shelljs/shelljs#136]
As specified on the documentation (http://documentup.com/arturadib/shelljs), I tried installing shelljs locally (given that the option [-g] looks optional), but I am having this issue on the console: 
```
npm WARN package.json shelljs@0.0.0 No repository field.
npm WARN package.json shelljs@0.0.0 No README data
npm WARN install Refusing to install shelljs as a dependency of itself
```
Is this behavior by design? Should I install shelljs always globally? 
Thanks

**Comment by nfischer** [comment]
@facundofarias is this still an issue?

I've had no issues installing shelljs locally (whether as part of package.json or otherwise), so I'll gladly assist if possible. What are the shell commands you're running?

**Comment by facundofarias** [comment]
The issue was filed two years ago. If it cannot be reproduced, then yes, it can be closed :)

**Comment by nfischer** [comment]
Thanks!
