### ISSUE TITLE
shell builtin

### ISSUE THREAD

**Issue by ainthek** [shelljs/shelljs#138]
stupid question: can I call shell-builtin ?
Im trying exec with history
getting:
'history' is not recognized as an internal or external command,
operable program or batch file.
Exit code: 1
Program output: 'history' is not recognized as an internal or external command,
operable program or batch file.

**Comment by nfischer** [comment]
I don't believe Bash built-ins are currently supported, since `exec()` uses `sh` instead of `bash`. See below:

```
$ cat sample.js
require('shelljs/global');
exec('history');

$ shjs sample.js
/bin/sh: 1: history: not found
```

If we switch to bash, then this problem might be resolved. I opened #281 to discuss switching shells.
