### ISSUE TITLE
cp -R dir/ target fails to copy hidden files in dir

### ISSUE THREAD

**Issue by idearat** [shelljs/shelljs#140]
The code for cp appends '*' to the source directory name if it ends with '/'. This causes the resulting file lookup to overlook hidden files in the source directory and fail to copy them.

**Comment by giltayar** [comment]
Workaround: do the same shell.cp again, but add '.*' to the source

**Comment by nfischer** [comment]
Once #275 is merged, I can write up a very quick fix for this.

**Comment by s-panferov** [comment]
Is this fixed in 0.7.0?

**Comment by nfischer** [comment]
I forget when we fixed this, but [this test case](https://github.com/shelljs/shelljs/blob/master/test/cp.js#L319) covers it, so this should be fixed now.

@s-panferov Thanks for pointing out this stale issue!
