### ISSUE TITLE
exec('lessc ... > ...') generates empty files

### ISSUE THREAD

**Issue by adrior** [shelljs/shelljs#142]
Hello!

I try to run [lessc] (http://lesscss.org/usage/#command-line-usage) with exec(). But it's generates empty css file and output resulting css into stdout.

For example, exec('lessc blocks.wizards/wiz-serp-recipe/0.1.0/wiz-serp-recipe.mobile.less > blocks.wizards/wiz-serp-recipe/0.1.0/wiz-serp-recipe.mobile.css') creates empty wiz-serp-recipe.mobile.css file and output resulting css in console. 

If run the same command directly in the shell — it's works fine.

**Comment by nfischer** [comment]
@adrior Hmmmm this should work properly. What system are you running on?

Could you please confirm the same behavior with a simpler command?

```Javascript
exec('echo hello > test.txt');
// for me on Ubuntu 15.10, node v5, this has the empty string as output, and successfully writes to the file
```

**Comment by adrior** [comment]
Now both examples works just fine. Thank you for response!

**Comment by nfischer** [comment]
Glad to hear it works! Thanks for confirming
