### ISSUE TITLE
Would like to see more async variants for cp/rm etc

### ISSUE THREAD

**Issue by d11wtq** [shelljs/shelljs#144]
Currently shelljs is useful in test suites and such like, but not so useful in a production nodejs app, if there's a need to copy/delete directories recursively, since it doesn't offer async variants of these filesystem commands. Is this a matter of principle, or just that the work hasn't yet been done?

**Comment by nfischer** [comment]
Marking this as a duplicate of #2

**Comment by nfischer** [comment]
Let's continue the discussion on #2
