### ISSUE TITLE
`.to(file)` does not mute STDIO output

### ISSUE THREAD

**Issue by aurium** [shelljs/shelljs#146]
`node -e "require('shelljs/global'); echo('some words').to('/dev/null')"`
Must not print `some words` on console.

**Comment by aurium** [comment]
Consider this related to issue #154, so any output must be silenced when piped to a file.

**Comment by nfischer** [comment]
Any thoughts on how to solve this?

**Comment by nfischer** [comment]
Blocked on issue #800. @freitagbr we could probably just merge this into that issue.

**Comment by nfischer** [comment]
Merging into #800
