### ISSUE TITLE
`exec(...).to(file)` should work

### ISSUE THREAD

**Issue by aurium** [shelljs/shelljs#154]
We know `exec(...).output.to(file)` works, but... why to be so verbose?

`node -e "require('shelljs/global'); exec('git status').to('/tmp/file')"` should work.

**Comment by ariporad** [comment]
Hmm... I'm not sure. On one hand it makes sense, but the other it's confusing.

@nfischer: Do you think we should implement this?

**Comment by nfischer** [comment]
@ariporad I was thinking of something similar actually. I was thinking of refactoring everything to return a `ShellString` which acts like a string, but also has a `.code`, `.stdout` (equivalent to default behavior), and `.stderr`, among some other features. If `exec()` gets refactored too, then either style would work.

**Comment by ariporad** [comment]
@nfischer: Hmm... I think it would make more sense if everything returned a ShellResult, because the stdout duplication would be weird.

**Comment by ariporad** [comment]
Alternatively, the ShellString could contain all output (stdout + stderr), then we could have ShellString.stdout/stderr.

**Comment by nfischer** [comment]
This is related to #148

**Comment by nfischer** [comment]
This will be resolved in #360.

Once that is merged, the **only** way to achieve this is with `exec(...).to(file)`, as `exec(...).output.to(file)` and `exec(...).stdout.to(file)` will actually no longer work

**Comment by nfischer** [comment]
Closing this. Please see my comment above if you see a break in behavior
