### ISSUE TITLE
implement mktemp

### ISSUE THREAD

**Issue by aurium** [shelljs/shelljs#155]
Something simpler than http://linux.die.net/man/1/mktemp
```javascript
file = mktemp()
// do something
```
is better than
```javascript
file = exec('mktemp').output
// do something
```

That can also accept the same [unix's mktemp](http://linux.die.net/man/1/mktemp) params:
```javascript
function mktemp() {
  var lastArg = arguments[arguments.length-1], opts = {};
  if ( lastArg && lastArg.constructor == Object ) opts = lastArg;
  arguments.indexOf = [].indexOf;
  if (arguments.indexOf('u') > 0 || arguments.indexOf('dry-run') > 0) opts.dryRun = true;
  if (arguments.indexOf('q') > 0 || arguments.indexOf('quiet') > 0) opts.quiet = true;
  if (arguments.indexOf('d') > 0 || arguments.indexOf('directory') > 0) {
    _mktemp_dir(opts)
  } else {
    _mktemp_file(opts)
  }
}
```
...and that allows:

```javascript
// Javascript
file = mktemp('directory', {suffix: 'test'})
```

```coffee
# Coffeescript
file = mktemp 'directory', suffix: 'test'
```

**Comment by ariporad** [comment]
@aurium: Are you aware of `tmpdir()`? I agree that the name is a little strange, I'll open an issue to rename it.

**Comment by nfischer** [comment]
This sounds like it's also creating a temporary directory, which `tempdir()` does not do

**Comment by ariporad** [comment]
@nfischer: hmm... Thoughts on doing that?

**Comment by nfischer** [comment]
I'm not familiar with what support node provides, or if this makes sense to do on Windows. I think using the directory provided by `tempdir()` has been working well for most people, so that wouldn't be a priority for me.
