### ISSUE TITLE
high cpu usage during synchronous exec

### ISSUE THREAD

**Issue by MetaMemoryT** [shelljs/shelljs#167]
Still getting 45% cpu usage when running synchronous exec on windows 8.1

**Comment by ariporad** [comment]
@MetaMemoryT: Yeah, that's a side effect of our trying to make `exec` synchronous (Node doesn't support that by default). I don't really think there's anything we can do about it.

@nfischer: Thoughts?

**Comment by nfischer** [comment]
I think some steps have been taken to reduce cpu usage for newer versions of node. @MetaMemoryT does the issue persist with node v5?

**Comment by sedwards2009** [comment]
Is using sleep() from https://www.npmjs.com/package/sleep an option? I appears to use a system call to sleep/stop the process for a given amount of time and it shouldn't burn CPU.

**Comment by boutell** [comment]
Isn't this a dead issue thanks to execSync being used in versions of Node that support it (0.12 and better)? Or am I missing something?

**Comment by nfischer** [comment]
@boutell thanks for pinging this issue. Yes, since we already dropped v0.10 support, I believe this can be safely closed.

**Comment by SuhairZain** [comment]
@nfischer Is this note in the README still relevant? Also, is this issue present only on Windows or on Unix platforms as well?
```
Note: For long-lived processes, it's best to run exec() asynchronously as the current synchronous implementation uses a lot of CPU. This should be getting fixed soon.
```

**Comment by nfischer** [comment]
@SuhairZain nope :smile: And #825 removes that line.
