### ISSUE TITLE
Is there a way to suppress pushd/popd output?

### ISSUE THREAD

**Issue by justinmchase** [shelljs/shelljs#171]
Normally I could pipe it to /dev/null but I don't know how to do that in shelljs. The stuff it prints out is not useful to me and it adds a lot of visual clutter. I would like to have a way to suppress the output but I can't quite figure out how to do it.

**Comment by justinmchase** [comment]
Thanks, I wish this was on pushd/popd functions themselves instead of exec but it'll do for now.

**Comment by brillout** [comment]
Same here, I wish this could be set on the pushd/popd functions themselves

**Comment by nfischer** [comment]
I'm not as familiar with popd and pushd. Is there a convention for silencing output in bash?

**Comment by justinmchase** [comment]
In bash, per line you can pipe out put to null basically. Doesn't appear to
be possible per call in shelljs.

**Comment by nfischer** [comment]
Right. So the convention I would suggest for now would be:


```js
shell.config.silent = true;
popd();
shell.config.silent = false;
```

I'm open to syntax suggestions for adding this to the command call itself :smile:

**Comment by nfischer** [comment]
If `popd` has some special "stay quiet" flag, I'll gladly take a PR for that too. Or if our `popd()` differs in default behavior from bash's `popd`, let's fix that

**Comment by ariporad** [comment]
@nfischer: I just had a great idea: What if we used option chains, like this:

```javascript
shell.popd.silent(...);

// Also possible.
shell.command.to('/foo/bar')(args)
```

**Comment by nfischer** [comment]
I don't like the second syntax, since redirects are usually at the end in bash. I can't remember for sure if this is *required*, but it's definitely most intuitive.

The first one could be promising. Another syntax idea is `cmd(arg1, arg2, {silent: true})`. This conforms with the common style of "options go at the end", whereas the `cmd.silent(arg1, arg2)` approach reminds me of `ava`.

Does anyone in the community have any thoughts on this?

**Comment by nfischer** [comment]
Another idea, if we go with an object as the last parameter:

```js
cmd(arg1, arg2, {'>': 'file.txt'});
cmd(arg3, arg4, {'>>': 'foo.txt'});
// maybe support '2>' and '&>' as well
// maybe shorten it to {'1': 'file.txt'}
```

**Comment by justinmchase** [comment]
That looks pretty hot.

**Comment by ariporad** [comment]
@nfischer: also:

```javascript
cmd(arg1, arg2, ['output.txt', '&1'])
```

**Comment by MattSturgeon** [comment]
Worth noting that in [ZSH](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html) `popd` has a `-q` flag:

> **`popd [ -q ] [ {+|-}n ]`**
> 
> Remove an entry from the directory stack, and perform a cd to the new top directory. With no argument, the current top entry is removed. An argument of the form ‘+n’ identifies a stack entry by counting from the left of the list shown by the dirs command, starting with zero. An argument of the form -n counts from the right. If the PUSHD_MINUS option is set, the meanings of ‘+’ and ‘-’ in this context are swapped.
>
> **If the -q (quiet) option is specified**, the hook function chpwd and the functions in the array $chpwd_functions are not called, and the new directory stack is not printed. This is useful for calls to popd that do not change the environment seen by an interactive user.

**Comment by nfischer** [comment]
@MattSturgeon  I filed this as #753, thanks for the suggestion.
