### ISSUE TITLE
shelljs 0.3.0 - child process not terminated when its task finished 

### ISSUE THREAD

**Issue by jihao** [shelljs/shelljs#178]
I am using shelljs.exec and shelljs.rm in a callback which takes a list of filename and do some business.  

the main program was a long running process which will run for like 30 minutes, and I find lots of node child process were generated and not terminated during the main program running life cycle.

I was expecting after I call shelljs.rm, the child process should be terminated. 

[hadoop@master-26161 bin]$ ps -ef | grep node  | wc -l
1640

hadoop   14783 14653 34 01:59 pts/0    00:10:12 node main_program.js 
hadoop   14819 14783  0 02:00 pts/0    00:00:07 [node] <defunct>
hadoop   14845 14783  0 02:00 pts/0    00:00:00 [node] <defunct>
hadoop   14865 14783  0 02:00 pts/0    00:00:01 [node] <defunct>
hadoop   14870 14783  0 02:00 pts/0    00:00:01 [node] <defunct>
hadoop   14882 14783  0 02:00 pts/0    00:00:02 [node] <defunct>
hadoop   14889 14783  0 02:00 pts/0    00:00:00 [node] <defunct>
hadoop   14898 14783  0 02:00 pts/0    00:00:00 [node] <defunct>
hadoop   14902 14783  0 02:00 pts/0    00:00:00 [node] <defunct>
hadoop   14906 14783  0 02:00 pts/0    00:00:00 [node] <defunct>

**Comment by ariporad** [comment]
@jihao: Would you mind testing this with the latest version of shelljs? Thanks!

**Comment by nfischer** [comment]
^ latest version in the github repo (since we haven't done a release in a while)

**Comment by nfischer** [comment]
Closing this, due to lack of activity (and I doubt it's still a real issue).
