### ISSUE TITLE
"Cannot extract package" with node-webkit

### ISSUE THREAD

**Issue by chirantan** [shelljs/shelljs#181]
I successfully used shelljs on node console. It does exactly what I need. However, when I use it with node-webkit, it gives me this error (Copy-paste it in browser's address-bar)

```
data:text/html;charset=utf-8,<html>%0A<head>%0A<title>Cannot%20run%20package<%2Ftitle>%0A<style>%0A*%7B%20margin%3A%200%3B%20padding%3A%200%3B%7D%0A%0Abody%20%7B%0A%20%20overflow%3A%20hidden%3B%0A%7D%0A%0Ap%2C%20h1%20%7B%0A%20%20display%3A%20inline-block%3B%0A%20%20margin-left%3A%20100px%3B%0A%20%20color%3A%20%23333%3B%0A%20%20font-family%3A%20sans-serif%3B%0A%7D%0A%0A%23clouds%7B%0A%20%20padding%3A%20100px%200%3B%0A%20%20background%3A%20%23c9dbe9%3B%0A%20%20background%3A%20-webkit-linear-gradient(top%2C%20%23c9dbe9%200%25%2C%20%23fff%20100%25)%3B%0A%7D%0A%0A.cloud%20%7B%0A%20%20width%3A%20200px%3B%20height%3A%2060px%3B%0A%20%20background%3A%20%23fff%3B%0A%20%20%0A%20%20-webkit-border-radius%3A%20200px%3B%0A%20%20%0A%20%20position%3A%20relative%3B%20%0A%7D%0A%0A.cloud%3Abefore%2C%20.cloud%3Aafter%20%7B%0A%20%20content%3A%20''%3B%0A%20%20position%3A%20absolute%3B%20%0A%20%20background%3A%20%23fff%3B%0A%20%20width%3A%20100px%3B%20height%3A%2080px%3B%0A%20%20position%3A%20absolute%3B%20top%3A%20-15px%3B%20left%3A%2010px%3B%0A%20%20%0A%20%20-webkit-border-radius%3A%20100px%3B%0A%20%20-webkit-transform%3A%20rotate(30deg)%3B%0A%7D%0A%0A.cloud%3Aafter%20%7B%0A%20%20width%3A%20120px%3B%20height%3A%20120px%3B%0A%20%20top%3A%20-55px%3B%20left%3A%20auto%3B%20right%3A%2015px%3B%0A%7D%0A%0A.x1%20%7B%0A%20%20-webkit-animation%3A%20moveclouds%2030s%20linear%20infinite%3B%0A%20%20opacity%3A%200.8%3B%0A%7D%0A%0A%40-webkit-keyframes%20moveclouds%20%7B%0A%20%200%25%20%7Bmargin-left%3A%20800px%3B%7D%0A%20%20100%25%20%7Bmargin-left%3A%20-800px%3B%7D%0A%7D%0A<%2Fstyle>%0A<%2Fhead>%0A<body>%0A%20%20<div%20id%3D"clouds">%0A%20%20%20%20<h1>Cannot%20extract%20package<%2Fh1>%0A%20%20%20%20<br%2F><br%2F>%0A%20%20%20%20<p>Failed%20to%20unzip%20the%20package%20file%3A%20%2Fvar%2Ffolders%2Fgf%2Fvrxmn3p161nb_h21w21qcrwr0000gn%2FT%2Fshelljs_3cb35822f62b70c4bacc<%2Fp>%0A%20%20%20%20<div%20class%3D"cloud%20x1"><%2Fdiv>%0A%20%20<%2Fdiv>%0A<%2Fbody>%0A<%2Fhtml>%0A
```

I've googled this and came across a similar issue here – https://github.com/nwjs/nw.js/issues/1493. But the solution doesn't seem to be in my hands. My node version is v0.10.33 and node-webkit version is 0.11.5. I'm using OSX 10.10.1.

Has anybody faced this problem?

**Comment by JohnnyMarnell** [comment]
having same problem.  don't want to switch to child_process :-/

**Comment by thunderace** [comment]
Same here. node-webkit 0.12.0-alpha2-win-ia32.

**Comment by MarianoRemedi** [comment]
I'm new in this and I was having the same problem "Cannot extract package", "Failed to unzip the package file: ". 
My problem was that when I renamed the zip file, the .zip extension was still there e.g.: app.nw.zip (now that I see it I was little bit stupid I think). 
So the .nw extension was  part of the file name and it wasn't an extension
I'm using WinRar, what I did was:
-Open winrar and select the package.json and index.html files and press add button.
-In archive name  I wrote: app.nw
-In Archive format: ZIP
-"OK" button.

This way, the file extension es .nw

The app.nw file is in the same directory where nw.exe is. I dragged and dropped it over the nw.exe and it works.

I don't know if this is the best way to do it, but it works for me.

Sorry if there are any typos, I'm from Argentina.

**Comment by AlexisCaffa** [comment]
Possible problems:

a) Guess NodeWebKit zip module dosen't quite support unicode path. Ex.: Look for hidden files name ending with ~ and delete all..
b) The limit of 260 characters of route on win32

**Comment by zzuhan** [comment]
Same problem。
`Failed to unzip the package file: var/folders/56/pgyp3jdx185c2vnvqc_5xk7r0000gn/T/shelljs_f41bba3860ab2159fd1a` 

shelljs create this file, and the name has uppercase and number, I think it's the problem.

**Comment by ariporad** [comment]
@chirantan, @JohnnyMarnell, @thunderace, @MarianoRemedi, @AlexisCaffa, @zzuhan: Is this an issue with shelljs? I'm not sure.

**Comment by nfischer** [comment]
Doesn't appear to be something we can solve. If this is still an issue, ping this thread.
