### ISSUE TITLE
cp -r breaks when the directory contains a softlink

### ISSUE THREAD

**Issue by crjobson** [shelljs/shelljs#193]
Assuming you have the following folder structure:
```
.
+-- foo/
    +-- bar      # softlink to ../bar
    +-- baz
        +-- qux  # softlink to ../../qux
        +-- quux # softlink to ../../quux
+--- bar/
    +--- file1
    +--- file2
+--- qux/
+--- quux/
+--- ...
```

When you do:

```javascript
cp('-rf', 'foo/*', 'out/');
```

The code for `cp` looks at the first argument, and realizes this is a list, so expands it.  For each item, it uses ‘lstat()’ to determine the file type – and if the file is a soft link, what the actual target type of the file is.  So for my case, I have a folder under 'foo' called ‘bar’, which is soft linked to a target 'bar' dir, so in this case shell.cp calls `lstat` which returns a directory.  This is then recursively copied.  Hence the 'bar' softlink ends up being copied as a full dir tree. 

Now, also under foo is a directory (called `baz`).  This has two child directories (`qux` and `quux`), which are both soft links to some other target folders.  So `baz` is a dir, so that gets recursively copied.  But the recursive copy here is now done in the `cpdirSyncRecursive` function.  This looks at the contents of the dir – and now uses `stat` instead of `lstat` to determine file type.  Here it sees `qux`, `quux` etc. and sees this is a softlink – and simply *copies* the softlink.  As `qux` refers to `../../qux` that’s what gets created in the target `out` folder – but that relative link is not a valid location in the new place.  But the link is created anyway.

So as a result, ‘bar’ is copied OK but `qux` and `quux` are not.

I can’t see how copying symlinks directly can ever work – unless the target is an absolute dir (not a relative one). In general though, I would prefer the prepare step to make full copies not simply copy the symlink.

**Comment by ariporad** [comment]
@crjobson: So, If I understand you correctly, we should be using `lstat` in `cpdirSyncRecursive`?

**Comment by ariporad** [comment]
Also, I'm going to change the issue title to make it more general.

**Comment by crjobson** [comment]
hi
Yes - i think you should use stat, and then copy the actual folder.  But you MIGHT want a way of telling cp to only copy the soft link as an option?  In my case, the final recursive copy was useless as the copied soft links were invalid in the new location.  So either do a full copy THROUGH the soft links, or do a SHADOW copy by preserving the soft links.  I think it depends on the way soft links are used: if they only point internally to the files int he copy set, no problems; but if the copy set has links to EXTERNAL files then the copy must be 'deep'

Make sense?
- chris

**Comment by nfischer** [comment]
I think this should be resolved by #232

**Comment by nfischer** [comment]
@crjobson is this still an issue for the latest version of shelljs? I think v0.7 resolves this, at least for unix.

**Comment by nfischer** [comment]
I'm going to close this issue, since I think this has been resolved. Feel free to re-open if this hasn't yet been resolved.

**Comment by crjobson** [comment]
This looks fine - thanks
