### ISSUE TITLE
0.4.0 broke our circle builds.

### ISSUE THREAD

**Issue by jeroenverfallie** [shelljs/shelljs#196]
[grunt-release](https://github.com/geddski/grunt-release) updated their node packages to the latest version last night, including this one, as of 0.4.0 this happens on our circleci build's `npm install`

Specifically, it can't delete this file: `shelljs/test/resources/ls/filename(with)[chars$]^that.must+be-escaped`

https://github.com/arturadib/shelljs/blob/master/test/resources/ls/filename(with)%5Bchars%24%5D%5Ethat.must%2Bbe-escaped

Oddly, this file has been there for 3 years, so I can't explain what's going on.

```
npm ERR! argv "node" "/home/ubuntu/nvm/v0.10.26/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v2.7.1
npm ERR! path .../grunt-release/node_modules/shelljs/test/resources/ls
npm ERR! code ENOTEMPTY
npm ERR! errno 53

npm ERR! ENOTEMPTY, rmdir '.../grunt-release/node_modules/shelljs/test/resources/ls'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '.../grunt-release/node_modules/shelljs/test/resources/ls'
npm ERR! error rolling back  { [Error: ENOTEMPTY, rmdir '.../grunt-release/node_modules/shelljs/test/resources/ls']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '.../grunt-release/node_modules/shelljs/test/resources/ls' }
```

**Comment by jeroenverfallie** [comment]
Update:

It's very likely that our circle setup has always fetched the module from its cache, and never had to update the module, thus, never had to delete it. 
Because the version is updated now, it's failing for the first time.

I can't confirm this though, but circle's npm install can't get rid of that one file, that's for sure.

**Comment by ariporad** [comment]
@jeroenverfallie: Does this still happen?

**Comment by nfischer** [comment]
I vote to close, since I don't think this is an issue with ShellJS. I suspect that your circle setup is not properly escaping the filename, and has trouble deleting it. And, as you know, the whole purpose of the file name is that it must be escaped (it's a resource for a test).

I had no trouble deleting the file myself. I set it up in an empty project with these commands:

```
$ npm -v # This is my npm version, I didn't bother checking with an older version
3.5.2
$ npm install -D shelljs
$ ls node_modules/ # check that's it's actually there
shelljs
$ npm uninstall shelljs # remove the files (no errors)
$ ls node_modules/ # check that it was successfully removed
```

I could also delete it with a simple `rm -r`, which is available on any unix machine. So hopefully one of those two is available for you.

**Comment by ariporad** [comment]
@jeroenverfallie : I'm going to close this, see above for some tips. Feel free to reopen.
