### ISSUE TITLE
Problems with exec (sync) on 0.12/io.js

### ISSUE THREAD

**Issue by dominykas** [shelljs/shelljs#197]
When the process being `exec`'ed errors out and outputs a lot of text, `shelljs` errors out on node 0.12/io.js (i.e. when support for actual `execSync` is present) on Travis (I'm not able to reproduce this on my Mac).

See this gist: https://gist.github.com/dominykas/f67e139a93fffdeb4c11

See `output-mac.txt` for the expected case (i.e. `git` command errors out, dumps quite some text) and see `output-travis.txt` for the error ([Travis build](https://travis-ci.org/dominykas/grunt-checkbranch/builds/56601651#L512) from [source](https://github.com/dominykas/grunt-checkbranch/tree/shelljs-failures-on-travis/tmp-shelljs))

**Comment by dominykas** [comment]
Updated the top post with a reduced test case - it seems that if there's an error, the output stream is getting closed too soon on nodes with support for `execSync`.

**Comment by ariporad** [comment]
@dominykas: Sorry this issue is so old! Would you mind re-doing this with the latest version of shelljs and letting me know if it is still broken? Thanks!

**Comment by dominykas** [comment]
I created this repo: https://github.com/dominykas/shelljs-issue-197

With results here: 
* 0.5.0: https://travis-ci.org/dominykas/shelljs-issue-197/builds/104491360 (fails, intermittent)
* 0.5.3: https://travis-ci.org/dominykas/shelljs-issue-197/builds/104491612 (seem to always pass)

So I guess it's fine, as long as you know what you fixed? :)

**Comment by nfischer** [comment]
Perhaps the issue was related to #206 (which was fixed by #214)? Both @ariporad and I came on after v0.5.3, so I'm not as familiar with the issues back then. Reading your error messages however, it looks like it's related. Closing for now, but please reopen if the issue ever returns.
