### ISSUE TITLE
Cross platform way to handle spaces in filenames

### ISSUE THREAD

**Issue by garytaylor** [shelljs/shelljs#201]
In windows, if we have a path such as C:\Program Files\foo\bar.exe and we use this string to pass to shelljs.exec(), it fails as C:\Program is not an executable.  On linux, it does a similar thing.

I have written code to work around this in my app, so if it is running in windows, it adds quotes around the path - or if we are on linux, max osx etc.. then we search for spaces and replace with '\ ', but I am going to have to do this everywhere.

Can this conversion be done within shelljs ?

Cheers

Gary

**Comment by tracker1** [comment]
You should be able to consistently escape cross platform with double-quotes ("some string"), which should be a singular item in your arguments list.  In general the windows way will work cross platform, also, most windows applications/shells/programs support forward slashes as path separators, in case you are dealing with similar issues for relative paths.

**Comment by ariporad** [comment]
@garytaylor: I'm going to close this, as the solution is just to double quote it. Feel free to reopen if needed.

Thanks @tracker1!
