### ISSUE TITLE
CLI Version

### ISSUE THREAD

**Issue by tobiastom** [shelljs/shelljs#202]
It might be nice to add a CLI version of the commands. This would allow people to use the commands directly inside the `package.json`.

For example:

```
   …
    "scripts": {
        "copy": "shelljs cp source/* desk"
    }
    …
```

This would make the cp task available which then could be used in every operating system, no matter if it is included or not. 

Right now I would need to add a separate tool for each job (for example [cpy](https://www.npmjs.com/package/cpy)).

**Comment by seangenabe** [comment]
+1 I kinda need this too. Currently I'm depending on cp (assuming msysgit is installed). I'm planning on making my own module, but this one seems a better place for it to be in.

**Comment by anselmh** [comment]
That would indeed be awesome. Any plans of doing that, @arturadib?

**Comment by arturadib** [comment]
No plans, could either be a separate package or if someone wants to take a stab at it and send a PR I'm happy to take a look, thanks!

**Comment by codemakerlive** [comment]
There's this module (which is currently on shelljs 0.2.6): https://github.com/nzakas/shelljs-nodecli. I didn't author it but if you could contact Nicholas perhaps the 2 projects could be merged.

**Comment by dandv** [comment]
That would be *so* awesome for [using npm as a build tool](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool) instead of grunt, gulp etc.

**Comment by keithamus** [comment]
It'd be great to see shelljs have a set of binaries matching all of the available commands - not just for windows compatibility, but for better compatibility between Linuxes and BSDs

**Comment by nickdima** [comment]
This is pretty trivial to implement, but not sure how to keep compatibility with the current behaviour of the `shjs` CLI. I'm talking about `shjs script_name` vs `shjs command_name`.
Maybe we could have it as a separate CLI script? It would need to have a short name also.
Or make a breaking change to the way it currently works?

**Comment by anselmh** [comment]
Hm, that would depend on what you want to do. If you don’t care about the old style, make it a new major version and breaking change. If you do care about it, I think a separate module would do the trick.

**Comment by keithamus** [comment]
@nickdima for every command you could create a simple binary wrapper, for example:

```js
// File: bin/cp
#!/usr/bin/env node
require('shelljs/global');
cp.apply(null, process.argv.slice(2));
```

```js
// File: bin/mkdir
#!/usr/bin/env node
require('shelljs/global');
mkdir.apply(null, process.argv.slice(2));
```

And so on. This way when we install shelljs, we can call `./node_modules/.bin/cp` which will be a version of `cp` which is cross-compatible.

**Comment by nickdima** [comment]
@keithamus hmm not a big fan of this... harder to maintain and harder to figure out when looking at the calls if it's the "real" command or the shelljs one. Plus with all those CLI scripts you could run into problems with other packages that might use the same name for their script.
I would prefer doing this:

`shjs rm -rf some_dir`

(maybe we can come up with a 2 letter name instead of `shjs`)

What do you think?

**Comment by keithamus** [comment]
Those files could easily be prefixed, to help differentiate them, so instead of `bin/cp` you could have `bin/shjs-cp`, etc.

**Comment by nickdima** [comment]
What's the benefit over having a single cli script?

Something along these lines:

```javascript
#!/usr/bin/env node
var shell = require('shelljs');

if (process.argv.length < 3) {
  console.log('ShellJS: missing argument (command name)');
  console.log();
  process.exit(1);
}

var command = process.argv[2];
var args = process.argv.slice(3);

var res = shell[command].apply(null, args);
if (res) console.log(res);
if (shell.error()) process.exit(1);

```

**Comment by nickdima** [comment]
Maybe we can call it `shl` or something like this and keep it along side the existent cli without making breaking changes.

**Comment by ariporad** [comment]
+1.

I'm going to mark this as low priority, but if anyone wants to send a PR, that would rock!

**Comment by levithomason** [comment]
I need this for another project, PR coming up.

**Comment by levithomason** [comment]
Ha, well.  I've found [shx](https://github.com/shelljs/shx).  Appears I've come to the races late.  Will see if our approaches have anything worth combining.

**Comment by nfischer** [comment]
Closing this, since our project [shelljs/shx](https://github.com/shelljs/shx) is designed to solve this.
