### ISSUE TITLE
Where is standard error going to?

### ISSUE THREAD

**Issue by n2liquid** [shelljs/shelljs#209]
If I run:

    console.log(sh.exec('echo WHOA THERE, AN ERROR CONDITION... 1>&2'));
    console.log(sh.error());

I get:

    WHOA THERE, AN ERROR CONDITION...
    { code: 0, output: '' }
    null

So how do I get messages from standard error in JavaScript?

**Comment by nfischer** [comment]
I think there might be a few problems going on here that might need updating. I get very different behavior depending on which commands I run:

```Bash
$ cat test.js
require('shelljs/global');
exec('echo hello world >&2');

$ shjs test.js >/dev/null # no stdout

$ shjs test.js 2>/dev/null # no stderr
hello world

$ node test.js >/dev/null # no stdout, using node
hello world

$ node test.js 2>/dev/null # no stderr, using node
```

This suggests that something is at least broken in the `shjs` script if not somewhere else as well. I suspect that this is related, and points toward a bug related to the `exec()` function (`shjs` is essentially a wrapper for a call to `exec('node ' + script_name + args);` (see [here](https://github.com/shelljs/shelljs/blob/master/bin/shjs#L50)).

I suspect it should just be modified to support capturing a process's stderr in addition to its stdout, and have both of these returned alongside the return code.

**Comment by nfischer** [comment]
This was bugging me, so I added this to #268. @n2liquid does this help you achieve what you wanted?

**Comment by nfischer** [comment]
Closing this, since #268 was merged. If this doesn't work as expected, please reopen this issue and let us know.
