### ISSUE TITLE
`cp` does not overwrite files by default

### ISSUE THREAD

**Issue by lvanengelen** [shelljs/shelljs#210]
In POSIX `cp` would just overwrite a file by default, without requiring the `-f` option.  This quite surprised me.  Was this done to make the `cp` behaviour a bit saver? In that case, would it be possible to mention this in the docs?

**Comment by nfischer** [comment]
I agree, this is something that probably should be documented. I think it would be even better to add the `-n` option and make `-f` the default (and simply keep it there for legacy reasons).

**Comment by nfischer** [comment]
This is now fixed in ShellJS v0.6. Thanks for reporting this, @lvanengelen :+1:
