### ISSUE TITLE
shelljs creates a file called 'string' with content 'testtest' when loaded by grunt

### ISSUE THREAD

**Issue by vincentcr** [shelljs/shelljs#212]
see this comment: https://github.com/jprichardson/string.js/issues/127#issuecomment-108023794

I have shelljs loaded because it's a dependency of grunt-contrib-jshint, and I see the same behavior.

**Comment by petebacondarwin** [comment]
Yes, this is annoying. How about we go with the hard-coded list of string methods instead?

**Comment by ariporad** [comment]
This doesn't really seem to be a problem with shelljs, although I agree that modifying `String.prototype` might not be the smartest, neither is calling every method.

I'm going to close this, but feel free to re-open if needed.

**Comment by nfischer** [comment]
This has actually been resolved by #360. Thanks for reporting this!
