### ISSUE TITLE
How about handling of asynchronous targets in make mode?

### ISSUE THREAD

**Issue by FlorianLoch** [shelljs/shelljs#213]
I would really like to see a feature for enabling me to have multiple targets with asynchronous code that get executed synchronously - like e. g. done in ```mocha```.

http://mochajs.org/#asynchronous-code

One would only have to define the order in which the targets are processed. I guess in order of appearance would be fine.

I could implement the functionality if there would be acceptance for it.

**Comment by FlorianLoch** [comment]
Any comments on this?

**Comment by ariporad** [comment]
I haven't really played with the makefile stuff much, @nfischer, toughts?

**Comment by nfischer** [comment]
I haven't used the makefiles much either. I'll try looking into this over the next couple days.

**Comment by nfischer** [comment]
@FlorianLoch we're currently discussion deprecating `make` in #340. If you're still using this feature, could you give some input on that thread?

**Comment by nfischer** [comment]
I'm tentatively adding the "won't fix" label, since we're thinking of deprecating the `make` command. Please ping this thread if anyone is still interested in this feature, and we'll gladly revisit this.

**Comment by nfischer** [comment]
I'll close this issue for now. Please ping this thread or reopen if this is still a concern.
