### ISSUE TITLE
Use semantic versioning and bump to 1.0.0

### ISSUE THREAD

**Issue by TimothyGu** [shelljs/shelljs#215]
The ShellJS API is pretty stable by now, so I think it is time for us to mark the version as 1.0.0. This would simplify dependency management as users would just know if a version is backwards-compatible or not.

**Comment by ariporad** [comment]
@TimothyGu: I don't think we're quite ready for 1.0 yet, see #272.

**Comment by TimothyGu** [comment]
:+1:
