### ISSUE TITLE
Cannot run shell.exec('heroku config:push') -- just hangs 

### ISSUE THREAD

**Issue by kingscott** [shelljs/shelljs#218]
Using shelljs to automate some bash commands in my gulpfile and for some reason shelljs won't run:  `heroku config:push`. So far it has been able to run every other command, and I can run this heroku command after with no errors; just a bit unsure why ShellJS is hanging on it. 

It is a plugin from heroku, so this could be the root of the issue.

Thanks!

**Comment by kingscott** [comment]
I was doing this locally.

**Comment by kingscott** [comment]
I can definitely give it a try. What does the run do that it doesn't do otherwise?

**Comment by fcpauldiaz** [comment]
Well, I use it to run local commands on the heroku cloud. Here is a list of the heroku commands. https://devcenter.heroku.com/articles/using-the-cli

**Comment by nfischer** [comment]
@kingscott has this been resolved? Have you tried using the new version, `v0.6.0`?

**Comment by kingscott** [comment]
To be honest, haven't been running that setup since late September. Adding `run` seemed to work and  just forgot to respond. Sorry.

**Comment by nfischer** [comment]
Sounds good! If this becomes an issue again, please feel free to re-open
