### ISSUE TITLE
Doesn't work inside Electron

### ISSUE THREAD

**Issue by sdegutis** [shelljs/shelljs#220]
No idea why.

**Comment by nfischer** [comment]
Possibly the same as #255?

**Comment by ariporad** [comment]
@sdegutis: Does #274 fix this?

**Comment by sdegutis** [comment]
I don't know, sorry, I don't use shelljs or electron anymore.

**Comment by joselevelsup** [comment]
So far I'm getting a Illegal Invocation everytime I use 
````javascript
var sh = require('shelljs');
sh.echo('Hello World');
````
inside the renderer index.js

**Comment by nfischer** [comment]
@joselevelsup is that using the latest version of master (we merged #274 yesterday)? What does the following code do for you? This would isolate if it's more than just an issue with `echo`.

```Javascript
var sh = require('shelljs');
console.log(sh.pwd());
```

**Comment by joselevelsup** [comment]
Turns out I was using it wrong. I had to use it in the Main process of Electron not the Render Process. Shelljs works fine!

**Comment by nfischer** [comment]
Awesome to hear! I'll close this issue for now. Please reopen if there are any concerns.

**Comment by jeremyrajan** [comment]
Hi,

I tried to use it renderer and sh.pwd seems fine. But for some reason, when I package the app and then pwd still works but `which` command i not working. 

Any idea why? 

Thank you!
