### ISSUE TITLE
Consider creating a GitHub Organization with more maintainers

### ISSUE THREAD

**Issue by mtscout6** [shelljs/shelljs#223]
@arturadib I understand the pressures you can encounter when an OSS library becomes more than you can bare on your own. May I suggest that this repo get transferred to a GitHub Organization where you can assign a team to help you maintain it? By the shear number of stars and pending pull requests it's clear that the work you've done is really appreciated. This is something I did with the react-bootstrap project earlier this year and now that project is thriving well beyond my means to keep up with it. I added some documentation on [becoming a maintainer](https://github.com/react-bootstrap/react-bootstrap/blob/master/MAINTAINING.md#becoming-a-maintainer) on that repo. It sounds crazy at first, and I wouldn't say just add anyone that chimes in, but many hands are better than one.

**Comment by arturadib** [comment]
yes! but even that takes time, and I'd have to find folks who can maintain the project with the original philosophy in mind (no bloat, as close to *nix as possible, etc). I'll try to find some time to look into this soon

**Comment by dandv** [comment]
:+1:

**Comment by arturadib** [comment]
this has been done. I'll work on finding more maintainers

**Comment by mtscout6** [comment]
Fantastic!

**Comment by mtscout6** [comment]
For what it's worth I'd be interested in joining, I have recently taken up a DevOps team lead for my employer. We are rebuilding a lot of our Ruby Infrastructure with Node and this project will continue to get more and more useful for us. I'll be honest that I won't be up to much for the next month or so, but I can start to help with issue reviews on occasion.
