### ISSUE TITLE
ls globbing does not behave like shell, consider using glob.sync

### ISSUE THREAD

**Issue by boutell** [shelljs/shelljs#225]
ls() globbing does not behave like the shell. For instance, this doesn't work:

/opt/stagecoach/apps/*/current/public

The * does not match path components in the middle of a path.

The same thing works, however, if I use the glob module's "glob.sync" method instead.

I suggest using glob.sync rather than a homegrown implementation of ls.

This would impact the options currently supported by ls however.

**Comment by nfischer** [comment]
This would be a very useful addition

**Comment by ariporad** [comment]
I'll implement this.

**Comment by boutell** [comment]
A+

**Comment by ariporad** [comment]
Fixed in #275.
