### ISSUE TITLE
Not all tests pass when umask is not set to 0022

### ISSUE THREAD

**Issue by rezonant** [shelljs/shelljs#226]
For me, I use 0077 (thus resulting in 600 (rw-------) on touch), and tests within tests/cp.js and tests/chmod.js fail. Changing my umask to 0022 and recloning the repository results in all tests passed.

liam@aether:shelljs-test :) umask 0077
liam@aether:shelljs-test :) git clone https://github.com/arturadib/shelljs.git
liam@aether:shelljs-test :) cd shelljs
liam@aether:shelljs :) npm install
liam@aether:shelljs :) npm test

> shelljs@0.5.3 test shelljs
> node scripts/run-tests

All JSHint tests passed

Running test: cat.js
Running test: cd.js
Running test: chmod.js

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: 320 == 365
    at Object.<anonymous> (shelljs/test/chmod.js:63:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
*** TEST FAILED! (missing exit code "123")

Running test: common.js
Running test: config.js
Running test: cp.js

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: 0 == 1
    at Object.<anonymous> (shelljs/test/cp.js:142:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
*** TEST FAILED! (missing exit code "123")

Running test: dirs.js
Running test: echo.js
Running test: env.js
Running test: exec.js
Running test: find.js
Running test: grep.js
Running test: ln.js
Running test: ls.js
Running test: make.js
Running test: mkdir.js
Running test: mv.js
Running test: popd.js
Running test: pushd.js
Running test: pwd.js
Running test: rm.js
Running test: sed.js
Running test: tempdir.js
Running test: test.js
Running test: to.js
Running test: toEnd.js
Running test: which.js

*******************************************************
WARNING: Some tests did not pass!
*******************************************************
npm ERR! Test failed.  See above for more details.
liam@aether:shelljs :(

**Comment by rezonant** [comment]
Furthermore, it appears that umask inappropriately influences symbolic chmods, ie the following operation results in a no-permissions (000) state:

$ umask 0077
$ touch file
$ node
> var shelljs = require('shelljs');
> shelljs.chmod('a-rwx,u+rw', 'file');
$ ls -la file
---------- 1 liam liam 0 Aug 26 13:36 file

**Comment by nfischer** [comment]
@rezonant I think we currently only support the standard umask. We'd love a PR that fixes this, though! (or at least makes it not break tests)

**Comment by nfischer** [comment]
@rezonant I'll accept a PR that fixes this, but I'm closing this issue because this isn't a priority. I think the workarounds are suitable:

 - Contributors should set their umask to the default value while testing ShellJS, or
 - Contributors can run tests on Travis and Appveyor, which have the default configurations
