### ISSUE TITLE
sed() should accept multiple file arguments

### ISSUE THREAD

**Issue by cvrebert** [shelljs/shelljs#231]
[Unix sed accepts multiple files](http://pubs.opengroup.org/onlinepubs/7908799/xcu/sed.html). Is there a reason ShellJS's sed doesn't, or has just nobody gotten around to it yet?

**Comment by nfischer** [comment]
I think this just hasn't been implemented yet. This sounds like it would make sense to have.

Right now `sed()` seems to return the modified text. I think, for the sake of backwards compatibility, if a single file is passed in, this should stay the behavior.

If multiple the files `foo.txt` and `bar.txt` are passed in that order, then I think the output should be an array along the lines of `[ modified foo.txt, modified bar.txt ]`.

Would that be sufficient for your uses?

**Comment by cvrebert** [comment]
Yes; I have no need for the return value.

**Comment by nfischer** [comment]
Sounds like a useful thing to me. I'm going to look into how this might be supported and see if I can make a PR. For now, though, your best bet is probably to use multiple `sed()` commands in a `forEach` loop. See the snippet taken from the README:

> ```Javascript
> ls('*.js').forEach(function(file) {
>   sed('-i', 'BUILD_VERSION', 'v0.1.2', file);
>   sed('-i', /.*REMOVE_THIS_LINE.*\n/, '', file);
>   sed('-i', /.*REPLACE_LINE_WITH_MACRO.*\n/, cat('macro.js'), file);
> });
> ```

**Comment by nfischer** [comment]
@cvrebert this should be resolved in #314. It'll work similarly to how `grep()` currently works. All output in one string, and each file gets replaced individually if the `-i` flag is passed.
