### ISSUE TITLE
Arguments

### ISSUE THREAD

**Issue by akashnimare** [shelljs/shelljs#237]
How do I give argument to shelljs.
like
shell.exec("ls -ssh" + process.argv[2]);
Something like this.

**Comment by frdmn** [comment]
Did you try to add another whitespace to separate the argument form the options (`-ssh`)?

```javascript
sh.exec("ls -al " + process.argv[2]);
```

**Comment by akashnimare** [comment]
Yeah. It's working. Is there any way I can modify the stdout?
The output of this command is -
filesize filename

What if I want only filesize?

**Comment by frdmn** [comment]
This is actually not relevant to the project, but what's the output of your command if you run it with an argument?

**Comment by akashnimare** [comment]
@frdmn Here is the output
<img src="https://github.com/akashnimare/filesize/raw/master/aa.png"/>
I only want the size in stdout.
https://github.com/akashnimare/filesize

**Comment by frdmn** [comment]
@akashnimare Something like this?

```javascript
var output = sh.exec('ls -shh ' + process.argv[2] + '', {silent:true}).output;

console.log(output.split(' ')[0]);
//=> 852M
```

Also, you should close this issue since your actual problem is solved :)

**Comment by akashnimare** [comment]
Thanks man.

**Comment by frdmn** [comment]
@akashnimare You're welcome :+1:
