### ISSUE TITLE
"Which" command not working properly on Windows Platform.

### ISSUE THREAD

**Issue by TingluoHuang** [shelljs/shelljs#238]
Install node.js on a windows box, try use shell.which to find the location of NPM.
Shell.which('npm') return "C:\Program Files\nodejs\npm" instead of the correct "C:\Program Files\nodejs\npm.cmd"
The bug is at which.js line 49.

**Comment by nfischer** [comment]
I believe another related issue is that the priority of `.bat`, `.cmd`, and `.exe` is currently incorrect. Seem [my comment](https://github.com/shelljs/shelljs/pull/239#issuecomment-169908832) on the PR for details.

**Comment by nfischer** [comment]
Closing since this is fixed in #239
