### ISSUE TITLE
/usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by guillaumeinnov24** [shelljs/shelljs#243]
I'm new with node. I've installed `npm` and then `npm install -g shelljs`.
Then I created a `.js` test file with
`var shell = require('shelljs');
shell.echo('hello world');`
inside.
But whatever I try, when I run `shjs test.js` 
it always comes with 
`/usr/bin/env: node: No such file or directory`
even with an absolute path.
What do I miss?

**Comment by TimothyGu** [comment]
Did you install nodejs with Ubuntu or Debian's apt-get?

**Comment by guillaumeinnov24** [comment]
My bad I missed this discussion https://github.com/nodejs/node-v0.x-archive/issues/3911
Indeed it has nothing to do with shelljs, sorry boys :/
