### ISSUE TITLE
Dir glob breaks when in the middle of path

### ISSUE THREAD

**Issue by nickdima** [shelljs/shelljs#245]
If you have a path like `some_dir/another_dir/**/*.ext` when you run `common.expand` on it the resulted filepaths will be relative to `another_dir` instead of containing the full path.

**Comment by nickdima** [comment]
Maybe [here](https://github.com/shelljs/shelljs/blob/master/src/common.js#L106) it should be:

```javascript
expanded.push(root + file);
```

**Comment by ddbruce** [comment]
I had this issue too (see [this](https://github.com/ddbruce/thermopi/blob/master/app.js)). Fixed it by modifying common.js as @nickdima said.

**Comment by nfischer** [comment]
Sounds like this could also be related to #225, which recommends using the glob module.

**Comment by nfischer** [comment]
@nickdima @ddbruce Does #275 fix this issue as well?

**Comment by nfischer** [comment]
@nickdima @ddbruce I think this is fixed now by #359. Please reopen if this is still an issue.
