### ISSUE TITLE
By default shelljs runs command in root 

### ISSUE THREAD

**Issue by Lakshman-LD** [shelljs/shelljs#246]
Usually working with the Linux systems, working within specific user is more probable. So, shelljs can execute commands on particular user instead of executing in the root. 

I agree that user can be changed using **su** but **su**asks for a password. So non-interactive scripts must be used to change user. So many complications. 

So it is better that shelljs executes command on a user from where it was called else provide some function to change user provided the Password.

**Comment by nfischer** [comment]
Could you provide a sample shelljs script and describe the behavior you're seeing?

I tried this in my Linux command line:

```Bash
$ sudo touch rootfile
$ touch rootfile # My normal user can't touch the file, as expected
touch: cannot touch ‘rootfile’: Permission denied
$ cat delete.js
require('shelljs/global');
rm('rootfile');
$ shjs delete.js # delete.js can't delete the file, since root owns it
rm: permission denied: rootfile
$ ls rootfile # it's still there
rootfile
$ sudo shjs delete.js # this outputs nothing and successfully deletes the file
$ ls rootfile # It's deleted, as expected
ls: cannot access rootfile: No such file or directory
```

Everything here makes sense to me, and `shjs` only runs as root when I tell it to. Does this agree with what you're seeing?

**Comment by Lakshman-LD** [comment]
Hey, thanks for the reply.
I was using Amazon Ec2, I think that might be the reason. There are two users in Ec2 namely the root and ubuntu. By default it runs the command in root, even though when it was executed from ubuntu. 
Its been a long time now, so Found **exec** and **spawn** served my purpose.
