### ISSUE TITLE
exec enhanced

### ISSUE THREAD

**Issue by cancerberoSgx** [shelljs/shelljs#251]
Hello, good project!

I'm having trouble with .exec/.execAsync, particularly when invoking command line tools that uses terminal colors or terminal advanced features like cli-spinner, etc. 

By default, shelljs will create a new buffer for child processes and executing command line tools that use for example cli-spinner will just break. 

PLEASE provide a .exe API so I can control this, for example like the following one. :

	var child_process = require('child_process');
	var exec = function(cmd, args, callback)
	{
		var child = child_process.spawn(cmd, args, {
			stdio: [
				0, // use parents stdin for child
				1, // use parent's stdout stream - IMPORTANT if we dont do this things like the spinner will break the automation.
				2  // fs.openSync('err.out', 'w') // direct child's stderr to a file
			]
		});
		child.on('close', function()
		{
			callback.apply(null, arguments); 
		});
		return child;
	};

**Comment by ariporad** [comment]
@cancerberoSgx: Since there seems to be some discussion of this in #242, I'm going to close this so we can continue there.
