### ISSUE TITLE
How to exit on first error

### ISSUE THREAD

**Issue by sheerun** [shelljs/shelljs#253]
Hey,

What is the equivalent of `set -e` in shelljs?

**Comment by nfischer** [comment]
Not sure if this exists yet, although it should be possible to implement. This would involve (among other things) writing a `set()` command, however. Which [options](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html) in addition to `-e` do you think would be most useful to implement?

**Comment by nfischer** [comment]
Looks like I spoke too soon. Try `config.fatal`:

```Javascript
require('shelljs/global');
config.fatal = true;
rm('-f', 'fake_file');
ls('fake_file');
ls('fake_file'); // This is never executed
```

**Comment by nfischer** [comment]
Closing this, since `config.fatal` should be good enough for now. We can reopen this if there is more justification for a full-fledged `set` command that supports more than just the `-e`/`+e` option.
