### ISSUE TITLE
Error shown when triggering a sigint during shelljs.exec if process.on sigint is defined

### ISSUE THREAD

**Issue by pajtai** [shelljs/shelljs#254]
Execute this file to reproduce

```
#!/usr/bin/env node
'use strict';

process.on('SIGINT', function() { console.log('done'); });
var exec = require('shelljs').exec('sleep 30');
```

Now press ctr-c before the sleep is done and you get an error like the following:

> ^Cshell.js: internal error
> Error: ENOENT: no such file or directory, open '/var/folders/s1/hl12yyyd0n3djffckxzc8fdm0000gp/T/shelljs_639bf41add87c30b7ccb'
>    at Error (native)
>    at Object.fs.openSync (fs.js:584:18)
>    at Object.fs.readFileSync (fs.js:431:33)
>    at execSync

**Comment by bompi88** [comment]
+1

**Comment by nfischer** [comment]
Confirmed. I think this has to do with the way we force `exec` to be synchronous (by writing to temp files)

**Comment by cqgao** [comment]
+1

**Comment by nfischer** [comment]
I'm going to merge this into #495. The new design won't use tempfiles by default.

**Comment by HamidOsouli** [comment]
+1
