### ISSUE TITLE
cp and rename directory with -r doesn't match unix behavior

### ISSUE THREAD

**Issue by jedwards1211** [shelljs/shelljs#256]
As shown below, if I do `cp -r a b` with shelljs where `a` is a directory and `b` doesn't exist, shelljs creates `b/a` directories and the copies the contents of `a` into `b/a`.  Instead, like in a unix shell, it should create `b` directory and copy the contents of `a` into `b`.

```
> mkdir a
> touch a/file.txt
> node
> require('shelljs/global')
{}
> cp('-r', 'a', 'b');
undefined
> 
(To exit, press ^C again or type .exit)
> 
> ls b/
a
> rm -rvf b
b/a/file.txt
b/a
b/
> cp -rvp a b
a -> b
a/file.txt -> b/file.txt
```

**Comment by aarjithn** [comment]
Possibly same as #101? Me too would like to get this fixed.

**Comment by nfischer** [comment]
To get the behavior you want, you must specify a trailing '/'. Change your command to:

```Javascript
cp('-r', 'a/', 'b');
```
Please see #15.

I agree that this differs from the Linux behavior. How does this compare with the BSD behavior (such as on OS X)? I know that BSD utilities behave differently if a directory is has a trailing '/'. See [this page](http://hints.macworld.com/article.php?story=20051112100007372) for more details. This example is slightly different, but I believe the behavior differs in this case as well. If someone could confirm on OS X, that would be helpful.

I don't believe POSIX specifies which behavior is correct, but please correct me if I'm wrong.

**Comment by jedwards1211** [comment]
@nfischer sorry, I shouldn't have said "in a unix shell", I actually ran my original example on OSX.

**Comment by nfischer** [comment]
Oh, ok. I'm on Linux, so I can confirm that Linux behaves the way you describe. If OS X also behaves that way, then it sounds like this is **not** POSIX behavior, and should indeed be fixed.

For now though, does the trailing '/' workaround achieve what you need, @jedwards1211?

**Comment by jedwards1211** [comment]
@nfischer it does, although of course I had just used `a/*` instead

**Comment by nfischer** [comment]
Would any of you be able to test out #271 and make sure it works as expected? I've tested it, and it seems to resemble the Linux behavior fairly closely (will test again to be completely sure). It'd be great if you guys could confirm as well.
