### ISSUE TITLE
Error in listEl.search when cp using array

### ISSUE THREAD

**Issue by Alphapage** [shelljs/shelljs#259]
Hello,

I get listEl.search is not a function when using this command:
```
.cp("rf",[folderPath+"/**/*.js",folderPath+"/**/*.json"],destPath)
```
but without [] all is working:
```
.cp("rf",folderPath+"/**/*.js",folderPath+"/**/*.json",destPath)
```

And one question:
How to escape one path ? , for example:
```
"!"+folderPath+"/escapedfolder"
```

**Comment by nfischer** [comment]
> ```
> .cp("rf",[folderPath+"/**/*.js",folderPath+"/**/*.json"],destPath)
> ```

I think you want the first argument to be `"-rf"`, not `"rf"`. It needs a hyphen in front. And you shouldn't start it with a `.cp`, just `cp` (no dot).

Also, I'm not sure if `**` globbing is well supported yet, so this may be a bug. I wasn't able to get either command to run.

> And one question:
> How to escape one path ? , for example:

I'm not completely sure what you mean by "escape one path." Could you please give an example shell script in bash that does what you're describing?

**Comment by ariporad** [comment]
I'm going to close this since it appears to have been solved. Feel free to re-open if needed.
