### ISSUE TITLE
shell.js: internal error Error: UNKNOWN: unknown error

### ISSUE THREAD

**Issue by metallurgical** [shelljs/shelljs#265]
I'm trying to install ionic framework and cordova but the error came out after typing ionic command. No error while installation process.

![capture](https://cloud.githubusercontent.com/assets/6198891/12003978/40493528-aaeb-11e5-8ac0-ce951078fc24.PNG)

Development Environment
- Windows 7 32Bit

**Comment by nfischer** [comment]
@metallurgical sorry for the delay. Thanks for reporting this bug! What version of node are you using? Also, would you be able to point me at a URL for Ionic's source code?

Could you also verify if the folder `C:\Users\Batsu\AppData\Local\Temp` exists on your machine?

**Comment by SunilRumbaLama** [comment]
The problem still persists @nfischer and the date is 14th july 2016

**Comment by VinodKumar303** [comment]
![image](https://cloud.githubusercontent.com/assets/21238052/17962807/1b443f84-6ad0-11e6-84c7-310207bf36c2.png)

**Comment by VinodKumar303** [comment]
i am getting shell.js : internal error.,   please help me how to resolve this error.

Thanks in Advance

**Comment by maneeshbabu** [comment]
The same error shown me while I am working with project. Please help me how to resolve this error. 
Thanks in Advance

**Comment by jpca999** [comment]
+ 1

**Comment by nfischer** [comment]
Closing this, since we unfortunately don't have the bandwidth to support ionic/cordova. Same case as electron.

If anyone wants to dig into this and figure out the issue, I'll gladly look at a PR.
