### ISSUE TITLE
Add tests for the shjs utility

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#280]
It might be useful to add some tests for the `shjs` utility itself. This would include making sure it respects stdout/stderr and exit codes. This is less of a priority now, but would be more useful if #268 (stderr) and #252 (exit codes) are merged.

This would involve creating shelljs scripts and executing them with the `shjs` command, and making sure results are as expected. I don't think we need a large number of test cases, but we should have a few just to make sure we don't get regressions in the utility.

**Comment by ariporad** [comment]
+1

**Comment by ariporad** [comment]
I'll do this.

**Comment by ariporad** [comment]
Fixed in #304.
