### ISSUE TITLE
Switch `exec()` to use bash by default

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#281]
This should be possible via the `shell` option (see [the docs](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback)). I've written out some preliminary code for Linux, and it seems to work as expected. I'll fix Windows compatibility and send out a PR.

Edit: `bash` should be the new default on Linux, `cmd.exe` should remain the default on Windows.

**Comment by ainthek** [comment]
Please consider MINGW users on windows as well.

**Comment by ariporad** [comment]
@ainthek: MINGW?

**Comment by TimothyGu** [comment]
I believe @ainthek's point is that in a MinGW setup the default shell should be bash rather than cmd.

**Comment by ariporad** [comment]
Good point. @nfischer: I think that the shell should be `bash` if available, regardless of platform, with a fallback to something else.

**Comment by nfischer** [comment]
Ok, sounds good. I'll look up how to check for the existence of a shell and see if I find anything along those lines.

**Comment by TimothyGu** [comment]
@ariporad +1

**Comment by nfischer** [comment]
After looking into this a bit, I think only `cmd.exe` will be supported on Windows. Going off [the docs](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback), is says:

> `shell` String Shell to execute the command with (Default: '/bin/sh' on UNIX, 'cmd.exe' on Windows, The shell should understand the `-c` switch on UNIX or `/s /c` on Windows. On Windows, command line parsing should be compatible with `cmd.exe`.)

Bash, however, would not be compatible with `cmd.exe`. I have this implemented for Unix, however. I'll try setting it to default to `cmd.exe` if Node says the platform is Windows, otherwise try bash if it exists. I'll also add a feature for setting `shell` yourself. Then, if you system supports bash and shelljs doesn't detect that, feel free to open a PR.

**Comment by ariporad** [comment]
@nfischer: Idea: On windows, could exec run `cmd.exe`, but give it "bash -c \"<actual command>\""?

**Comment by sedwards2009** [comment]
Shouldn't it actually be using /bin/sh instead of bash? Not every system has bash but all of the unix-like ones should have a POSIX compliant shell at /bin/sh. It other words, it is more portable.

**Comment by nfischer** [comment]
@sedwards2009 This tries bash, if it doesn't exist, falls back to sh. This should make it fairly safe.

@ariporad, I'd prefer not to do that. It's a good idea, but there can be weird bugs with escaping quotes, and things like that. If users *really* want that, they'll have the flexibility to do it themselves now. The point of exec is to run native commands that aren't part of shelljs, and that would prevent anyone from running native Windows commands

**Comment by sedwards2009** [comment]
@nfischer The problem with preferring bash over plain sh is that people can easily write bash-only code and not notice that it is incompatible with plain sh until someone else tries running it on a system which doesn't have bash.

I remember a number of years ago Ubuntu (or Debian??) changed the symlink at /sbin/sh from bash to dash. It exposed a bunch of bug as people had been using bash features in scripts which claimed to need just plain sh.

**Comment by TimothyGu** [comment]
> I remember a number of years ago Ubuntu (or Debian??) changed the symlink at /sbin/sh from bash to dash.

Debian, therefore Ubuntu. dash = Debian Almquist SHell: https://wiki.debian.org/DashAsBinSh

However, most people using `exec` probably wouldn't use these bash features, except for `<<<` (other common ones are `function` and `if [[` but those are unlikely to be used in `exec`).

**Comment by nfischer** [comment]
@TimothyGu `<<<` was the feature we had in mind. One user posted an issue regarding that, expecting it to work

@sedwards2009 Portability is a main goal for the project. `exec` however is inherently not portable. It's designed for external commands, such as `git`, `uname`, `ifconfig`, etc. Scripts that rely on `exec()` are almost never portable, and the user should know and accept that. I don't see a good reason to restrict people to the sh subset of commands when they have bash available, just like how I don't see a reason to restrict UNIX users to the extremely small subset of commands that are the same on Windows (echo, cd, and maybe a couple more).

With that said, `exec()` now accepts any options that the underlying node API accepts, including the shell option. So users can always get the flexibility to use bash syntax if desired, they just need to be aware of what's going on by default

**Comment by ariporad** [comment]
@nfischer: That just gave me an idea: What if we replaced `exec` with something closer to `spawn`?

**Comment by nfischer** [comment]
@ariporad looks like `spawn()` will not perform globbing, which sounds like it's closer to what's being asked for here.

I don't like replacing it, because I think globbing is an important feature to offer (and we get it for free, so why not?). That would be a major change of behavior, and glob support is a feature that's pretty nice.

I think the solution(s) in bash is(/are) something like this:

```Bash
# in an empty directory
$ touch a.txt # creates a normal file
$ touch b.txt # again, works as expected
$ touch *.txt # does not create a file, this just updates time stamps for the other two
$ touch '*.txt' # this creates a file named *.txt (solution #1)
$ for k in *.txt; do echo $k; done # no quotes around $k is insecure
a.txt
b.txt
a.txt b.txt *.txt
$ for k in *.txt; do echo "$k"; done # double quotes allow $k to work sensibly (solution #2)
a.txt
b.txt
*.txt
```

I think the best option would be to have a `shellEscape()` function. Then users can feel safe about the code they write:

```Javascript
> touch('a.txt');
> touch('b.txt');
> touch('*.txt'); // we can modify this to allow globbing, to work as above
> touch(shellEscape('*.txt')); // this creates a file named *.txt
> ls('*.txt').forEach(function (file) { echo(ls(file)); });
// this isn't ls()'s current behavior, but we could modify it to be consistent with unix ls
[ 'a.txt' ]
[ 'b.txt' ]
[ 'a.txt', 'b.txt' ]
> ls('*.txt').forEach(function (file) { echo(ls(shellEscape(file))); });

**Comment by sedwards2009** [comment]
@nfischer 
I really like that shelljs uses the familiar unix-style vocabulary, but sometimes you might have to deviate from it to get something better. For example, bash has some really atrocious and dangerous default behaviour which is best not copied directly but instead exposed in a better way.

**Comment by nfischer** [comment]
Closing this in favor of #348
