### ISSUE TITLE
Support echo-ing environment variables

### ISSUE THREAD

**Issue by freitagbr** [shelljs/shelljs#291]
`echo()` should be updated to support echo-ing environment variables. Currently, `echo('$TERM')` will simply echo `$TERM`. We should allow distinction between strings and variables. Maybe something like this:
```
echo(null, '$TERM'); // 'xterm-256color'
```
Environment variables are visible to Node through the `process.env` object, which contains the user environment.

**Comment by nfischer** [comment]
@freitagbr Would this suit your needs?

```Javascript
echo(env['TERM']);
echo(env.TERM); // alternate syntax for the same thing
```

See [the docs](https://github.com/shelljs/shelljs#envvar_name)

**Comment by freitagbr** [comment]
Yes. I should read more carefully.

**Comment by nfischer** [comment]
Closing this for now. Re-open if you think there's need for better syntax for this feature.

And I agree, the docs aren't quite as great as they could be. I think we should consider reformatting the docs a bit. Feel free to open a PR if you think you can clean up any of the command descriptions.
