### ISSUE TITLE
Some packages that may be helpful

### ISSUE THREAD

**Issue by isaacs** [shelljs/shelljs#3]
- https://github.com/isaacs/node-glob It's 100% js now, and has sync and async APIs for finding files.  Provides fancy-pants globs like Bash4 with extglob and globstar turned on (though these can be disabled).
- https://github.com/isaacs/node-touch Touches a file
- https://github.com/substack/node-mkdirp Battle tested efficient mkdir -p
- https://github.com/isaacs/node-which like which(1)
- https://github.com/isaacs/fstream Useful for piping between directories for `cp -R` style behavior or tar streams (no sync api, though, only streaming.)
- https://github.com/isaacs/node-tar For a tar command (no sync API, only streaming)
- https://github.com/isaacs/rimraf Battle-tested rm -rf
- https://github.com/isaacs/read like read(1)

**Comment by ariporad** [comment]
@isaacs: Hi! (Sorry there's been no response till now, we just got some new maintainers):

I know that in the past, @arturadib hasn't been huge on adding dependencies, but I'm not sure if we're sticking to that. I will make sure to bring it up at our meeting tomorrow.

Thanks so much!
