### ISSUE TITLE
`link -s` is broken for files on Windows

### ISSUE THREAD

**Issue by BYK** [shelljs/shelljs#301]
Currently we simply use `junction` as the linking method on Windows do avoid any linking permissions that Windows has (requires admin permissions to link a file). This though only works for directories so we need to check the source item type and use the proper link method accordingly.

**Comment by ariporad** [comment]
@nfischer: Do you have a windows VM to test a possible PR for this? (I have no windows access, so I wouldn't know if it worked).

**Comment by BYK** [comment]
@ariporad I do have Windows machine that I use as my main computer :) Also if you don't have time I can submit a PR too. I just didn't have time back when I created the issue.

**Comment by ariporad** [comment]
@BYK: Actually, that would be great, would you mind? You seem to know a heck of a lot more about Windows than I do.

**Comment by nfischer** [comment]
I have a Windows 7 machine I can try testing this out on, once the PR is submitted :+1:
