### ISSUE TITLE
Gen-docs is broken

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#309]
Oops! It turns out that #303 modified the behavior of `sed()` in a way that didn't play nicely with `scripts/generate-docs.js`. The docs script uses a regex `/## Command reference(.|\n)*/`, which was previously used to mean "replace everything from '## Command reference' until the very end of the file."

Unix `sed`, however, does not operate on multiple lines, so it only replaces the first line, leaving all the old docs concatenated onto the end of the new docs.

**Comment by ariporad** [comment]
Fixed.
