### ISSUE TITLE
Cross-platform way to add to PATH

### ISSUE THREAD

**Issue by seanmonstar** [shelljs/shelljs#32]
I'm sure part of this should be fixed in node core, but they're just sitting on the issue (joyent/node#3728).

PATH uses `:` on *nix, and `;` on Windows. It could either provide just the separator, or provide some sort of push method.

Example:
```js
shell.PATH.push('../node_modules/.bin');
// or
shell.env.PATH += shell.sep + '../node_modules/.bin';
```

**Comment by nfischer** [comment]
Closing this since it looks like `path.delimiter` should be sufficient (and was added to node after this issue was created). If this is still a concern, please feel free to re-open.
