### ISSUE TITLE
Feature request: Metadata with `ls`

### ISSUE THREAD

**Issue by gvn** [shelljs/shelljs#323]
Hi there. First off, I'm a big fan of this library!

Unless I'm missing something, there's no way to read the modification date of a file (among other things). I'm having to go back into node's `fs` module for that. It seems like this would be very useful. It strikes me that it could be added in an option for `ls`.

EG: `ls('-l', 'path')` might return an array of objects with file metadata such as permissions, owner, group, size, and modification date.

**Comment by nfischer** [comment]
Sounds good to me. I think I'll open a PR for ls -l later today, and it'll be based off this design

**Comment by gvn** [comment]
Awesome! I'm happy to give it a code review if you'd like. I could probably also write a PR soon-ish, but my guess is you'd be way faster at adding it. Just let me know! :smiley:

**Comment by nfischer** [comment]
@gvn I'll tag you in the PR once it's done :+1:

**Comment by nfischer** [comment]
@gvn I tagged you in the PR
