### ISSUE TITLE
Add documentup as a webhook

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#327]
We need to update http://documentup.com/shelljs/shelljs. It's all generated off the README, but we need to actually update the site itself with new docs

**Comment by ariporad** [comment]
@nfischer: I think I added a webhook so it gets done automatically.

I'm going to test it by removing @arturadib's twitter from the README.

**Comment by nfischer** [comment]
Looks like it worked! :+1: Let's add the twitter back in just in case Artur wants to have that as a line of contact though.

**Comment by ariporad** [comment]
Nope... Apparently I didn't.

But visiting http://documentup.com/shelljs/shelljs/__recompile works just as well. Maybe we can add that to travis? (When I get a minute later, I'll debug the webhook a little more).

**Comment by nfischer** [comment]
Ah, ok. As long as the stuff is recompiled. It'd be nice to have that as a webhook though, but only for builds that get merged, not all PRs (not sure if that's hard to set up)

**Comment by ariporad** [comment]
I don't think it should be.
I don't think we should have the twitter on there, as I doubt he wants it, 
and
regardless, it would be better if they used the issue tracker. (Mostly to
consolidate it, and because they way we can see it to impliment).

**Comment by ariporad** [comment]
Hmm... Maybe we do have it...

I'm going to test again.

**Comment by ariporad** [comment]
Hmm... It didn't work. I have no clue.

**Comment by ariporad** [comment]
It looks like this is a known issue: jeromegn/DocumentUp#98.

**Comment by nfischer** [comment]
Closing this, since I think the recompile URL (http://documentup.com/shelljs/shelljs/__recompile) would work well enough for our purposes.

**Comment by ariporad** [comment]
@nfischer: Wait... I have an evilish idea.

**Comment by ariporad** [comment]
Nope, that didn't work. Should I add it to travis?

**Comment by nfischer** [comment]
I think it's fine to leave as is. We can just manually recompile when necessary
