### ISSUE TITLE
rm -rf incorrect behaviour

### ISSUE THREAD

**Issue by stefk** [shelljs/shelljs#332]
`rm('-rf', target)` should never throw an exception when the target doesn't exist. It does, however, when it is *inside* a non-existent directory:

Expected:

```js
mkdir('./tmp');
rm('-rf', './tmp');
rm('-rf', './tmp'); // no error
rm('-rf', './tmp/*'); // no error
rm('-rf', './tmp/non/existent'); // no error
```

Actual:

```js
mkdir('./tmp');
rm('-rf', './tmp');
rm('-rf', './tmp'); // ok
rm('-rf', './tmp/*'); // rm: no such file or directory: ./tmp
rm('-rf', './tmp/non/existent'); // same
```

**Comment by ariporad** [comment]
Hmm... That would appear to be the case. I'll try to whip up a PR.

**Comment by nfischer** [comment]
@stefk Thanks for reporting this!

This is indeed a bug on ShellJS v0.6. However, this seems to have been fixed in the latest version of master.

I'll add some unit tests tonight, to prevent a regression from occurring in the future.
