### ISSUE TITLE
option not recognized

### ISSUE THREAD

**Issue by obihill** [shelljs/shelljs#334]
I'm trying a very simple example but I'm having issues:

```javascript
//my-js-file.js
require('shelljs/global');
ls('-l', '/');
```

and then I run `shjs my-js-file.js` on the command line. I get the following error: `ls: option not recognized: l`.

What am I doing wrong?

Note: Trying this using Node version 4.2.4 on an Ubuntu 14.04 server (DigitalOcean).

**Comment by nfischer** [comment]
Did you install via npm? ls -l is brand new (thanks for trying it out!) and as such has not yet been released on npm. Expect a new npm release (v0.6) by the end of this week :+1:

You can get this feature immediately by cloning our git repo instead

**Comment by obihill** [comment]
Thanks a lot. I'll make do with `.exec()` until then. Not in a hurry.

Cheers.

**Comment by nfischer** [comment]
My pleasure
