### ISSUE TITLE
Asking for feedback on the `make` command

### ISSUE THREAD

**Issue by ariporad** [shelljs/shelljs#340]
Hi Everyone!

Me and @nfischer (but mostly me), were wondering if you guys used `shelljs/make`, and/or if you'd be sad if it went away.

Thoughts?

**Comment by nfischer** [comment]
This is a feature I don't personally use. I don't mind keeping it if there are people out there that use it, although I see very few bug reports/feature requests for the `make` command, which makes me suspect it's less popular than the rest of the API.

**Comment by ariporad** [comment]
@nfischer: My thoughts exactly.

**Comment by zephraph** [comment]
I don't really get why this feature is being deprecated. Was it a maintenance burden? You yourselves noted that there weren't many issues coming in on this feature, so why remove it?

Here are at least two examples of where it's used:
- https://github.com/box/t3js/blob/master/Makefile.js
- https://github.com/eslint/eslint/blob/master/Makefile.js

What's the rational behind this?

**Comment by nfischer** [comment]
Given that we've already had a couple comments on this, and some prominent projects use this feature, I don't see much benefit to moving forward with removing this. We may want to consider reverting #431.

**Comment by nfischer** [comment]
I'm going to close this, since there's no reason as of yet to remove this feature.

**Comment by nfischer** [comment]
I think I forgot to publicize this here, but the documentation for `shelljs/make` moved to https://github.com/shelljs/shelljs/wiki/The-make-utility.
