### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#347]
This is a general issue that our unit tests should be more comprehensive. I've noticed that sometimes unit tests don't actually test correct behavior (this was the issue with some tests in `touch.js` that I fixed. I'm sure there are also many options/edge cases for functions that are not tested very comprehensively.

As we work toward future releases, we should also work on improving our test framework, to prevent regressions. Also, we should probably add more sanity checks in the `run-tests.js` script, since because this uses ShellJS to test ShellJS, a major break (for example: if `ls()` returns the empty array every time) can cause the test runner to give a false positive.

I'm putting the "help wanted" label on here, so if anyone is looking for something to contribute on, more test cases would be welcome.

If you'd like to contribute, please try to isolate your changes to one file per PR (it makes it much easier to review). Also, it helps if you tag this issue number in your PR. We're also interested in refactoring test cases (so as long as you know JS, you'd be able to help) :+1:

**Comment by blockloop** [comment]
Are you opposed to adding mocha?

**Comment by ariporad** [comment]
@blockloop: This is something I've been thinking about for a while. I think it might be a good idea to refactor our tests to use mocha.

@nfischer: Thoughts?

**Comment by blockloop** [comment]
I'll pitch in and help. I initially wrote the 'touch' tests with it and took them out. I'll gladly redo it.

**Comment by nfischer** [comment]
@ariporad what would be the benefits of mocha tests over using simple assert statements? How difficult would the refactor be?

**Comment by ariporad** [comment]
It would take some work, but not to hard. The benefit of mocha is that other
tools know how to work with it. (Ie. Code coverage)
Let me look into this, I'll get back to you in a day or two.

**Comment by nfischer** [comment]
Ok sounds good

**Comment by ariporad** [comment]
@nfischer, @blockloop: Actually, I think I'm going to go with [`AVA`](https://github.com/sindresorhous/ava). It will make the tests faster, and make them easier to convert.
