### ISSUE TITLE
Document that exec() options don't work on early versions of node

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#350]
As far as I can tell, options to `exec()` and `execSync()` only work for node v0.11+. This should probably get documented in our README. If enough people are interested, we could try some hacks to get it to work (we could do this for `cwd`, for example), but I don't think it's worth it, since it really only affects v0.10 users (since we don't support v0.8 anymore).

**Comment by ariporad** [comment]
@nfischer: Hmm... I'm thinking we maybe should drop v0.10 support. I think having a fragmented API is really bad.

**Comment by nfischer** [comment]
@ariporad to an extent I agree. But here's my rationale: the "supported" API could be without `exec` options. But if it's easy enough to provide these options for most versions of node, then why limit the users from that flexibility?

I think it's better to have something that covers 99% of use cases (really, how common are `exec()` calls with those options?) for node v0.10 than to simply drop support for it. Anyone who's using node v0.10 is probably doing so because it's all their package manager will install (i.e. [Ubuntu](http://packages.ubuntu.com/search?keywords=nodejs)).

**Comment by ariporad** [comment]
@nfischer: Hmm... I'm still not sold... It seems really strange to me.

**Comment by ariporad** [comment]
@nfischer: We dropped v0.10 support, right?

**Comment by nfischer** [comment]
Yup. Closing this.
