### ISSUE TITLE
Standardize command output

### ISSUE THREAD

**Issue by ariporad** [shelljs/shelljs#356]
We need to standardize the output of the commands. Currently, they return a whole bunch of things. (See the [`shx` output section](http://ariporad.link/1ojYTMg)).

I think that @nfischer is working on a standardized `ShellString` for all commands to return. I'm not sure about the details.

At bear minimum, I think that all commands need to return something with `stdout` and `stderr` properties. This will allow #269 to simply have `error()` return the exit code of the previous command (equivalent to `$?`). It will also greatly simplify `shx`.

**Comment by ariporad** [comment]
Some examples:

```
function _cmd1() {
  var out = 'foo';
  out.stdout = out;
  out.stderr = '';
  return out;
}

function _cmd2() {
  var out = [1, 2, 3];
  out.stdout = out.join('\n');
  out.stderr = '';
}

function _cmd3() {
  var out = true;
  return { stdout: true + '', stderr: '', result: out };
}


// etc.
```

**Comment by nfischer** [comment]
I'll refactor my changes later today and open a PR
