### ISSUE TITLE
ln('-sf', './', '<destination>') is not linking the right folder

### ISSUE THREAD

**Issue by mtscout6** [shelljs/shelljs#363]
https://travis-ci.org/TWExchangeSolutions/eslint-config-exchange-solutions/jobs/107132691

From what I can see there's a few issues.

1. For some reason the [`resolvedSourcePath`](https://github.com/shelljs/shelljs/blob/0da963b51f1895440ac4c96fb14248de1f028f58/src/ln.js#L46) is built up with the `dest` path?
2. On Mac OSX you don't even use the `resolvedSourcePath` when [creating the symlink](https://github.com/shelljs/shelljs/blob/0da963b51f1895440ac4c96fb14248de1f028f58/src/ln.js#L54), but it does not appear to be respecting the current working directory. This worked in 0.5.3 which was using the correct `resolvedSourcePath`.

Is there a reason not to use the `resolvedSourcePath` for all operating systems?

I can put together a PR for this, just trying to gather any backstory I'm missing.

**Comment by nfischer** [comment]
Thanks, @mtscout6! Sounds like a bug. What link does shelljs actually create?

The behavior here is a little tricky. Here's the behavior I see on my linux system:

```Bash
# test 1
$ cd testdir/
$ ls # it's empty
$ ln -s ./ dest # links to testdir/
$ cd dest/
$ ls # shows dest, since we're in testdir/
dest
$ cd ..
$ rm dest
# test 2
$ mkdir foo
$ cd foo/
$ ln -s ./ ../dest
$ cd ..
$ ls
dest    foo
$ cd dest
$ ls # ./ is still the cwd relative to the destination (dest is inside testdir/, so it links to testdir/)
dest    foo
```

A PR would be much appreciated

**Comment by nfischer** [comment]
Hmmm... I just added some new unit tests, and it seems like shelljs is behaving as described. Here's what I added, let me know if this differs from unix behavior: #364

Also, I think a suitable workaround for the time being would be to make `./` into an absolute path, either with `pwd()`, `process.cwd()`, or `path.resolve('.')`.

Thanks for trying out `v0.6`!

**Comment by rjhilgefort** [comment]
@nfischer fwiw, I'm on OSX as well and seeing the same problem.
