### ISSUE TITLE
Only Get Stderr from Exec

### ISSUE THREAD

**Issue by 360disrupt** [shelljs/shelljs#371]
I have the opposite problem to:
https://github.com/shelljs/shelljs/issues/92

On my local machine with nodemon everything works fine. On the server exec only gives me stderr and the code (which is `0` which equals `no error`).

I'm using node v.5.0.0. And it is started with `pm2` on the server.

I actually don't know if this is a bug or maybe s.th. with the server config.

**Comment by nfischer** [comment]
Hmmm... this seems like a strange issue. I don't think this is a bug with shelljs, since it seems to work on your local machine. Are you checking the `.stdout` attribute? `.output` is deprecated (and will be removed soon).

**Comment by 360disrupt** [comment]
The coffee gets compiled first by gulp before shelljs runs.
```
executeCommands = (commands, callback)->
  commandsToExecute = ""

  for command in commands
    commandsToExecute += "#{command} && "

  commandsToExecute += "echo \"finished\""

  shell.exec commandsToExecute, (code, stdout, stderr) ->
    logger.info "Exit code: #{code}", stdout
    logger.warn "Program stderr:", stderr
    err = if stderr? && stderr != "" then stderr else null
    return callback err, stdout, code
```

- `commands` is an array of shell commands
- `callback` is my callback to express

e.g. a route:
```
  app.get('/mongodump', routesService.loggedIn, routesService.cleanParams, (req, res) ->
    shellService.mongoDump req.user, (err, out, code) ->
      return res.json({err: err}) if err?
      return res.json({"out": out, "code": code})
  )
```

**Comment by 360disrupt** [comment]
PS:
Same thing with async instead of chaining:
```
executeCommands = (commands, callback)->
  commandEchoFinished = "echo \"finished\""
  commands.push({"name": "commandEchoFinished", "command": commandEchoFinished})
  results = []
  async.eachSeries commands,
    (command, next)->
      shell.exec command.command, (code, stdout, stderr) ->
        logger.info "Command: #{command.name}, exited with code: #{code}", stdout
        logger.warn "Command: #{command.name}", stderr
        err = if stderr? && stderr != "" then stderr else null
        return next err if err?
        results.push({"command":command.name, "code":code, "stdout":stdout})
        return next null
    (err)->
      return callback err if err?
      return callback null, results
```

**Comment by nfischer** [comment]
@360disrupt What if you chain the statements with `;` instead of `&&`? Or what if you put `echo 'Hello world'` as the first command? That would check if it's because of a command failing toward the end.

**Comment by jeroenransijn** [comment]
I am having a similar issue, what is your environment. I am currently using Electron with ShellJS. Also I am Webpack, no idea if this is relevant.

**Comment by 360disrupt** [comment]
I can't really say what it was. It works now, I guess the provider of the server may have changed something. My environment is `nodejs 5.9.0`.

**Comment by nfischer** [comment]
@jeroenransijn @360disrupt if either of you have the time to help figure out the bug, that would be much appreciated. I suspect it's due to differences in your environment (we list the supported nodejs and iojs versions in the README, anything outside of that we'll need help supporting).

Thanks!

**Comment by jeroenransijn** [comment]
@nfischer I was actually not well researched on what I was trying to do. Exec, even with the async option, waits for the process to finish and then gives you back the result of your command. I ended up using `require('child_process').spawn()` straight from node, which gives you a stream. I was wondering why there is no alternative in ShellJS?

**Comment by nfischer** [comment]
It returns the child process, so you can use that to access stdout or stderr.

I think this should work:

```
var c = exec('cmd', {async: true});
c.stdout.on('data', function(stdout) {
  // do something with this chunk of data
});
```

**Comment by 360disrupt** [comment]
I will use `shelljs` in another project soon. If I see the problem again I can investigate. Currently I'm not able to look into it because it disappeared.

**Comment by nfischer** [comment]
> I will use shelljs in another project soon. If I see the problem again I can investigate. Currently I'm not able to look into it because it disappeared.

@360disrupt if you can figure out what the issue is, please ping this thread again (or open a new issue). Thanks!

**Comment by nfischer** [comment]
@360disrupt @jeroenransijn were either of you able to identify the source of the issue?

**Comment by nfischer** [comment]
We did a big exec refactor, so I'm assuming this is no longer relevant. Holler if this issue comes back.
