### ISSUE TITLE
REQUEST HELP: A directory for scripts

### ISSUE THREAD

**Issue by tadeve96** [shelljs/shelljs#374]
can i have a directory where shjs command would look there if there is no script of the called name in the current directory ?

**Comment by nfischer** [comment]
Why not put scripts in your ~/bin? You can give them executable permission and add that to the path. Now it's easy to find them. Just make sure to add a shebang (either node of shjs).

^ Thats the solution taken by Linux, so I wanted to see if that was what you're looking for.

**Comment by ariporad** [comment]
@nfischer: I still think it would be a useful bit of functionality to be able to run `shjs scripts`. (We should also glob shjs.

@tadeve96: For now, you can just run `shjs scripts/*.js`, and bash should glob that.

**Comment by nfischer** [comment]
@ariporad I read this issue as asking for something different I think. I read it as:

```bash
$ shjs scriptName.js # this is a shorthand for...
$ shjs path/to/special/shjs/scripts/folder/scriptName.js
```

Assuming that scriptName.js is not a file in the current folder. This has nothing to do with globbing (your command line shell would handle that).

Why would someone want to run every script in a special folder with a single command? That doesn't sound very useful to me.

**Comment by ariporad** [comment]
@nfischer: Hmm... Yeah, I did.

We run every script in a folder twice during our build process. (We run ever script in `scripts/`, then every script in `test/`).

**Comment by nfischer** [comment]
I agree it's useful as a build step. But why would someone want to run every script in one system wide folder, let's call it `~/shelljsscripts`? That doesn't sound very useful.

To me this issue sounds like it's asking for a system wide folder, which shjs will treat as a special sort of PATH to hunt for script names. I see the use case (for individual scripts), but it raises some security concerns and it doesn't seem to solve anything the PATH env variable doesn't already solve in a more well-defined way.

**Comment by ariporad** [comment]
Oh yeah, that's totally not how I thought about it. That would be
confusing.

**Comment by nfischer** [comment]
I think it's dangerous behavior to have shjs, if given a directory as an argument, run every single coffee and js file inside. Thats running a lot of code the user may not intend to be running. Making them out `/*.js` at the end isn't so bad, and then they know exactly what will happen.

Not sure if shjs actually supports the globbing (I think it only runs its first file argument, not any others). But that's closer to what makes sense. I think sticking with the bash utility's semantics here is the right move.

**Comment by ariporad** [comment]
@nfischer: Ok. But we should make `shjs` support globbing (Right now it doesn't).

**Comment by ariporad** [comment]
I'm going to close this, and open a new issue.
