### ISSUE TITLE
Support globbing in `shjs`

### ISSUE THREAD

**Issue by ariporad** [shelljs/shelljs#388]

**Comment by ariporad** [comment]
I'll do this.

**Comment by nfischer** [comment]
@ariporad Could you give an example of where globbing *should* be that it already isn't?

**Comment by ariporad** [comment]
> shjs scripts/*.js

**Comment by ariporad** [comment]
Also, while we're at it, shjs should append NODE_PATH, not override it.

**Comment by nfischer** [comment]
^ appending to NODE_PATH might be better.

I'm not sure I understand the issue with the glob scenario you provided. Here's the steps I think would happen:

```Bash
# assuming we're launching from bash, sh, zsh, or some similar **unix** shell (not cmd.exe)
$ shjs scripts/*.js # this is what you type in to the shell, manually
$ shjs scripts/foo.js scripts/bar.js scripts/baz.js # your shell expands the glob, so it looks
# exactly as if you typed this (assuming there are exactly 3 .js files, named as such)
# Then, shjs runs the first script (scripts/foo.js), and passes it some arguments (scripts/bar.js,
# scripts/baz.js)
```

Does this differ from what you would see for the following example?

```Bash
$ bash scripts/*.sh # same thing, but the "bash version"
```

**Comment by ariporad** [comment]
@nfischer: Hmm...

It doesn't, but it's counter-intuitive behavior.

**Comment by nfischer** [comment]
It's not counter-intuitive for someone who wants to be able to write a script like:

```javascript
#!/usr/bin/env node
require('shelljs/global');
config.silent = true;
echo(cat(process.argv[3])
  .exec('tr -cs A-Za-z \'\\n\'')
  .exec('tr A-Z a-z')
  .sort()
  .exec('uniq -c')
  .sort('-rn')
  .head('-n', process.argv[3]));
```

(note the `process.argv`s as a way of passing input to the script)

**Comment by ariporad** [comment]
@nfischer: Good point. I'll close this.
