### ISSUE TITLE
Plugin System.

### ISSUE THREAD

**Issue by levithomason** [shelljs/shelljs#391]
**[NOTE: This thread was originally about the `open` command. I'm hijacking it. -@ariporad]**

It would be nice to have a plugin system for shelljs which allows custom commands.

**Comment by nfischer** [comment]
@levithomason Thanks for the suggestion!

Unfortunately, `open` seems to have very different semantics across different systems. `open` on OS X will do as you described, while `xdg-open` on a Linux system does the equivalent. [This stackoverflow post](http://stackoverflow.com/questions/264395/linux-equivalent-of-the-mac-os-x-open-command) discusses it.

I can't remember off the top of my head what `open` does on Linux, but I know there is such a command, so I'm hesitant to implement an `open()` function that differs from that in semantics. Maybe if we could find a different (non-ambiguous) name? Let me know if you have any suggestions.

**Comment by levithomason** [comment]
It seems the common denominator (except Windows) to opening a file with the default program is `open()`.

```
$ gnome-open file.txt   // Linux
$ xdg-open file.txt     // Linux
$ gvs-open file.txt     // Linux
$ open file.txt         // Mac
$ file.txt              // Windows
```
Ref [Windows](http://superuser.com/questions/246825/open-file-from-the-command-line-on-windows) and [Linux](http://askubuntu.com/questions/101965/what-is-the-replacement-for-gnome-open-in-gnome).

Though, [`$ open` on Linux](http://man7.org/linux/man-pages/man2/open.2.html) seems to open a file descriptor but not the default program?

**Comment by nfischer** [comment]
Yeah, `open` has pretty different behavior between mac and Linux.

I think this would perhaps be better done as a separate module that plugs in. We could do a `shelljs-open` module which would call `xdg-open` for Linux (that's a shell script available on pretty much any distro), `open` on Mac, and just the filename on Windows. Wouldn't be hard to implement, and we could probably find a clever way to make it feel like it's part of the shelljs package itself when both are included.

@levithomason What do you think?

**Comment by ariporad** [comment]
So, I'd actually like to hijack this thread as a way of discussing custom shelljs commands.
Currently, this is what we suggest:
```javascript var git = require('git'); var open = require('@shelljs/open'); var shell = require('shelljs');
shell.cd('foo/bar/baz'); git.checkout('branch'); open('foo.txt'); ```
This might be a good time to try and implement a proper extension API. Here's what I'm thinking are some good requirements to start with: 1. Should allow adding custom commands (ex. `shell.foo()`). * Sub-commands would be nice too (ex. `shell.git.checkout()`) 2. Commands should behave exactly like normal shelljs commands. (Unsure how this works out with SHX). 3. It would be nice to expose some of our internal stuff to plugins, like `wrap` and `expand`.
Here's two ideas I had, off the top of my head: ```javascript // Idea 1 // Plugins register themselves.
// git.js var shell = require('shelljs'); var plugins = require('shelljs/plugin'); var git = plugins.register('git', _git, { idx: 1 }); // Same signature as `common.wrap` git.register('checkout', _checkout, { idx: 1 });
// index.js require('shelljs-plugin-git'); var shell = require('shelljs'); shell.git.checkout('foo.txt'); ```
```javascript // Idea 2 // You pick your plugins
// git.js module.exports = function(shell, plugins) { // ... }
// index.js var shell = require('shelljs');
shell.plugins(['git']); // Shorthand for 'shelljs-plugin-git' ```
If we go this route, I think it would make sense to implement builtin commands as plugins, which would be nice.
Thoughts?

On Sun, May 15, 2016 at 3:59 PM, Nate Fischer <notifications@github.com> wrote:
Yeah, open has pretty different behavior between mac and Linux.

I think this would perhaps be better done as a separate module that plugs in. We could do a shelljs-open module which would call xdg-open for Linux (that's a shell script available on pretty much any distro), open on Mac, and just the filename on Windows. Wouldn't be hard to implement, and we could probably find a clever way to make it feel like it's part of the shelljs package itself when both are included.

@levithomason [https://github.com/levithomason] What do you think?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub [https://github.com/shelljs/shelljs/issues/391#issuecomment-219316698]

**Comment by ariporad** [comment]
So, I'd actually like to hijack this thread as a way of discussing custom shelljs commands.

Currently, this is what we suggest:

```javascript
var git = require('git');
var open = require('@shelljs/open');
var shell = require('shelljs');

shell.cd('foo/bar/baz');
git.checkout('branch');
open('foo.txt');
```

This might be a good time to try and implement a proper extension API. Here's what I'm thinking are some good requirements to start with:
1. Should allow adding custom commands (ex. `shell.foo()`), and subcommands (ex. `shell.git.checkout()`)
2. Commands should behave exactly like normal shelljs commands. (Unsure how this works out with SHX).
3. It would be nice to expose some of our internal stuff to plugins, like `wrap` and `expand`.

Here's two ideas I had, off the top of my head:
```javascript
// Idea 1
// Plugins register themselves.

// git.js
var shell = require('shelljs');
var plugins = require('shelljs/plugin');
var git = plugins.register('git', _git, { idx: 1 }); // Same signature as `common.wrap`
git.register('checkout', _checkout, { idx: 1 });

// index.js
require('shelljs-plugin-git');
var shell = require('shelljs');
shell.git.checkout('foo.txt');
```

```javascript
// Idea 2
// You pick your plugins

// git.js
module.exports = function(shell, plugins) {
    // ...
}

// index.js
var shell = require('shelljs');

shell.plugins(['git']); // Shorthand for 'shelljs-plugin-git'
```

If we go this route, I think it would make sense to implement builtin commands as plugins, which would be nice.

Thoughts?

**Comment by nfischer** [comment]
@ariporad This sounds like a really neat idea. I have a couple clarifying questions.

1. Would `git.js` be in a separate module (the `shelljs-plugin-git` module)?
2. Would `_git` be a function that's implemented within the `shelljs-plugin-git` module?

I like the idea of letting users pick which plugins they use. It'd be weird to require someone to use the `git` plugin if they only wanted the `open()` plugin (assuming these are both implemented as plugins).

I'm definitely in favor of allowing subcommands. That's an excellent suggestion.

I like the syntax of:

```javascript
var shell = require('shelljs');
shell.plugin(require('shelljs-plugin-git')); // allows shell.git()
shell.plugin(require('shelljs-plugin-open')); // allows shell.open()
```

I'm not sure what this would look like for `require('shellljs/global')`, however. Ideally, we should have a syntax that makes sense for both forms of requires. If there's a way for plugins to reliable register themselves (with both global & non-global requires), then I wouldn't be opposed to that.

**Comment by nfischer** [comment]
Actually, probably the simplest syntax is this:

```javascript
var shell = require('shelljs');
shell.git = require('shelljs-plugin-git'); // allows shell.git()

// or with global requires...
require('shelljs/global');
var git = require('shelljs-plugin-git'); // allows git()
```

**Comment by ariporad** [comment]
Yes, git.js is in a separate plugin? And _git is the implementation of the command.

Here's an idea I quite like:

```javascript
// git.js
var shell = require('shelljs');
var plugin = require('shelljs/plugin');
var git = module.exports = plugin.Plugin('git', opts); // Plugins can't be called as functions. Command is a subclass of Plugim, so you are free to export a Command instead if you prefer. In the future, we may have other types.
git.subcmd(plugin.Command('checkout', _checkout));

// index.js
shell.use('git') // shorthand for shell.use(require('shelljs-plugin-git'))

shell.git.ch
```

**Comment by levithomason** [comment]
This sound great.  +1 to `shell.use('git')` with shorthand.

I don't follow what is happening with `plugin.Plugin()` and `git.subcmd`.

**Comment by nfischer** [comment]
> ```
> shell.use('git') // shorthand for shell.use(require('shelljs-plugin-git'))
> ```

How would this work with a global require()? Also, I don't like `shell.use()`, since the only functions we have as properties of `shell` are command implementations (e.g. `shell.ls()`, `shell.grep()`, etc.). Seems confusing to throw `shell.use()` into the mix.

**Comment by levithomason** [comment]
I don't use nor know enough on the global require to comment.  Personally, I think that many globals is not a good idea.  I just use `sh.ls()`.

I guess `shell.use()` reminds me of other plugins systems, like `chai.use()`.  Whereas requiring a module and attaching it to an object doesn't really seem like a plugin.

I think there is unforeseen future advantage in starting out with a function pattern.  When adding a plugin, you might want to provide validation, or compatibility information, etc.  If there is a plugin spec, and a method for `use()`ing the plugin, then this can be done consistently and easily.  But, if plugins are added to the instance via assignment, it is much more difficult.

That said, it doesn't have to be on the `shell` instance.  It could be `plugin.use(shell, 'git')` where `shell` is your instance of shelljs.

**Comment by nfischer** [comment]
I have no issues with `plugin.use(shell, 'git')`. We might even be able to configure this to allow `plugin.use('git')` to export to the global namespace.

I agree modifying the global namespace isn't the greatest thing. The idea is to stay consistent with the current API (some people still use `shelljs/global`). It'd be weird to have `echo('foo')` work but require someone to use `shell.git(...)` within the same file, so we need a slightly different approach for those using `require('shelljs/global')`.

If we're extremely against modifying the global namespace, we can create a plugin system that's only compatible with non-global requires. Although I'm in favor of encouraging folks to use `require('shelljs')`, I don't really like having an inconsistent API.

**Comment by levithomason** [comment]
Agree on consistency, also may cause some unrest if the plugin system were limited to non-global use.

I'm down with converting this issue into a plugin system issue.  Or, killing this one and creating a new plugin system PR to hash the rest of it out.  I'll likely be taking a passive position it anyhow.  Will try to offer input when available.

**Comment by ariporad** [comment]
Ok, thread has been hijacked.

I'd like to strongly vote against `plugin.use(shell, 'git')`. I think that `shell.use` is OK, I don't think it would cause problems. (See `shell.config`, `shell.ShellString`).

I'm not sure about the global namespace, adding tons of globals seems bad, but it is useful.

Here's an idea, which would make the non-global option easier: What if we renamed `shell` to `$`. Ex:

```javascript
var $ = require('shelljs');
$.ls('foo');
```

As for what's happening with the `Plugin`/`subcmd`, here's a more annotated example (I was on mobile):

```javascript
// git.js
var $ = require('shelljs');
var plugin = require('shelljs/plugin');

// WARNING: This is quite literally the first think I came up with in 30 seconds typing
// on an iPhone. It's totally not set in stone.

// plugin.Plugin is a class (or maybe a factory). It's the base class for all plugins.
// It's pretty self-contained, and does basically nothing.
// plugin.Command is a subclass of plugin.Plugin. It defines a plugin which can
// called as a function.
// In the future, we could add additional plugin types.
// In this example, `shell.git`, WOULD NOT be the Plugin instance, it would be
// something else.

// First, have the actual code.
function _checkout(file) {
    // ...
}

function _track(file) {
    // ...
} 

// Next, create the initial plugin instance. We export it so that we can `shell.use`
// it later.
var git = module.exports = plugin.Plugin('git', opts);

// Now create another plugin (in this case a command), for `git checkout`
var checkout = plugin.Command('checkout', _checkout, { idx: 1 });

// Now, mount `checkout` on `git`.
git.subcmd(checkout);

// Here's an example of a sub-sub-command: `git lfs track`  (It was the first thing
// I could think of, it's GitHub's solution for large files).

// First, create the plugin
var lfs = plugin.Plugin('lfs', opts); // Again, `git.lfs()` is invalid.

// Then, create the command.
var track = plugin.Command('track', _track, {idx: 0});

// Then, mount it.
lfs.subcmd(track);
git.subcmd(lfs);



// index.js
var $ = require('shelljs');
$.use('git') // shorthand for $.use(require('shelljs-plugin-git'))

$.git.checkout(opts, "foo");
$.git.lfs.track('bar');
$.git.lfs(); // TypeError
$.git(); // TypeError


// For global mode, nothing about the plugin changes.
// index-global.js
require('shelljs/global'); // This now defines global.$ = require('shelljs');
$.use('git'); // We don't define a global 'use', so nothing changes.

// Now we define global.git = global.$.git, so this works:
git.checkout('foo');
git.lfs.track('foo');
$.git.checkout('foo');
$.git.lfs.track('foo');
git.lfs(); // TypeError
git(); // TypeError
```

**Comment by nfischer** [comment]
> I'd like to strongly vote against plugin.use(shell, 'git'). I think that shell.use is OK, I don't think it would cause problems. (See shell.config, shell.ShellString).

I think `shell.use()` is too narrow in scope. This makes it difficult to add more functions for working with plugins. I'm not sure which additional functions we'll *necessarily* want, but here's some potential ideas:

 - `plugin.list(shell)` -- list all plugins currently in-use
 - `plugin.check(shell, 'git')` -- perhaps this checks if the `git` plugin is in-use
 - `plugin.remove(shell, 'git')` -- remove this plugin (perhaps it conflicts with another plugin you need to use later down the road in the same script)

Whether we like these *specific* functions or not, this sort of syntax lets us expand to more possibilities beyond `use()`. I'm not opposed to `shell.plugin.use()`, but I'm not sure how that would look for global requires. I don't like adding *all* these methods directly onto `shell` though.

> Here's an idea, which would make the non-global option easier: What if we renamed shell to $.

I see where you're going with this, and it's a solid approach, but it just doesn't feel quite right. This still puts the plugin function in a namespace, it just doesn't give the user any control over what that namespace is. I would still be in favor of something like:

```javascript
require('shelljs/global');
var plugin = require('shelljs/plugin'); // or it could be a different path, doesn't matter to me
plugin.use('git'); // we're using the name `plugin`, but that's totally by choice, just like with any module
```

**Comment by ariporad** [comment]
@nfischer: I can't really think of a use case for any of those. I think we should emphasize that 1 plugin = 1 command, so there wouldn't be a reason for `.remove` or `.check` (`.check` can be replaced by `!!$[cmd]`).

I personally like `$.use` because it's similar to other plugin systems (ex. `chai`). If we need to add other things in the future, we could alias `$.use` to `$.plugin.use`. I agree that we don't want `$.list` or `$.remove` or `$.check`.

>  > Here's an idea, which would make the non-global option easier: What if we renamed shell to $.
>
> I see where you're going with this, and it's a solid approach, but it just doesn't feel quite right. This still puts the plugin function in a namespace, it just doesn't give the user any control over what that namespace is. I would still be in favor of something like:

That's not really what I meant. I meant that (in the docs), we recommend that you:

```javascript
var $ = require('shelljs');
```

Instead of:
```javascript
var shell = require('shelljs');
```

Because most people use whatever we name we suggest, this would make the non-global option. (ex. `$.ls()` vs `shell.ls()`, a few chars).

**Comment by nfischer** [comment]
> Because most people use whatever we name we suggest, this would make the non-global option. (ex. $.ls() vs shell.ls(), a few chars).

Yeah, but people are usually smart enough to figure that out if it's important to them ([cash](https://github.com/dthree/cash) is a great example). I think it's better to have a less-cryptic namespace than to save a few chars.

Weren't we discussing how to make a plugin system compatible with global imports? You said that with `require('shelljs/global')` it still uses the `$` variable:

> ```javascript
> // index-global.js
> require('shelljs/global'); // This now defines global.$ = require('shelljs');
> $.use('git'); // We don't define a global 'use', so nothing changes.
> ```

To me, that doesn't seem like the right thing to do. That's only slightly better than importing `use()` directly into the global namespace.

**Comment by ariporad** [comment]
Sorry, I explained that poorly. I was suggesting that for global imports, we do two things:

1. As a bonus feature of  `shelljs/global`, we define a  `global.shell` variable.
2. When using global mode, plugins are still registered using `shell.use`, but `shell.use('git')` defines both `shell.git` and `global.git`.

**Comment by levithomason** [comment]
-1 to adding more global variable definitions.  This could cause a lot of problems.  You could easily blow away some local variable doing this.  Also, what if I already had a global named `shell` or `$`?  If I wanted to use `shelljs/global` I'd first have to refactor my codebase.  Or, we'd have to have a config option for the global name you want to use, which just seems worse.

I think the assignment needs to be really explicit.

**Comment by nfischer** [comment]
Let's brainstorm some more APIs for this sort of thing. I don't think we've found anything great just yet. I think we should figure out a syntax that is mostly the same, for either local or global imports, without polluting the global namespace more than necessary.

**Comment by nfischer** [comment]
Here's the link to [eslint's plugin docs](http://eslint.org/docs/developer-guide/working-with-plugins). I think their plugin API isn't quite right for us (it's all in config files), but it might be good food for thought. Feel free to post links to other plugin-usage APIs, so we can get some idea of how to design ours to be consistent.

**Comment by levithomason** [comment]
[Chai](http://chaijs.com/guide/plugins/) is great, possibly a little more applicable to our pattern.  I also like [Gulp plugins](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/README.md), however, they are all about streams so the pattern isn't a 1:1.  [Webpack's plugins](https://github.com/webpack/docs/wiki/How-to-write-a-plugin) are more similar to gulp in that they are called in sequence and operate on files but still may have ideas to glean.  Lastly, I think the simplicity and self referential [jQuery plugin](https://learn.jquery.com/plugins/basic-plugin-creation/) is most like something we're trying to achieve here (if not Chai).

These are all great plugin systems and probably have some aspects we can incorporate.

**Comment by ariporad** [comment]
Here's my $0.02:

* I really like Chai's system, it seems simple but powerful, and it would be easy to use for ShellJS.
* Not a huge fan of jQuery plugins, they're basically glorified monkey-patching.
* I think that gulp's system isn't super relevant, as it revolves around a factory-returning-a-stream, and we don't have an equivalent of a steam to return.
* Webpack's system seems kind of confusing to me, and it looks like a bit of callback hell.
* It's worth considering that we're trying to impliment a command, similar to jQuery or Chai, not a transform, like Webpack or Gulp.

**Comment by ariporad** [comment]
Also, here's the features we need (feel free to edit):

- [ ] Add a command to `shell`.
- [ ] Add commands to commands (ex. `git commit` and `git lfs track`.)
- [ ] Callable Commands (ex. `ssh`)
- [ ] Non-callable commands (ex. `git`)
- [ ] Expose internal shelljs utils.

**Comment by ariporad** [comment]
@nfischer, @levithomason: Any other thoughts on this?

**Comment by ariporad** [comment]
Here's another idea in favor of a `chai`-like system:

You'll recall how I talked about (I forget where), about a way to convert bash commands to shelljs easily using proxies?

Well, here's an example API which accomplishes roughly the same thing using a chai-like interface:

```javascript
var $ = require('shell');

$.use(shellify('git')('commit', 'add', 'push'));

$.git.add('.'); // Converted to exec('git add "."')
$.git.commit({ message: 'feat: super awesome feature' }); // Converted to exec('git commit --message "feat: super awesome feature"')
$.git.push({ 'set-upstream': 'origin' }, 'master'); // Converted to `git push --set-upstream "origin" "master"')

// Here's shellify
function shellify(cmdname) {
   return function(...cmds) {
     return function($, utils) {
        // This part of the API needs bikeshedding     
        // For callable commands, like `open`
        if (!cmds.length) return utils.cmd($, cmdname, (opts, ...args) => $.exec(cmdname, optsToFlags(opts), ...args);
       // For more complex commands, like git.
       var cmd = utils.cmd($, cmdname, opts);
       cmds.forEach(name => utils.cmd(cmd, name, (opts, ...args) => $.exec(cmdname, name, optsToFlags(opts), ...args));
     }
  }
}
```

**Comment by ariporad** [comment]
Oops... Wrong button. Sorry.

**Comment by levithomason** [comment]
No other comments here.  I'll let you two solve this one from here.

**Comment by nfischer** [comment]
@ariporad Thanks for giving this lots of thought! I'm really excited about a plugin architecture.

Looks like `shellify` is in the global namespace, which I'm opposed to. Aside from that, here's some quick thoughts:

 - `$.use('git')` is a really short interface for using plugins, which is awesome. However, this hides the fact that `shelljs-plugin-git` is a dependency for your project. Why make things so obscure? `$.use(require('shelljs-plugin-git'))` is much clearer, I think. Is there a precedent for your syntax?
 - I'd personally like `git('-C mydir/ pull origin master')` to be an allowable syntax. Depending on how we implement these sorts of plugins, I think commands should be callable, but should also have convenient methods where appropriate. This lets you have both `git('-C ...')` as well as `git.add(...)`.
 - Parsing the docs sounds like it'd be pretty difficult in the general case. I'd rather have plugin authors pick and choose their favorite commands/subcommands to implement, instead of forcing them to implement them all.
 - I don't want `git.commit` to just convert to `exec("git commit")`. That's pretty limiting for commands like `open('file.txt')`, where you need different behavior under different conditions. If executing code in the shell makes the most sense, then they can always use `shell.exec()`, right?

**Comment by nfischer** [comment]
[Here's](https://github.com/nlp-compromise/nlp_compromise#pluginmixins) an example module that uses a `.plugin(require('plugin-name'))` syntax, which sounds clearer to me than `.use('plugin-name')`.

**Comment by ariporad** [comment]
@nfischer: Sorry, I think I came across a little confused. Let me clarify a bit:

> Looks like shellify is in the global namespace, which I'm opposed to. Aside from that, here's some quick thoughts:

I was thinking it would either be a seperate module or a property of `$`.

>$.use('git') is a really short interface for using plugins, which is awesome. However, this hides the fact that shelljs-plugin-git is a dependency for your project. Why make things so obscure? $.use(require('shelljs-plugin-git')) is much clearer, I think. Is there a precedent for your syntax?

ESLint does this.

> I'd personally like git('-C mydir/ pull origin master') to be an allowable syntax. Depending on how we implement these sorts of plugins, I think commands should be callable, but should also have convenient methods where appropriate. This lets you have both git('-C ...') as well as git.add(...).

👍 

> Parsing the docs sounds like it'd be pretty difficult in the general case. I'd rather have plugin authors pick and choose their favorite commands/subcommands to implement, instead of forcing them to implement them all.

Agreed, it was just an idea I had.

> I don't want git.commit to just convert to exec("git commit"). That's pretty limiting for commands like open('file.txt'), where you need different behavior under different conditions. If executing code in the shell makes the most sense, then they can always use shell.exec(), right?

That would just be one (possible) option. Plugin devs could also impliment the functionality in JS.

I'm going to have quite a bit of free time this weekend, why don't I work on a mockup and we can go from there?

**Comment by nfischer** [comment]
@ariporad Do you want to take on adding subcommand support for plugins? Are there any other options/features you'd like for plugins?
