### ISSUE TITLE
new release required. npm is out of date

### ISSUE THREAD

**Issue by AshHeskes** [shelljs/shelljs#405]
The documentation on http://documentup.com/shelljs/shelljs is out of sync with http://documentup.com/shelljs/shelljs. Specifically the grep command options '-l' was added in https://github.com/shelljs/shelljs/commit/90569dcdac96249516999c5e7afea05b6698d2cd and npm hasn't been updated since.

**Comment by ariporad** [comment]
Hi @AshHeskes,

Yes, the documentation on master doesn't exactly match what's on NPM, because master is the development version (So `grep('-l')` won't work with the current npm version!). Sorry for any confusion!

I'm going to close this, but feel free to reopen if I've misunderstood the problem.

**Comment by nfischer** [comment]
Yup, a new release is on the way. A few more loose ends to tie up, and then we'll have v0.7 released to npm. Should be this week or next :+1:
