### ISSUE TITLE
Pipe example from 'Readme' doesn't work

### ISSUE THREAD

**Issue by hjek** [shelljs/shelljs#406]
```
$ cat pipe.js 
require('shelljs/global')
echo('files with o\'s in the name:\n' + ls().grep('o'));

$ shjs pipe.js 
/home/pelle/pipe.js:3
echo('files with o\'s in the name:\n' + ls().grep('o'));
                                             ^
TypeError: ls(...).grep is not a function
    at Object.<anonymous> (/home/pelle/pipe.js:3:46)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by ariporad** [comment]
Hi @hjek!

I think the problem is most likely that you're using shelljs 0.6 (which is currently on npm), where as the README on master is the development version, which is 0.7. Can you confirm that this is the case?

Thanks!

**Comment by hjek** [comment]
That was the problem, and the [documentation on there](https://www.npmjs.com/package/shelljs) also doesn't mention pipes.

**Comment by nfischer** [comment]
The README is still the best place to check for docs, but it documents all the new features that may or may not be released yet. I'll add a warning to the top of the README to clarify this.
