### ISSUE TITLE
exec doesn't work with qualified paths on windows

### ISSUE THREAD

**Issue by stuartf** [shelljs/shelljs#41]
A command like `shell.exec('./node_modules/.bin/mocha' + MOCHA_OPTS);` works on Linux and OSX, but on windows it complains that `.` isn't a command.

**Comment by nfischer** [comment]
I think @czchen's approach should work. Closing this. Feel free to re-open if the issue persists.

In general, you can't run commands of the form `./path/to/file` on Windows. `path/to/file` should be a suitable alternative. If it's in the current working directory, unix requires `./file.sh` and windows requires `file`, so you should check the value of `process.platform` to achieve os-agnostic code
