### ISSUE TITLE
Catch exec() output

### ISSUE THREAD

**Issue by andkirby** [shelljs/shelljs#416]
I'm expecting that `exec('git status')` returns me output and status code.
It does but it doesn't catch output. Even using `2>&1` doesn't help.
`a=exec('git status 2>&1')` shows output but it shouldn't.
How to catch it?

**Comment by ariporad** [comment]
Hi!

exec by default outputs to the console. If you don't want that, you can do `exec('git status', { silent: true })`


I'm going to close this, but feel free to reopen if I've gotten it wrong.

**Comment by andkirby** [comment]
Thanks for this note! It's helpful
