### ISSUE TITLE
Every shell command is executed multiple times

### ISSUE THREAD

**Issue by Ruskyj** [shelljs/shelljs#427]
### Node version:
0.10.42

### ShellJS version (the most recent version/Github branch you see the bug on):
0.6.0

### Operating system:
Linux (no idea what type, uname -v gives me this: #1 SMP Mon Aug 10 09:44:54 EDT 2015)

### Description of the bug:
Hi guys, I'm new to all this, but I ran into a problem. Every command I send to the shell via the shelljs is executed multiple times (random number, usually around 5-10). It works fine on my local enviroment (MacBook pro), but when I try it on the production server, it's always acting up like this.
Every command I tried is executed multiple times (git pull, echo, gulp, copy, etc...)

Any ideas what I'm doing wrong? Thx

### Example ShellJS command to reproduce the error:

```javascript
require('shelljs/global');

console.log("Test");
exec("echo whatever");
```

### ShellJS command output on my machine:
```
Test
whatever
whatever
whatever
whatever
whatever
whatever
whatever
whatever
```

**Comment by Ruskyj** [comment]
Quick update: using **execSync** module works (outputting all commands just once).

**Comment by nfischer** [comment]
@Ruskyj Would you be able to use a more recent version of node? I've seen things like this before on node v0.10. If you use node v4+ that should be a workaround

**Comment by Ruskyj** [comment]
@nfischer Unfortunatelly, I don't think so. It took 2 weeks just to get NodeJS on that machine installed. Corporate processes BS...

I fixed it by using execSync for now. But thx for the info, I'll keep that in mind for my future projects. Btw, this info should probably be mentioned in documentation as well.

**Comment by nfischer** [comment]
@Ruskyj 

> Nodejs is really old: 0.10.42

Yeah, that makes more sense. I've seen something similar to this before (although it always seemed to work correctly for the most part).

Unfortunately, we recently [dropped support for v0.10](https://github.com/shelljs/shelljs/wiki/Migrating-from-v0.6-to-v0.7) for future development. Since we're getting ready to release v0.7, we probably won't be able to focus on this issue. If you can figure out a fix, please feel free to submit a PR.

**Comment by Ruskyj** [comment]
It's ok, I completely understand, 0.10 is from the stone age.
I might look into that if I ran into further problems. 

Thx for your time ;)
