### ISSUE TITLE
exec() stdout should be a ShellString

### ISSUE THREAD

**Issue by cancerberoSgx** [shelljs/shelljs#430]
stdout and stderr properties of the object returned by exec() should be ShellString , example:

var target = './myfile.js';
var cmd = shell.exec('browserify ./src/index.js', {silent:true});
// cmd.stdout.to(target) //should work but fails! instead I have to do: 
new shell.ShellString(cmd.stdout).to(target);

**Comment by ariporad** [comment]
Hi @cancerberoSgx!

Actually, the `stdout`/`stderr` properties of `exec` aren't `ShellString`s, but rather the return value of `exec` itself is. I believe that what you want can be accomplished simply with `cmd.to(target)`.

I'm going to close this, but feel free to re-open if I've misread it.

**Comment by nfischer** [comment]
> I believe that what you want can be accomplished simply with cmd.to(target)

@cancerberoSgx As of ShellJS v0.7 (just got released) this is the recommended way of using it.

Just added an entry for it in [the breaking changes wiki](https://github.com/shelljs/shelljs/wiki/Migrating-from-v0.6-to-v0.7).

**Comment by cancerberoSgx** [comment]
thanks! that did the trick. but, what about stderr ? although is not important. Thanks

**Comment by nfischer** [comment]
You should do as you described in the above post. It's rare enough to redirect stderr that we felt it was worth the trade off
