### ISSUE TITLE
[ Feature ] SSH command

### ISSUE THREAD

**Issue by MatthieuLemoine** [shelljs/shelljs#435]
Feature request for the ssh command.

It could be a wrapper around [mscdex/ssh2](https://github.com/mscdex/ssh2) client.
It allows to execute a command over ssh or to maintain an interactive shell session.

**Comment by nfischer** [comment]
What would the interface look like? Could you give an example use case?

**Comment by ariporad** [comment]
I've actually been thinking about this recently.

I think it would be really cool to do something like this:

```javascript
var git = shell.cmd('git')

git.commit({ a: true, message: 'feat(commands): add shell.cmd'}, 'foo bar', 'baz');
```

Which is exactly equivalent to:

```bash
$ git commit -a --message "feat(commands): add shell.cmd" "foo bar" "baz"
```

If we could do this for any possible command, that would be pretty awesome.

I looked into doing this, I'm pretty sure we'd have to use ES6 Proxies (node >=`5.12`), or change the syntax to `git.cmd('commit', { a: true, message: 'feat(commands): add shell.cmd'}, 'foo bar', 'baz');

Thoughts?

**Comment by MatthieuLemoine** [comment]
I thought about:  

```javascript
const opts = {
  user : 'root',
  host : 'host.com',
  port : 22
};
const cmd = 'service nginx restart';

// Execute a command on remote host
ssh.exec(opts, cmd);

// Start an interactive shell on remote host / Connect to a remote host
ssh.connect(opts);
```

As you said @ariporad, to implement commands with a large set of subcommands (such as git), ES6 proxies are the only way to avoid wrapping all commands one by one. But there is no polyfill for this use case. 

It's not an issue for ssh as we only need 2 subcommands.

**Comment by nfischer** [comment]
@ariporad Your idea sounds really cool! Since it requires proxies, I think this is something that probably shouldn't be part of shelljs itself, but perhaps could be its own module on top of shelljs. I'd be interested in pursuing this, but let's discuss on gitter or on a different thread.

@MatthieuLemoine One concern I see is in regards to authentication. In the example `ssh.exec(opts, cmd)`, how do you envision handling the login password? Would this halt execution to prompt the user in the terminal?

**Comment by MatthieuLemoine** [comment]
@nfischer 
[mscdex/ssh2](https://github.com/mscdex/ssh2) can handle several methods of authentication. 

A shelljs user could do one of the following : 
1.  Set his password in the opts object
2. Set the path to his private key in the opts object
3. Set the path to his SSH-Agent in the opts object
4. Set tryKeyboard to true in the opts  and then it would prompt the user for his password

More info [here](https://github.com/mscdex/ssh2#client-methods)

**Comment by MatthieuLemoine** [comment]
As [mscdex/ssh2](https://github.com/mscdex/ssh2) uses streams,  it will not halt the execution during the `ssh.exec` or `ssh.connect`.

But we can syncify it if needed by spawning a childProcess.

**Comment by ariporad** [comment]
@MatthieuLemoine: Why can't you just use mscdex/ssh2 directly? That's kind of the whole point of shelljs, you can use normal node modules (of which there are quite a few).

**Comment by MatthieuLemoine** [comment]
@ariporad : It requires a lot of boilerplate code to create a  common ssh client with mscdex/ssh2 as you have to handle output, input and error streams.

```javascript
// Interactive shell client
const client = new Client();
client.on('ready', () => {
  client.shell((err, stream) => {
    if (err) throw err;
    // Piping
    process.stdin.setRawMode(true);
    process.stdin.pipe(stream);
    stream.pipe(process.stdout);
    stream.stderr.pipe(process.stderr);

    stream.on('close', () => {
      // Release stdin
      process.stdin.setRawMode(false);
      process.stdin.unpipe(stream);
       // End connection
       client.end();
    });
  });
});

// Exec a command over ssh
const cmd = 'pwd';
const client = new Client();
client.on('ready', () => {
  client.exec(cmd, (err, stream) => {
    if (err) throw err;
    stream.pipe(process.stdout);
    stream.stderr.pipe(process.stderr);
    stream.on('close', () => {
      client.end();
      end();
    });
  });
});
```

The idea is to abstract it to allow the user to only type a single command like other shelljs commands.

**Comment by ariporad** [comment]
Hmm...
It seems like this might be better-suited as a module outside shelljs, with an API like this:
``` var ssh = require('ssh');
ssh.connect({ host: '...', username: '...', password: '...'}); ssh.exec('rm -rf foo bar'); ssh.close(); ```
Unless I'm missing something.
On Fri, Apr 29, 2016 at 12:40 AM, Matthieu Lemoine <notifications@github.com> wrote:
@ariporad [https://github.com/ariporad] : It requires a lot of boilerplate code to create a common ssh client with mscdex/ssh2 as you have to handle output, input and error streams.

// Interactive shell clientconstclient=newClient();
client.on('ready', () => {
  client.shell((err, stream) => {
    if (err) throw err;
    // Pipingprocess.stdin.setRawMode(true);
    process.stdin.pipe(stream);
    stream.pipe(process.stdout);
    stream.stderr.pipe(process.stderr);

    stream.on('close', () => {
      // Release stdinprocess.stdin.setRawMode(false);
      process.stdin.unpipe(stream);
       // End connectionclient.end();
    });
  });
});

// Exec a command over sshconstcmd='pwd';
constclient=newClient();
client.on('ready', () => {
  client.exec(cmd, (err, stream) => {
    if (err) throw err;
    stream.pipe(process.stdout);
    stream.stderr.pipe(process.stderr);
    stream.on('close', () => {
      client.end();
      end();
    });
  });
});

The idea is to abstract it to allow the user to only type a single command like other shelljs commands.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub [https://github.com/shelljs/shelljs/issues/435#issuecomment-215650130]

**Comment by ariporad** [comment]
Hmm...
It seems like this might be better-suited as a module outside shelljs, with an API like this:
```javascript
var ssh = require('ssh');
ssh.connect({ host: '...', username: '...', password: '...'});
ssh.exec('rm -rf foo bar'); ssh.close();
```
Unless I'm missing something.

**Comment by leesei** [comment]
@MatthieuLemoine Right tool for the right job.
If you need to SSH to the server I recommend [Ansible](https://www.ansible.com/).

**Comment by ariporad** [comment]
Or, if we impliment #402, there might be a way to create a new shell instance over ssh:

```javascript
var shell = require('shelljs');

var remote = new shell.SSH({ host: '...', user: '...', password: '...' });
remote.rm('-rf', 'foo', 'bar');
remote.close();
```

**Comment by MatthieuLemoine** [comment]
@leesei Ansible is an automation tool. If I only want to execute a single command over ssh inside my shelljs script it seems a little overkill to use Ansible. In this case, i would spawn a childProcess if needed.

@ariporad  Sure it could be  done as an external module. But ssh is a very usual command, this is why I thought it could be implemented directly in shelljs.

**Comment by ariporad** [comment]
@MatthieuLemoine: Hmm... Currently, we only support built in UNIX commands in ShellJS, but I imagine if we every added external commands, we would definitely support SSH.

**Comment by sequoiar** [comment]
+1 run shelljs over ssh2

**Comment by nfischer** [comment]
We now have a modest plugin API, so if anyone wants to start this, please feel free :smile: I'll be happy to point you toward plugin API docs, since it's still in the works

**Comment by MatthieuLemoine** [comment]
I have implemented a ssh plugin for shelljs.
See [shelljs-plugin-ssh](https://github.com/MatthieuLemoine/shelljs-plugin-ssh).

This plugin supports executing a command and openning a live shell on a remote host.

```javascript
require('shelljs-plugin-ssh');

const HOST = 'user@localhost';

// Exec command over ssh
const { out, error } = ssh(HOST, 'ls -l');

// Setup a live shell on remote host
ssh(HOST);
```

**Comment by nfischer** [comment]
Closing this, since there's a plugin implemented

**Comment by dwiyatci** [comment]
@MatthieuLemoine I was just giving your [shelljs-plugin-ssh](https://www.npmjs.com/package/shelljs-plugin-ssh) a shot - not sure if it's still working correctly with the latest `shelljs` version as it always throws error mentioned in MatthieuLemoine/shelljs-plugin-ssh#2. Could you quickly confirm? Appreciate your work on this. 🙇

**Comment by MatthieuLemoine** [comment]
@dwiyatci The error you saw is a logging failure. Can you retry with v1.2.2 ?

**Comment by dwiyatci** [comment]
@MatthieuLemoine Here are the results:

```javascript
shell.ssh(host);
// throws "Invalid usernameError: Invalid username"

shell.ssh(host, { username: 'glenn' });
// OK. works like a charm

const { out, error } = shell.ssh(host, 'ls -l');
console.log(error);
// throws the infamous ""chunk" argument must be one of type string or Buffer" like before

const { out, error } = shell.ssh(host, 'ls -l', { username: 'glenn' });
console.log(out);
// OK. works like a charm
```

I think in general the plugin still works fine, it's just the matter of the docs (of the plugin) that needs to be improved, thank you. =)

**Comment by MatthieuLemoine** [comment]
Yes the problem is the logger. I should have used the good old console.log instead 😄

**Comment by wmertens** [comment]
I just had this thought so I'm just writing it here: How about implementing the ssh by calling shelljs on the remote? This requires Node on the remote of course, but it would greatly improve the reliability versus calling ssh.

There's [node-ssh](https://github.com/steelbrain/node-ssh#readme) which provides a native, and then the api could look like this:

```js
const rsh = await shell.ssh(ssh2ConnectOptions) 
const files = await rsh.ls('**/*.js')
if ((await rsh.exec('echo hello')).code) throw "argh"
await rsh.cat('*.txt').toRemote('combined.txt')
rsh.dispose()
```

So the advantage would be that shelljs has access to the real data on the remote, and not just strings, and the result of exec etc can be transformed to ShellString which is nice to work with.

I can't think of a way to make the async functions sync though.
