### ISSUE TITLE
got some problem using `exec`

### ISSUE THREAD

**Issue by CocaCola183** [shelljs/shelljs#442]
### Example ShellJS command to reproduce the error:

1. `exec('cd /var/log').code == 0`, but can cwd not changed  
2. 
    *  `exec('ls /var/log/nginx/{hello.,}example.com_access.log')` // show no such file or dictory but     `ls('/var/log/nginx/{hello.,}example.com_access.log')` can list all  
    *   `exec('ls /var/log/nginx/*.example.com_access.log')` can list all too

**Comment by ariporad** [comment]
Hi,

We actually don't support `exec('cd')`, because exec spawns a subprocess, and there's no way for a subprocess to change the parent's working directory. But cd does work.

I'm going to close this, but feel free to reopen if I've misunderstood.

**Comment by nfischer** [comment]
The reason ls does not work is because exec spawns a`sh` shell, not a `bash` shell. Use the `{shell: "path/to/bash"}` option to get full bash expansion.

I'll clarify this in the docs.

In general, if we offer a shelljs function for a specific command, we recommend using that instead of `exec`.

**Comment by CocaCola183** [comment]
@ariporad @nfischer Thanks for your reply!
`{shell: "path/to/bash"}` helped me
