### ISSUE TITLE
Usage with neodoc

### ISSUE THREAD

**Issue by felixSchl** [shelljs/shelljs#445]
Hey, I am the author of [neodoc](http://felixschl.github.io/neodoc) which provides a way to generate a CLI parser from the utility's help text. I feel these two projects go hand in hand really, really nicely as naturally when writing a script, you might want to expose a CLI but not add loads of boilerplate. With neodoc you add your help text like you would in a bash script &mdash; The helptext is then transformed into a parser that parses and validates user input. You can [play with it online](http://felixschl.github.io/neodoc) or [check out the examples](https://github.com/felixSchl/neodoc/tree/development/examples) which actually use shelljs :). Neodoc is still flying under the radar currently, so I was hoping to raise some attention to it and gather some feedback as to how you would use it in conjunction with shelljs.  Please do close this issue if you feel this out of place, not justified or idk. Otherwise, I'd love to get your feedback especially around how you'd use it with shelljs and what improvements and new features you'd like to see to improve the experience more.

**Comment by ariporad** [comment]
Hi @felixSchl!

@shelljs/contributors: What are your thoughts on this? Neodoc looks quite cool, but we don't really do ver y much arguments parsing, so I don't know if it would be useful.

**Comment by nfischer** [comment]
I'll take a look, thanks!

**Comment by nfischer** [comment]
Closing this, since it probably isn't what we want for this project. Thanks!
