### ISSUE TITLE
shell.js grep: internal error,  Invalid regular expression

### ISSUE THREAD

**Issue by noteon** [shelljs/shelljs#447]
### Description of the bug: 

```
shell.js: internal error
SyntaxError: Invalid regular expression: /*.js/: Nothing to repeat
```

### Example ShellJS command to reproduce the error:

```javascript
shelljs.ls().grep("*.js")
```

**Comment by nfischer** [comment]
I believe this is the expected behavior. This regex looks to be invalid. I think the regex you're looking for is `grep(/.*\.js/)`. Note, `grep()`'s first argument should always be a regex, not a glob pattern to match files.

Please correct me if I've misunderstood. Cheers!

**Comment by noteon** [comment]
You can try the following example, it works. The first param is not regex, it is string. If you want to the first param is always string. you need to add some guard code.

shelljs.echo("mytest").grep("my");//result: mytest

**Comment by nfischer** [comment]
The first parameter should be a regex. You can specify it either as a JS string or as a JS regex, but either way it should conform to regex syntax. This was to maintain consistent behavior. The only difference should be a matter of number of backslashes you need to escape. Hope this clarifies the confusion!

Your example is definitely correct. It should be identical in behavior to `shelljs.echo("mytest").grep(/my/);`, and that's the output I would expect. Hope this helps!
