### ISSUE TITLE
how can i run sudo apt-get install xtodotool by your plugin?

### ISSUE THREAD

**Issue by himanshuoodles** [shelljs/shelljs#448]
### Example ShellJS command to reproduce the error:

```javascript

```

**Comment by nfischer** [comment]
```javascript
// in install.js
require('shelljs').exec('apt-get install -y xtodotool');
```

```bash
$ # at your shell prompt
$ sudo node install.js
```

If this doesn't help, please ping this thread again. Otherwise, feel free to close this issue. Cheers!

**Comment by himanshuoodles** [comment]
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

**Comment by himanshuoodles** [comment]
is there is any way i can install this type of software from node script in ubuntu

**Comment by nfischer** [comment]
^ Make sure you launch node with `sudo`. This works for me when I do that.

**Comment by nfischer** [comment]
@himanshuoodles is this still an issue for you, or has this been solved?

**Comment by himanshuoodles** [comment]
NO , i think running with sudo would work. I will tell when i will make its executable . You can close it.

**Comment by nfischer** [comment]
Ok great! Please ping this thread if the issue comes back.
