### ISSUE TITLE
Parameters for shell option

### ISSUE THREAD

**Issue by sobi3ch** [shelljs/shelljs#462]
I didn't know where to ask this question so I did it here. I know I can .exec() with different shell using something like this `{shell: '/bin/bash'}`. But is it possible to run certain shell with options like `/bin/bash -i`. 
This doesn't work obviously `{shell: '/bin/bash -i'}`

**Comment by nfischer** [comment]
We support whatever's available [here](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback).

From the looks of it, I'd say that options are not supported.

**Comment by nfischer** [comment]
I'm going to close this, since it isn't something we have control over at ShellJS (based on how things are implemented). Feel free to reopen this if you still need answers. Cheers!
