### ISSUE TITLE
`cp` work incorrectly when folder name contains '@'

### ISSUE THREAD

**Issue by s-panferov** [shelljs/shelljs#463]
### Node version:

node -v
v4.2.6

### ShellJS version:

0.7.0

### Operating system:

OSX 10.11.5

### Description of the bug:

My structure
```
build
  /node_modules
    /@folder
    /another-folder
```

When I write `cp build/* other/`, only `@folder` copied from `node_modules`, but `another-folder` doesn't. It works correctly when I remove `@` from the name.

Please note that '@' is default symbol for namespaces in `npm`.

**Comment by nfischer** [comment]
@s-panferov `cp build/* other/` shouldn't be supported. You can't copy directories unless you use `-r`.

I just tried this out, and could not reproduce the bug on Ubuntu.

```bash
$ tree # before running the command
.
└── build
    └── node_modules
        ├── another-folder
        │   └── bar
        └── @folder
            └── foo
```

```javascript
> // in NodeJS, in either version v4.2.4 or v6.0.0
> require('shelljs/global'); // shelljs v0.7
> cp('-r', 'build/', 'other/');
```

```bash
$ tree # after running the command
.
├── build
│   └── node_modules
│       ├── another-folder
│       │   └── bar
│       └── @folder
│           └── foo
└── other
    └── node_modules
        ├── another-folder
        │   └── bar
        └── @folder
            └── foo
```

@s-panferov Does this behave differently for you, or am I misunderstanding?

**Comment by s-panferov** [comment]
@nfischer yes, sorry, we use `-r`. I can't reproduce this on the minimal example too, I'll try to make some experiments.

**Comment by nfischer** [comment]
Sounds good :+1:

**Comment by nfischer** [comment]
@s-panferov any luck trying to reproduce this?

**Comment by s-panferov** [comment]
@nfischer no, this can be closed
