### ISSUE TITLE
Don't kill the node process upon unexpected error

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#483]
#64 and #473 are examples of complaints about this.

Currently, ShellJS will [kill the process]() if it encounters an unexpected ("internal") error. Ideally, the commands should all catch these before they arise, but since nothing is ever perfect so sometimes utilities fail for various reasons (permissions errors are a big reason).

It'd be great if ShellJS threw an exception instead of killing the process, since this would at least allow users the chance to catch the exception in their code. If the exception is left uncaught at the top-level, this would kill the process anyway as it currently does. This could have significantly different behavior if thrown inside of a try-catch, however, so this would be a breaking change.

**Comment by ariporad** [comment]
I agree... I'm not sure why we ever started killing the process.

One thing though is that it might make sense to change the error's `.stack` property, to make it somewhat more useful... I'm not sure exactly what form this would take, but getting a stack trace to some shelljs error handler isn't likely to be that useful.

**Comment by nfischer** [comment]
@ariporad Do you want to take this on? I imagine we'll just want to keep whatever the stack is from before, and maybe also add in a message like "ShellJS internal error" on the top of the stack trace.

**Comment by nfischer** [comment]
Fixed on `dev` branch
