### ISSUE TITLE
Error ENOTEMPTY when deleting a directory recursively.

### ISSUE THREAD

**Issue by rmariuzzo** [shelljs/shelljs#49]
Sometimes, when deleting a directory that has sub-directories and files it throw an error witch code: `ENOTEMPTY`.

When executing this: `rm('-rf', '/path/to/build/zip')` the following error is thrown:

> rm: could not remove directory (code ENOTEMPTY): build/zip/vendors/bootstrap

Note: It can happen with any sub-directory, is not related to a particular directory only. It doesn't happens with files.

**Comment by andreialecu** [comment]
+1 Seem to be getting the same error here on Windows occasionally. It's annoying becuase I'm running a pretty big test suite and the tests randomly fail because of this and I need to restart it every time until it eventually works.

**Comment by andreialecu** [comment]
I have changed the code block at https://github.com/arturadib/shelljs/blob/master/src/rm.js#L49 with this:

```
  var result, files;
  try {
    files = fs.readdirSync(dir);
    result = fs.rmdirSync(dir);
  } catch(e) {
    common.error('could not remove directory (code '+e.code+'): ' + dir, true);
    if (e.code == "ENOTEMPTY") {
      common.error('files found: ' + files.join(', '));
    }
```

And I can indeed see that there are some files left behind sometimes, randomly.

**Comment by andreialecu** [comment]
I think the only way to fix this on Windows is to auto-retry. I have found a library that doing exactly this here:
https://github.com/isaacs/rimraf

**Comment by andreialecu** [comment]
I made a pull request for this that auto-retries for up to 1 second on Windows. See #179

**Comment by nfischer** [comment]
Closing this since #179 is merged. Please reopen if this error persists

**Comment by dpmott** [comment]
For me, shx version 0.3.2 exhibits this same intermittent behavior when run from an npm script from within VSCode; when it fails, it fails immediately (no waiting for up to 1 second).  It would appear that the changes from https://github.com/shelljs/shelljs/pull/179 may have been lost.

**Comment by nfischer** [comment]
I still see the changes:

https://github.com/shelljs/shelljs/blob/4e38240eda2f377e2219f61dcf53e8f9bff74c0a/src/rm.js#L53-L78

I don't know enough about this problem to know if the bug still exists though.
