### ISSUE TITLE
Wrong method signature in doc

### ISSUE THREAD

**Issue by charlesread** [shelljs/shelljs#498]
The doc for `head` says that the method is:

```head([{'-n', <num>},] file [, file ...])```

But it should be:

```head([{'-n': <num>},] file [, file ...])```

(colon in options object)

**Comment by nfischer** [comment]
@charlesread thanks for pointing this out! Would you be able to submit a PR for this? You can make the necessary changes in `src/head.js` and `src/tail.js`, and then run `npm run gendocs` to update the README
