### ISSUE TITLE
100% cpu usage when a nodejs script goes side ways executing a command.

### ISSUE THREAD

**Issue by celer** [shelljs/shelljs#5]
Hi,

First thanks for writing ShellJS, so we've noticed in our project that somtimes shellJS consumes 100% cpu resources when something goes wrong with exec. 

i.e. 

exec("mysql -u testUser testDB < test.sql") 

will sometimes hang, leaving us with 100% cpu utilization on the shellJS parent process.

**Comment by mattheworiordan** [comment]
I have the same issue, the sync version causes very high CPU utilisation.

**Comment by mandb** [comment]
same issue, just doing this as fast as possible:

stat("/tmp/shelljs_f96bb1d9c47d577da6b2", 0x7ffff928b908) = -1 ENOENT (No such file or directory)
open("/tmp/shelljs_a75e65249275e587da3a", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 49
pwrite(49, "a", 1, 0)                   = 1
close(49)                               = 0
stat("/tmp/shelljs_f96bb1d9c47d577da6b2", 0x7ffff928b908) = -1 ENOENT (No such file or directory)
open("/tmp/shelljs_a75e65249275e587da3a", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 49
pwrite(49, "a", 1, 0)                   = 1
close(49)                               = 0
stat("/tmp/shelljs_f96bb1d9c47d577da6b2", 0x7ffff928b908) = -1 ENOENT (No such file or directory)
open("/tmp/shelljs_a75e65249275e587da3a", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 49
pwrite(49, "a", 1, 0)                   = 1
close(49)                               = 0

**Comment by nfischer** [comment]
Closing this, since I don't think this is an issue anymore with the current implementation of `exec()`.
