### ISSUE TITLE
how to silently write to a file?

### ISSUE THREAD

**Issue by ccorcos** [shelljs/shelljs#501]
when I run `echo('something').to('output.txt')`, the test is echoed to the console even when `shell.config.silent = false`. It would be great if there was a way to silently write to a file...

**Comment by nfischer** [comment]
Hi @ccorcos! The way we're doing this right now is with `shell.ShellString('something\n').to('output.txt')`.

Hope this helps! If this workaround is sufficient, feel free to close this issue :smile: (or let us know if you can think of a good way to put this in the docs).

**Comment by brillout** [comment]
👍 
Although a note in the readme would have saved me 30 minutes

**Comment by nfischer** [comment]
@brillout would you be able to submit a pull request? I'd gladly take a look.

**Comment by brillout** [comment]
An example like the following would have helped me
```js
ShellString('input text').to('output.txt');
```

**Comment by nfischer** [comment]
@brillout could you open a new pull request for the change?
