### ISSUE TITLE
exclude .idea from npm package

### ISSUE THREAD

**Issue by TrySound** [shelljs/shelljs#505]
### ShellJS version (the most recent version/Github branch you see the bug on):
0.6.0, but I see nothing is changed here.

### Description of the bug:
Too big npm package.

Cheers.

**Comment by ariporad** [comment]
Hi @TrySound,

I'm not sure what you're talking about. There's no `.idea` in our repo, and both me and @nfischer (the only people who regularly commit to the repo, or do releases) use vim.

I'm going to close this, but please feel free to re-open if I've misunderstood the question or if you're still having the issue.

**Comment by TrySound** [comment]
@ariporad Oh, it was not published with 0.7.3. But it was in 0.6.0. Sorry, didn't check.

**Comment by nfischer** [comment]
@TrySound I'll take a look at v0.6.0.

**Comment by nfischer** [comment]
@TrySound This is fixed in v0.6.1 :smile:

**Comment by TrySound** [comment]
Cool! Thanks!

**Comment by nfischer** [comment]
@TrySound Although it'd be awesome if you could update to v0.7.3 :smile:

**Comment by TrySound** [comment]
It's not me.
https://github.com/eslint/eslint/blob/master/package.json#L65
