### ISSUE TITLE
Sed should allow a replacement string to contain `\1` for match groups

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#507]
Sed should accept replacement strings that contain `\1` and `\2` and the like, for the sake of doing replacements. Currently, this is probably supported by `$1`, `$2`, etc. (but that's JS-syntax, not Unix-syntax).

``` js
sed(/my(.*)regex$/, '\\1 works', 'file.txt');
// probably the closest we can get to Unix sed's syntax without a breaking change:
// sed 's/my.*regex$/\1 works/' file.txt
```

This ties in closely with `shx sed`, since it doesn't currently support substitutions like this.

**Comment by nfischer** [comment]
After thinking about this a bit, it's probably best to leave this as a won't fix (the `$1` syntax is good enough). That means we should open issues against [shx](https://github.com/shelljs/shx) and [shelljs-transpiler](https://github.com/nfischer/shelljs-transpiler) to accommodate this.

@freitagbr thoughts?

**Comment by freitagbr** [comment]
Agreed, let's open duplicate issues for this in the other projects. We should maybe add an example of using the `$1` syntax to the documentation.

**Comment by nfischer** [comment]
Do you want to take on the documentation here?

**Comment by freitagbr** [comment]
Sure, I can do that.
