### ISSUE TITLE
`exec` gets stuck on my Debian box

### ISSUE THREAD

**Issue by protz** [shelljs/shelljs#51]
```
protzenk@sauternes:pdfjs ((a68e11c...)) $ nodejs
> require("shelljs/global")
{}
> exec("ls")
```

Then, the nodejs process gets stuck and the only way I can get out of this is to run `pkill nodejs` in another terminal. Any ideas what might be causing this? I've installed nodejs as a Debian package, and I've also run "npm install shelljs" hoping that it would upgrade me to the latest version.

Thanks,

jonathan

**Comment by nfischer** [comment]
@protz @parasyte @infracanophile Sorry for the delay! Any luck on this? Does the issue persist in shelljs `v0.6`? If so, which versions of node are you seeing the issue on?

**Comment by parasyte** [comment]
@nfischer I have already rewritten my shelljs calls to run asynchronously, and chained them with promises. I could experiment with reverting that.

**Comment by nfischer** [comment]
@parasyte thanks!

**Comment by nfischer** [comment]
Closing this, due to lack of inactivity. If this is still an issue, please ping this thread.
