### ISSUE TITLE
Exec issues with string option introduced in 0.7.4

### ISSUE THREAD

**Issue by shaunwarman** [shelljs/shelljs#515]
### Node version (or tell us if you're using electron or some other framework):
4.5.0

### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.4

### Operating system:
OS X

### Description of the bug:
Oddly, 0.7.4 throws [internal error](https://github.com/shelljs/shelljs/blob/master/src/exec.js#L267) when using String options in exec call. For some reason this was working in previous versions, but recent change in 0.7.4 alters the behavior to accept a string option. After changing to the expected signature of object it works as it should. But it's interesting to know why this worked as a string in previous versions? Did a commit from March sneak in to 0.7.4 that altered exec [functionality](https://github.com/shelljs/shelljs/commit/db20acebfb730ec66acdb7a046b1ba98665e88c0)? Or am I missing something in recent commits?

### Example ShellJS command to reproduce the error:

```javascript
var shelljs = require('shelljs');
shelljs.exec('hostname -f', 'silent');
```

**Comment by nfischer** [comment]
The following API has never been (to my knowledge) supported:

```js
shell.exec(cmd, 'silent');
```

If that ever worked, it was by pure luck.

We only aim to support this:

```js
shell.exec(cmd, { silent: true });
```

Are you saying that the unsupported API used to work, but is now broken? Or that the supported API no longer works in the recent version?

Also, what version are you comparing against? Is this a chance between 0.7.3 -> 0.7.4, or 0.6.x -> 0.7.x?

**Comment by shaunwarman** [comment]
0.7.3 -> 0.7.4.. oddly the string signature worked (even though it shouldn't have) and a change in 0.7.4 fixed that.
