### ISSUE TITLE
ShellJS in Electron package don't find ffmpeg anymore

### ISSUE THREAD

**Issue by StefMa** [shelljs/shelljs#516]
### Node version (or tell us if you're using electron or some other framework):
[Electron](https://github.com/electron/electron) version 1.3.4

### ShellJS version (the most recent version/Github branch you see the bug on):
Version 0.7.0

### Operating system:
OS X El Capitan 10.11.16

### Description of the bug:
I've created a small electron App which needs ffmpeg to convert a movie to a gif. Nothing special.
`ffmpeg` is installed via [homebrew](https://github.com/Homebrew/brew/)
```
brew install ffmpeg
```
When I run my electron app local (without packaging) everything worked like expected.
But when I package my app with the [electron-packager](https://github.com/electron-userland/electron-packager) shelljs can't find `ffmpeg` anymore. The `code` is then `127` instead of `0` :(
Because your current documentation said that it run in `sh` I've checked it here if `ffmpeg` is missing. But the terminal output looks like this:
```
$ /bin/sh
sh-3.2$ which ffmpeg
/usr/local/bin/ffmpeg
```
I've also switched to `bash` with the option `shell` (see Example ShellJS command) but that doesn't help.

What I'm doing wrong? And why it's working without packaging but break with packaging?
Or isn't it an error in ShellJs? 💭 

### Example ShellJS command to reproduce the error:
I've als tested it with `shell: '/bin/sh'` and `shell: '/bin/bash'` nothing works.
```javascript
exec('ffmpeg -i ' + filenames[0] + ' ' + path, {silent:true, async:true},  function(code, stdout, stderr) {
    // Send error code to renderer to debug
    loadingWin.webContents.executeJavaScript('console.log(' + code + ')')
}
```

Don't know if this a related issue https://github.com/shelljs/shelljs/issues/480

**Comment by nfischer** [comment]
@StefMa currently, shelljs does not support electron. We're working to fix this. A previous version should work, as long as you have NodeJS installed separately under the name `node`.

**Comment by StefMa** [comment]
Hmm sad to hear :(
Is there any workaround?
Maybe with `child_process` or something like that?
I've tried with 
```javascript
var execS = require('child_process').exec
var child = execS('ffmpeg -i ' + filenames[0] + ' ' + path, (error, stdout, stderr) => {
  // ToDo something with the gif
}
```
but on the packaged electron App it will raise a error that there isn't a gif available :(

**Comment by StefMa** [comment]
It looks like it is a problem with the `PATH`.
Because I always got the error code 127 which means `process not found`.

So I'm not able to add all the `PATH`es user have set. 
I'm using know the full path to ffmpeg.
The code looks like this and is working:
```javascript
exec('/usr/local/bin/ffmpeg -i ' + filenames[0] + ' ' + path, {silent:true, async:true},  function(code, stdout, stderr) {
    // Send error code to renderer to debug
    loadingWin.webContents.executeJavaScript('console.log(' + code + ')')
}
```

**Comment by nfischer** [comment]
Can you launch any exec commands? I'm pretty sure exec is broken for electron

**Comment by nfischer** [comment]
If any exec commands work, then this is a different bug than I thought it was. Perhaps modifying `process.env.PATH` will help

**Comment by StefMa** [comment]
> Can you launch any exec commands? I'm pretty sure exec is broken for electron

Yes I can, I've no trouble with the versions I've mentioned with shelljs in general.
The only problem was the `127` error code.

Yes, thank you. I'll look into `process.env.PATH` :)

**Comment by StefMa** [comment]
I had looked into it and it seems that the problem is that macOS don't inherited the `$PATH`.
See https://git.io/viaFg, https://git.io/viaF2 and https://git.io/viaFa

I've fixed it in a better way then hardcoded `ffmpeg` path with the following lines:
```javascript
process.env['PATH'] = '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
```

**Comment by nfischer** [comment]
@StefMa Thanks for the follow-up. Sounds like Mac OS has a bug. Hopefully that gets fixed in the new version. I'm glad this worked for you.
