### ISSUE TITLE
The performance in `cp` is different between `0.6.0` and `0.7.4`

### ISSUE THREAD

**Issue by SidKwok** [shelljs/shelljs#517]
### Node version (or tell us if you're using electron or some other framework):
v6.2.0
### ShellJS version (the most recent version/Github branch you see the bug on):
0.6.0 and 0.7.4
### Operating system:
OS X 10.11.6
### Description of the bug:
The performance in `cp` is different between `0.6.0` and `0.7.4`
### Example ShellJS command to reproduce the error:

```javascript
// ./Users/Sid/Desktop/0.7.4/main.js
require('shelljs/global');
var path = require('path');
var assetsPath = '/Users/baidu/Desktop/0.7.4/newFolder';
rm('-rf', assetsPath);
mkdir('-p', assetsPath);
cp('-R', 'dontNeedToBeCopied/', assetsPath);

// ./Users/Sid/Desktop/0.6.0/main.js
require('shelljs/global');
var path = require('path');
var assetsPath = '/Users/baidu/Desktop/0.6.0/newFolder';
rm('-rf', assetsPath);
mkdir('-p', assetsPath);
cp('-R', 'dontNeedToBeCopied/', assetsPath);
```

after running:
0.6.0:
```
├── dontNeedToBeCopied                    
│      ├── needToBeCopied1.js             
│      └── needToBeCopied2.js    
├── newFolder  
│      └── dontNeedToBeCopied   
│                ├── needToBeCopied1.js      
│                ├── needToBeCopied2.js     
│
├── main.js
```

0.7.4:
```
├── dontNeedToBeCopied                    
│      ├── needToBeCopied1.js             
│      └── needToBeCopied2.js    
├── newFolder  
│        ├── needToBeCopied1.js      
│        ├── needToBeCopied2.js   
│
├── main.js
```

**Comment by nfischer** [comment]
This is a known change to get Unix compatibility. To get the old behavior, use `cp('dirname/*', 'newdir')`. If this is not compliant with UNIX, please let us know.

**Comment by nfischer** [comment]
I'll close this for now, but if there any further issues, please ping this thread and we can revisit it.

For what it's worth, I compiled a list of [migration guides](https://github.com/shelljs/shelljs/wiki/Breaking-Changes) that I *think* cover all the breaking changes. If you see one I missed, feel free to add it in there/clarify things for people in the future :smile:
