### ISSUE TITLE
How to send SIGINT signal to child process launched with exec

### ISSUE THREAD

**Issue by aalexgabi** [shelljs/shelljs#518]
I have something like this and I would like to kill child process with given signal:

```
shelljs.exec('istanbul my-daemon', {async: true});

// Tests here

// Once tests done send SIGINT to the child process
```

Is there a way to do this with ShellJS instead of native spawn?

**Comment by nfischer** [comment]
I think using the native `child_process.exec()` might be your best bet.

**Comment by freitagbr** [comment]
Closing this.

**Comment by HustLion** [comment]
You can save the process to a varaible and call `kill()` on it. No need to use native `child_process.exec()`.

```js
var child = exec('some_long_running_process', {async:true});
child.kill();
```

This works on macOS Sierra 10.12.4.

**Comment by lixplor** [comment]
Hi! Is it possible to explain more clearly? I would also like to know how to kill long-live child process.
I tried `child.exit(0);`, `child.kill();`, `child.kill('SIGINT');`, `shell.exec('kill ' + child.pid);`. But none of them works!
I'm running script on Debian and execute a `mplayer <url>` command on a child process.

**Comment by nfischer** [comment]
You'll want [`child_process.kill()`](https://nodejs.org/api/child_process.html#child_process_subprocess_kill_signal). To expand on @HustLion's example:

```js
// This script takes 3 seconds
var child_process = require('child_process');
var c = child_process.exec('sleep 3'); // async
```

```js
// This script exits much quicker
var child_process = require('child_process');
var c = child_process.exec('sleep 3'); // async
c.kill();
```

**Comment by lixplor** [comment]
So this means Shell.js cannot kill process, we must use original `child_process` module in Node.js to achieve this.
Thanks @nfischer

**Comment by nfischer** [comment]
> So this means Shell.js cannot kill process

Not true, but `shell.exec(... {async: true})` is a thin wrapper over `child_process.exec()`. If your goal is to run something async in the background, I would strongly recommend `child_process.execFile()` or `child_process.spawn()` for security reasons.

**Comment by xhkocatepe** [comment]
It does not clear for me. I will c.kill() and then c.killed return true, but app is running does not close.
App only close run exec or cmd ("taskkill /f ...") but I don't want to do this. 

Is there any way to forcebly close over child_process ?

**Comment by nebosite** [comment]
Doesn't work for me either.   This issue is forcing me to bypass shelljs and go directly to child_process so that I can kill the process later.   (I'm starting up a server, verifying it works, then stopping it)

**Comment by rez1shehni** [comment]
I solve this issue by kill process by name like this :
shell.exec(`Taskkill /F /IM python.exe`, {}, () => console.log('killed: ', Process.killed))

**Comment by olleharstedt** [comment]
This is still an issue, right? I'm also not able to `kill` a proxy server started with `php -S`

**Comment by nfischer** [comment]
Just want to clarify that we have no plans to support this. You are welcome to use `child_process.exec()` or a similar function if you need to kill a long-running process. Sorry if this isn't what you want to hear, but I think you have a clear alternative to meet your needs.

`shell.exec()` and `shell.cmd()` are intended for processes which have a finite runtime and which will finish on their own. If you run into issues which affect this use case, please file a bug.

**Comment by olleharstedt** [comment]
That's fine, but why even have the method `kill` in the interface if it does nothing? Throwing an exception would be nice, at least. It also confuses the LLMs..... 😶

**Comment by nfischer** [comment]
We just return the same object that `child_process.exec()` provides us. It has literally all of the same methods because it is the same object.

If `child.kill()` doesn't work the way you expect, then perhaps you're hitting this behavior:

> On Linux, child processes of child processes will not be terminated when attempting to kill their parent. This is likely to happen when running a new process in a shell or with the use of the shell option of ChildProcess

https://nodejs.org/api/child_process.html#subprocesskillsignal

`shell.exec()` is just a wrapper on top of `child_process.exec()`. Both of these use a POSIX shell under the hood to evaluate your command string. If you switch to one of the `child_process` functions that doesn't invoke an underlying shell, then maybe this will work the way you expect. Try `child_process.execFile()`.
