### ISSUE TITLE
Question: passing code via pipe?

### ISSUE THREAD

**Issue by amilajack** [shelljs/shelljs#520]
I'm using the following code to pass javascript source code (as a string) as stdout to anther command.
```js
exec(`echo "${jsCodeHere}" | someOtherCommand`)
```
The issue with this is there are a bunch of issues caused by the syntax of javascript being evaluated by bash. Is there a better way of doing this?

**Comment by nfischer** [comment]
Did you look into our support for pipes? The built-in `echo` should treat text normally, and then you can pipe it via `echo(code).exec(cmd)`. Let me know if this helps!

You can also use the `ShellString` constructor and it'll be like echo, except it won't print to stdout.

**Comment by amilajack** [comment]
This worked perfectly! Thanks!

**Comment by amilajack** [comment]
It seems like `echo(code).exec(cmd)` doesn't support the `{ silent: true }` option. Does it?

**Comment by nfischer** [comment]
Exec should. Echo does not support it yet (but I can add support)

**Comment by amilajack** [comment]
So adding support will suppress the output but still pass it to exec?

**Comment by nfischer** [comment]
For now, the recommended workaround is `(new shell.ShellString("text you don't want to print to the console")).exec(cmd)`.

But I'll probably write something up that's more intuitive, since we get this issue a lot. If that works for you, feel free to close this issue (we have some other issues related to this, see #146 and #501).

**Comment by ariporad** [comment]
@nfischer: Suggestion (and I'm happy to open a PR for this): we could make a `shell.pipe(str)` method, that does this:

```javascript
shell.pipe = function (str) {
    return new shell.ShellString(str);
}
```
