### ISSUE TITLE
FS Real Path error thrown when requiring shelljs

### ISSUE THREAD

**Issue by smks** [shelljs/shelljs#521]
### Node version (or tell us if you're using electron or some other framework):
Node - v4.5.0
NPM - 2.15.9

### ShellJS version (the most recent version/Github branch you see the bug on):
^0.7.4

### Operating system:
Mac OSX El Capitan

### Description of the bug:
I have a post install script that requires shelljs - I cloned the repository and then run npm install. The script fails when I require shelljs with an issue about node's global fs. When I remove the require to shelljs, it does not throw an error.

### Example ShellJS command to reproduce the error:

```javascript
#! /usr/bin/env node

/*jshint esversion: 6, node: true */
"use strict";

const shell = require("shelljs");
```

```module.js:327
    throw err;
    ^

Error: Cannot find module 'fs.realpath'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)`
```

**Comment by ariporad** [comment]
@smks: Was this resolved?

**Comment by smks** [comment]
When I recursively removed the node modules folder and then run again it worked. I'm guessing something went wrong with the install of dependencies.
