### ISSUE TITLE
API request: allow `plugin.error()` to take an options parameter

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#522]
The current API for `plugin.error`/`common.error` is this:

```js
common.error(message, code, _continue);
```

This API has been good enough for us, but we may want to modify it to take an options parameter for more flexibility:

```js
common.error(message, options);
```

We would migrate `continue` and `code` into the options (`code` already defaults to 1 and `continue` defaults to false).

**Comment by ariporad** [comment]
I support having an options object, but I think that we should make the signature `common.error(message [, code] [, options])`;

**Comment by nfischer** [comment]
I thought about that as well. The issue is that sometimes you might want the default error code while also wanting to specify an option.
