### ISSUE TITLE
Add -u flag support for cp

### ISSUE THREAD

**Issue by ilja903** [shelljs/shelljs#526]
Hello!

It would be great if someone could add -u flag support for cp command.

Right now output for shx is following:

cp: option not recognized: u

Thanks in advance.

**Comment by nfischer** [comment]
Anyone can take this issue up if they've got time. It doesn't look too bad to implement and test (`touch()` utility could be helpful during tests). From the Linux man page:

> ```
> -u, --update
>   copy only when the SOURCE file is newer than the destination file or when the destina‐
>   tion file is missing
> ```
