### ISSUE TITLE
exec won't pass return code to callback when used with async.js

### ISSUE THREAD

**Issue by kstratis** [shelljs/shelljs#528]
Hi,

I'm using **NodeJS v6.8** with **ShellJS v0.7.4 (npm)** on a MacbookPro 13' running **macOS Sierra**.
The problem using **[AsyncJS v2.1.1](https://github.com/caolan/async)** to run an external git command through `exec` is the following:

```javascript
var shell = require('shelljs');
var waterfall = require('async/waterfall');

waterfall([
  function(callback) {
    shell.exec('git clone ssh://git@github.com/kstratis/Spoon-Knife /Users/kstratis/Documents/myrepos/', 
    {silent:false, async:true}, 
    callback);
  },
  function(code, stdout, stderr, callback) {
    console.log('The code is: ' + code);
    console.log('stdout is: ' + stdout);
    console.log('stderr is: ' + stderr);
    callback(null, 'completed');
  }], function (err, msg) {
        if (err) throw err;
        console.log('All tasks successfully' + msg);
      });
```

* `code` is **always** an empty value
* `stdout` is `stdout`
* no `stderr`. In its place is the callback function as parameter.

Any help? 
Thanks.

**Comment by megawac** [comment]
from gitter

> `waterfall` expects the callbacks of tasks to be called in the form `(err, ...results)` however, it looks like it's being called like `(code, stdout, stderr)`. Therefore, waterfall will always error. You are going to have to wrap the call to that callback to be consumed by `async.waterfall`

**Comment by ariporad** [comment]
Yep

**Comment by ariporad** [comment]
Yep, exactly what @megawac said... ShellJS calls the callback incorrectly. Based off that, I'm going to close this, but feel free to reopen if I've misunderstood.
