### ISSUE TITLE
Inadvertent breaking change to shell.test()

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#529]
See the discussion in #492 

`shell.test()` used to not perform shell globbing (it's not usually something you would want in this scenario). The above-mentioned PR accidentally introduced globbing to the command, which could break things for some users.

If anyone can examine that PR and figure out all behavior changes, feel free to submit a PR for this.

**Comment by gyandeeps** [comment]
Thanks for this. I can do the work if you want.

**Comment by nfischer** [comment]
@gyandeeps that would be awesome! As I see it, all we need to do is add the option for no-globbing to the `test()` command any others that I similarly missed in the refactor. I'll add unit tests later to prevent a similar regression for those specific commands.

**Comment by gyandeeps** [comment]
awesome... thats whay i thought by looking at the code
will send a PR shortly. Will try to add some test
