### ISSUE TITLE
Project objectives: there is some higher goal to achieve?

### ISSUE THREAD

**Issue by reinaldorauch** [shelljs/shelljs#533]
Hi'all

There is some higher goal to the project to achieve? Like 100% of interface compatibility with unix/posix commands? (Something like node is doing with fs and unix system calls) or such thing?

It would help to community where to put efforts.

Thanks in advice.

**Comment by nfischer** [comment]
Just added this: https://github.com/shelljs/shelljs/wiki/Roadmap

@ariporad please take a look, feel free to move things around, edit, and add. This should be most of what we discussed on the dev-team gitter. Let me know if I've missed anything or you've thought of something.

**Comment by nfischer** [comment]
Closing this, since the roadmap has been posted. If there's any further discussion, ping this thread or put suggestions on the Roadmap.
