### ISSUE TITLE
Can we run multiple `exec` concurrently?

### ISSUE THREAD

**Issue by ccorcos** [shelljs/shelljs#562]
It would be awesome if we could run multiple `exec` concurrently.

Maybe it would work something like this:

```js
shell.map(['a', 'b'], x => shell.exec(`cd ${x}; ls`))
```

That would be AWESOME!

**Comment by nfischer** [comment]
I believe you can two *async* execs concurrently without issue. I have not tried this myself.

```js
shell.map(['a', 'b'], x => shell.exec(`cd ${x}; ls`, { async: true }));
```

@ccorcos does this do what you had in mind?

**Comment by ccorcos** [comment]
I see. Interesting. And gathering all the results would involve wrapping things into a promise and using `Promise.all`...

**Comment by nfischer** [comment]
It sounds to me like you've figured out a suitable alternative. I'm closing this, since it doesn't seem like it's really specific to ShellJS. Please reopen if you feel like there's an easy way to do this in the shell that you think ShellJS should offer.
