### ISSUE TITLE
write to file

### ISSUE THREAD

**Issue by ccorcos** [shelljs/shelljs#568]
Any interest in adding this to the core api?

```js
const write = (file, contents) => {
  new shell.ShellString(contents).to(file)
}
```

**Comment by nfischer** [comment]
@ccorcos is there a unix `write` command with similar semantics? If there's a standard command, I would have no issues with adding that. Otherwise, feel free to implement this as a [plugin](https://github.com/shelljs/shelljs/wiki/Using-ShellJS-Plugins) if you think others can benefit

**Comment by ccorcos** [comment]
ah I see. only want to support unix commands here?

**Comment by nfischer** [comment]
Yeah, that's the idea. We have some non-unix commands, but we're trying to phase them out with unix-y alternatives.

**Comment by ccorcos** [comment]
I see. Although idk if we should look to unix as the gold standard. There
are some many weird quirks like using cat to read a file, lol

**Comment by nfischer** [comment]
I agree that Unix is very quirky. I can personally never remember the order of arguments sometimes, or find myself forgetting the occasional `-r`. Nonetheless, Unix is very well standardized, and many people have exposure to it. In the past, we've had issues where users expect Unix behavior and are surprised at the differences
