### ISSUE TITLE
&& and & and || operators

### ISSUE THREAD

**Issue by tomdavidson** [shelljs/shelljs#583]
Does shx support &&, &, and || - I do not have windows to check it out?

```js
"test": "shx test1 && test2",
"serve": "shx star-dev-server &",
"deploy": "shx deploy.sh || rollback.sh"
```

**Comment by nfischer** [comment]
@tomdavidson `&&` and `||` are both supported on Windows. I don't think `&` is. These are currently outside of the scope of shelljs and shx though, I'm afraid.

Closing this, but feel free to ping me if I didn't fully answer your question.
