### ISSUE TITLE
pushd, popd, and dirs need to use full paths

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#584]
So apparently no one ever tested `pushd`, `popd`, and `dirs` properly. These should always return lists of *absolute* directory paths, abbreviating the home directory as `~`.

I've been rewriting the tests, and they're nowhere close to being correct...

Either we should seriously consider fixing these commands before v0.8, or we should deprecate them immediately.

@freitagbr thoughts?

**Comment by freitagbr** [comment]
I agree, let's fix this for v0.8. We should leave a note in the documentation about this behavior for versions below v0.8.

**Comment by nfischer** [comment]
I'll let you fix this, then. I don't find these functions particularly useful for scripting

**Comment by freitagbr** [comment]
For clarification, is the lack of abbreviating the homedir as `~` the only thing that needs to be fixed? These methods seem to use full paths already.

**Comment by nfischer** [comment]
Huh, could've sworn the paths weren't full. I guess I must've been mistaken. It's fine to leave the `~` alone, let's mark as won't fix.
