### ISSUE TITLE
rm -rf on a symbolic link to a dir deletes its contents

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#587]
Currently, ShellJS differs from the unix implementation. I added a test in #586 (currently being skipped) to cover this. Once that's merged, we should write a fix for this.

blocked by #586

**Comment by nfischer** [comment]
No longer blocked. Anyone can take this up.

**Comment by freitagbr** [comment]
I believe this was fixed in #598.

**Comment by freitagbr** [comment]
Is the expected unix behavior that only the symlink is deleted, and not the contents on the linked directory?

**Comment by nfischer** [comment]
No, I believe it should be the opposite actually. See [this test](https://github.com/shelljs/shelljs/pull/586/files#diff-d8a9f9ae97d75f6a7009af716e50b867R264)

**Comment by freitagbr** [comment]
On macOS, rm -ref on a die symlink simply deletes the symlink. Can you test on linux?

**Comment by nfischer** [comment]
@freitagbr 

```bash
$ ln -s mylink realdir
$ ls realdir/ # has stuff
$ ls mylink/ # has same stuff
$ rm -rf mylink # no trailing slash = remove the link
$ ls mylink # gone
$ ln -s mylink realdir
$ rm -rf mylink/ # with a trailing slash = delete the contents, keep mylink, and keep realdir
$ ls -d mylink realdir # still here
$ ls realdir # all contents are removed
```

Also, `rm` has no `-e` on Linux (maybe that was a typo?)
