### ISSUE TITLE
[Question] commands with multiple options / arguments?

### ISSUE THREAD

**Issue by bmcgonag** [shelljs/shelljs#589]
I just want to know how to setup a command that has multiple options with an argument for each as shown below.  You samples don't really cover this.

Thanks,

### Node version (or tell us if you're using electron or some other framework):
node 4.5.0 

### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.5
added through meteor npm install shelljs --save

### Operating system:
Linux / Mac

### Description of the bug:
Not a bug - just a question

### Example ShellJS command to reproduce the error:
mongodump -h localhost --port 3001 -d meteor

```javascript

```

**Comment by nfischer** [comment]
You should be able to use `exec()` for this, right? Just pass the whole command in, as you would type it in the shell

**Comment by bmcgonag** [comment]
trying that, but getting an error back 

`exec: internal error`

Not sure why.  I can run this command on the command line with no issue.  Does the command have to be in single or couble quotes within the parentheses?  I'll try that, play around a bit, and see what I can get going.  I appreciate the quick response.

**Comment by bmcgonag** [comment]
I got it...i'm an idiot...wasn't running it on the server - my bad.  Fixed and working...this is an awesome project.  I can do all kinds of great stuff with this!  You guys rock.

**Comment by nfischer** [comment]
Glad it worked for you 😊
