### ISSUE TITLE
Redirect output to file fails

### ISSUE THREAD

**Issue by getdave** [shelljs/shelljs#60]
When executing the following command directly on the cmd line the database is dumped to the file correctly.

When running the same command via ````.exec.```` using Grunt.js (see below) the output is in the console and the file is created but has no contents.

````
shell.exec('mysqldump -u my_user -pmy_pass test > test.sql');
````

My ultimate goal is to run a dump via ssh like so:

````
shell.exec("ssh user@host \ mysqldump -u my_user -pmy_pass test > test.sql");
````

**Comment by nfischer** [comment]
I tried out the following code and saw the expected results:

```
$ cat sample.js
require('shelljs/global');
exec('echo hi > mytempfile.txt');
$ shjs sample.js
$ cat mytempfile.txt
hi
```

@getdave @c0bra Do either of you see different behavior using my example? To me this doesn't seem like a shelljs issue.

**Comment by vejersele** [comment]
@nfischer we just encountered this issue on Linux, while it was working perfectly fine locally on my mac ... Might be OS related then I guess.

OS : Ubuntu 14.04.3 LTS

**Comment by nfischer** [comment]
@vejersele Did you see the issue with my simple example above? I tested my example on Ubuntu 15.10 and it worked perfectly. If you can confirm that simple examples like above aren't working for you, then I can investigate further.

**Comment by nfischer** [comment]
@vejersele bumping this thread. Could you provide the exact line of code that didn't work for you?

**Comment by nfischer** [comment]
I'm going to close this issue, since it doesn't seem like it's related to ShellJS. Please re-open if the issue persists.
