### ISSUE TITLE
Add support for other file types in rm

### ISSUE THREAD

**Issue by freitagbr** [shelljs/shelljs#617]
`rm` is only able to delete files, directories, and symbolic links. `fs.lstatSync` is able to detect several other file types, however:
```
stats.isBlockDevice()
stats.isCharacterDevice()
stats.isFIFO()
stats.isSocket()
```
Support for these file types should be added (at least for the ones it makes sense to run `rm` on).

**Comment by freitagbr** [comment]
Which of these does it make sense to implement `rm` for? I think it only makes sense for `fifo`s.

**Comment by nfischer** [comment]
It probably makes sense to remove fifos. If someone tries to `rm` the other devices, let's provide an error message (similar to when someone tries to `rm` a file they don't have permission for). If someone does need to `rm` these file types, they can easily file a bug for it.
