### ISSUE TITLE
rm -rf doesn't work if the directory contains an asar archive in Electron

### ISSUE THREAD

**Issue by tgds** [shelljs/shelljs#618]
### Node version (or tell us if you're using electron or some other framework):
electron v1.4.8
node v7.1.0

### ShellJS version (the most recent version/Github branch you see the bug on):
shelljs v.0.7.5

### Operating system:
macOS Sierra 10.12.1
Windows 8.1

### Description of the bug:
Getting `rm: could not remove file (code ENOTDIR)` errors when running recursive rm in Electron to remove a directory and the directory happens to contain an asar archive. 

I believe that this is caused by the fact that Electron patches fs [to treat asar files as virtual directories](https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md#node-api). Thus, ShellJS sees the .asar file as a directory and attempts to remove all individual files as given by fs.readdir('example.asar'). 

Monkey patching rm.js to require original-fs seems to solve it. 
I expected similar problems with cp -r, but doing a quick test that seems to work without issues.

Now, I am very new in the industry, so I'd need some guidance on crafting a good PR and discuss what makes the most sense to do here. Would checking if original-fs is available and using it in rm.js be the best solution, or should this be extended globally? Do you think this could potentially have some unwanted side effects or can think of a better solution? 

Thank you!

### Example ShellJS command to reproduce the error:

```javascript
// Somewhere in main or renderer Electron js
const shelljs = require('shelljs')
shelljs.rm('-rf', '/PathToADirectoryContainingAsarArchive')
```

**Comment by nfischer** [comment]
@tgds Thanks for reporting this!

This could be a tricky thing to fix. I'll need to learn more about electron and asar archives. We already have some issues with electron support (see #480), so we have quite a few things to work on.

Could you point me toward docs on original-fs? I'm assuming this is an electron-specific thing to copy over the real `fs` to a different package name.

**Comment by tgds** [comment]
@nfischer Thanks! Yeah, you're assuming correctly. It looks like it should be straightforward in the end. I should pay more attention when reading the [docs](https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md) next time. Looks like [this switch](https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md#treating-an-asar-archive-as-a-normal-file) should do it: 
```javascript
process.noAsar = true
``` 
Will test this and send a PR later on today, I hope. 

Potentially, I can imagine situations where you would like to have asar support optional in ShellJS in Electron. What do you think?

**Comment by nfischer** [comment]
I'm going to close this, since it's documented in [the wiki](https://github.com/shelljs/shelljs/wiki/Electron-compatibility)
