### ISSUE TITLE
Echo tests unnecessarily run tests in own process

### ISSUE THREAD

**Issue by freitagbr** [shelljs/shelljs#622]
To prevent writing to the process' own stdout, the `echo` tests were written to run each test in its own process, and the stdout of that process was captured. Because ava runs each test in its own process anyway, the `echo` tests no longer need to run in separate processes.

**Comment by nfischer** [comment]
Ava only runs tests in their own processes if running in parallel mode. Even still, I don't think it captures the stdio, I think it just goes straight through to the console, which isn't what we want.

We could do away with the stdout capturing if we mock `process.stdout` and `process.stderr`.

**Comment by nfischer** [comment]
@freitagbr ping. Any progress on this?

**Comment by freitagbr** [comment]
When I run the echo tests in concurrent mode, `echo` still prints to stdout. So, I think the best think to do in this situation would be to mock `process.stdout` and `process.stderr`. The [`std-mocks`](https://github.com/neoziro/std-mocks) module looks like it might be useful for this purpose.

**Comment by nfischer** [comment]
Yeah, that module seems fine

**Comment by nfischer** [comment]
I did something similar for shx [here](https://github.com/shelljs/shx/blob/master/test/mocks.js) and [here](https://github.com/shelljs/shx/blob/master/test/specs/cli.js#L19)

The downside to mocking like this is that we'll need to mock/restore within each test case (I don't think you can do it in setup/teardown). This is lots of boilerplate 😦 

An alternative approach is to refactor `echo()` to take a configurable stream. It's always `process.stdout` in production, but we can set it to some other stream for tests only. But maybe that's too Java-ish 😜

**Comment by freitagbr** [comment]
Fixed in #708
