### ISSUE TITLE
QUESTION: Feedback while an operation is running?

### ISSUE THREAD

**Issue by bmcgonag** [shelljs/shelljs#629]
### Node version (or tell us if you're using electron or some other framework):
6.x.x

### ShellJS version (the most recent version/Github branch you see the bug on):
Newest

### Operating system:
Ubuntu 16.04 Linux 64 bit

### Description of the bug:
No bug...just a question.

### Example ShellJS command to reproduce the error:
    shell.exec('rsync -avP ' + inputPath1 + ' ' + inputPath2, function(code, stdout, stderr){
        console.log(code);
        console.log(stdout);
        console.log(stderr);
    });

I know this is running, I can see it in the terminal, but I want to give feedback through the GUI that it's running.  Is there some way to know it's running.  I don't see any feedback in the console until the entire operation is complete, and depending on the size of a directory this could take a while.

```javascript

```

**Comment by freitagbr** [comment]
`shell.exec` doesn't expose an `EventEmitter` or `stream` interface, which is what I would want in your case. Instead, you can use the `child_process.spawn` from node core:
```js
var spawn = require('child_process').spawn;

var rsync = spawn('rsync', ['-avP', inputPath1, inputPath2]);

rsync.on('error', function (err) {
    // handle errors here
}).on('exit', function (code) {
    // code is exit code
});

// rsync.stdout is a readable stream that you can pipe somewhere.
// I would use this to inspect the running process, if it prints to stdout anyway.
rsync.stdout.pipe(somewhere);
```

**Comment by nfischer** [comment]
`shell.exec()` already does emit stdout in real time to the console. This does not work if the program you're running (ex. `rsync`) expects to be run from a terminal.

If `rsync ... | cat` works as you want, then `shell.exec('rsync ...')` should too. We've been looking into ways of faking the tty, but I believe there are issues with doing that while also capturing the output.

**Comment by nfischer** [comment]
You can also try something like:

```js
var c = shell.exec('rsync ...', { async: true });
c.stdout.on('data', function (data) {
  console.log('I got some data');
  // Or you can alert your GUI here that progress has been made
});
```

See [the docs](https://github.com/shelljs/shelljs#execcommand--options--callback)

**Comment by bmcgonag** [comment]
Thanks so much for the suggestions and Ideas. I'll put these to work, and see what i come up with.

**Comment by nfischer** [comment]
Closing this. If you have any further questions, feel free to re-open :smile:
