### ISSUE TITLE
feat: cp & mv should not overwrite recently created files

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#631]
If you have a copy command like:

```sh
$ cp file1.txt out/file1.txt destination/
```

You should get an error that says something like:

```
cp: will not overwrite just-created ‘destination/file1.txt’ with ‘out/file1.txt’
```

We're currently silently overwriting files that we created in that same copy command, but should instead provide a warning and refuse to copy the second file.

The behavior should stay the same with `-f` and `-r`, but `cp` does not give the warning with directories or their contents.

```sh
$ cp dir1 out/dir1 destination/ # never has this error
$ ls destination/dir1/ # shows the merged contents of both ./dir1/ and out/dir1/
```

The warning is never present with the `-n` flag.

This warning should also be presented for the `mv` command.

**Comment by uttpal** [comment]
@nfischer I would like to fix this issue

**Comment by nfischer** [comment]
@uttpal Help would be very appreciated!

Yes, I believe your understanding is correct. If in doubt, you can always try out GNU cp/mv on a Linux system.

**Comment by uttpal** [comment]
@nfischer 
In the case of a directory, cp is overwriting recently created files with the latest one.

`cp -R dir1 dir2/dir1 dir3/dir1 dest/`
`cat dest/dir1/file1`  > `in dir3`

**Comment by nfischer** [comment]
> In the case of a directory, cp is overwriting recently created files with the latest one.

You're right, I was mistaken. Thanks for double checking
