### ISSUE TITLE
mkdir fails with non-normalized path

### ISSUE THREAD

**Issue by webOS101** [shelljs/shelljs#634]
### Example ShellJS command to reproduce the error:

```javascript
shelljs = require('shelljs');
shelljs.mkdir('-p', 'asdf/./');
```

Expected result is that no error should be thrown and certainly the process should not terminate.  `'-p'` flag should not fail for any existing path or part of path.

**Comment by nfischer** [comment]
@webOS101 Thanks for reporting. It looks like most of our utilities should probably normalize paths before using them. I'll work on a fix for this tonight using `path.resolve()`.

It looks to me like *most* commands would want paths to be resolved before handling them (`ln()` is an example of where this is **not** the case). I'll wrap this functionality as a default part of `common.wrap` (`ln()` will opt-out), although this probably only affects `mkdir -p`, `cp -r`, and `rm -r`, and `ls -R` (anything recursive).

To address your second concern, where the process dies, this will be fixed when we release v0.8. See #483.
