### ISSUE TITLE
How to increase ShellJS buffer size?

### ISSUE THREAD

**Issue by DorEliyahu17** [shelljs/shelljs#639]
### Node version (or tell us if you're using electron or some other framework): 
v7.1.0

### ShellJS version (the most recent version/Github branch you see the bug on): 
v0.7.4

### Operating system: 
Windows 10/Windows 7

### Description of the bug:
I'm writing a script that execute the command ```shell.exec('ls -l -R [path to search in] | grep -v .lnk | tr -s " "', {silent: false});``` and when I'm trying to execute this command on a path that has more than 21005244 chars in the output of the command, the execute of the command stopped and the script continue to running.
I'm assuming that the bug is that I need to increase the size of the ShellJS but I can't find how.
Can you please help me to find how to do so?
Thanks

### Example ShellJS command to reproduce the error:
```javascript
shell.exec('ls -l -R C:/Users/User/Desktop | grep -v .lnk | tr -s " "', {silent: false});
```

**Comment by nfischer** [comment]
Workaround provided by #335. See [the exec docs](https://github.com/shelljs/shelljs#execcommand--options--callback) and the [`maxBuffer`](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) docs
