### ISSUE TITLE
Drop support for v0.12

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#647]
According to the [NodeJS LTS schedule](https://github.com/nodejs/LTS), v0.12 support was dropped by Node in December 2016. This means it's probably reasonable to drop the support in our v0.8 release.

This has some benefits for us:

 - we can cut v0.11 and v0.12 from our Travis builds for faster CI (maybe even iojs too, which sometimes has false negatives)
 - we can significantly trim down on the code inside `src/exec.js` (there's a whole [v0.10-specific else-branch](https://github.com/shelljs/shelljs/blob/4c48631d745ef4cb3e9d198b37e5772fb57ce905/src/exec.js#L128))
 - we can [clean up tests](https://github.com/shelljs/shelljs/blob/4c48631d745ef4cb3e9d198b37e5772fb57ce905/test/exec.js#L116)
 - we can trim down `src/tempdir.js` a [bit as well](https://github.com/shelljs/shelljs/blob/4c48631d745ef4cb3e9d198b37e5772fb57ce905/src/tempdir.js#L43)
 - we can remove our `Object.assign()` polyfill (if we remove iojs as well)

@freitagbr what are your thoughts on dropping v0.12 support? What about dropping iojs support? We'll get the biggest CI benefits if we go with iojs, but I don't know if many people still rely on it (my guess is iojs users have moved on to v4+).

**Comment by freitagbr** [comment]
I would be in favor of dropping support for iojs. I don't see it being widely used in production or even development, and like you said, most iojs users should at least be on v4 or later by now.

I know usage of v0.12 is pretty common still, though dropping support for v0.12 and below is probably fine as long as this lands in v0.8+ only.

Just make sure that `"engines": { "node": ">=4" }` ends up in `package.json`.

**Comment by nfischer** [comment]
Ok, I can take this up
