### ISSUE TITLE
Question: what is the correct shebang for scripts?

### ISSUE THREAD

**Issue by publicocean0** [shelljs/shelljs#652]
in manual is not written how to insert the prefix for executing directly script 
#!/bin/shelljs

is correct?

**Comment by nfischer** [comment]
Hi @publicocean0! Thanks for trying out ShellJS.

Are you using this for a node package or just to write some scripts for your computer? I may be able to give you better advice depending on your use-case.

You'll probably want to install with something like:

```sh
$ npm install -g shelljs
```

You should write your files to look something like:

```js
#!/usr/bin/env node

var shell = require('shelljs');
shell.echo('Hello world!');
```

You can run the script with

```sh
$ node ./path/to/script.js
$ # or...
$ script.js # if this is installed somewhere in your PATH and has '+x' permission
```

**Comment by publicocean0** [comment]
Thanks
