### ISSUE TITLE
Rewrite exec using execsync-ng (which uses node-ffi)

### ISSUE THREAD

**Issue by spion** [shelljs/shelljs#66]
Hi,

Shelljs has been awesome so far, except for `exec`. I know how it works, with the write-to-a-temporary file loop, and I know that its a hack necessary due to the lack of child_process.execSync. 

Unfortunately, exec has been very buggy for me, randomly not working on various developer and server machines. Usually it gets stuck in an endless loop. I never seem to be able to satisfyingly reproduce the issue or find the cause.

So I decided to give that up and write shelljs-ffi based on execsync-ng which in turn is based on node-ffi. execsync-ng is a fork of execSync that also works on windows. 

You can check out these modules at https://github.com/doxout/shelljs and https://github.com/doxout/execSync or try them out: npm install shelljs-ffi execsync-ng

I know that a native module dependency such as node-ffi is probably unacceptable for shelljs. However I decided to ask anyway... Is it possible that this fork may be accepted into shelljs?

**Comment by aurium** [comment]
Node now supports `child_process.execSync` https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options

**Comment by nfischer** [comment]
Closing this, since we no longer support v0.10, and can utilize the synchronous functions.
