### ISSUE TITLE
Passing empty string to cp throws internal error

### ISSUE THREAD

**Issue by webOS101** [shelljs/shelljs#664]
### Node version (or tell us if you're using electron or some other framework):
v6.8.0
### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.6
### Operating system:
Mac OS X
### Description of the bug:
Passing empty string to `cp` command throws an internal error.  Would be much easier to deal with an exception or error return.

```
ShellJS: internal error
Error: must provide pattern
    at new GlobSync (node_modules/glob/sync.js:31:11)
...
   at node_modules/shelljs/src/common.js:246:22
```

### Example ShellJS command to reproduce the error:

```javascript
shelljs.cp('', 'dest');
```

**Comment by freitagbr** [comment]
Thank you for the bug report. I think the desired behavior in this case is to just source string(s), even if they're empty. This is what GNU `cp` does:
```
$ cp "" dest
cp: cannot stat '': No such file or directory
```
If any of the source files do not exist, then return a shell error like the above.

**Comment by nfischer** [comment]
@freitagbr sure, that sounds like a reasonable approach. You can fix this inside `common`. Just don't pass the empty string to `globSync`.

This can be a unit test on `common.expand()`. We should probably write tests for the following cases:

 - `common.expand([])`: either throw an error or allow it to return `[]`, whichever makes more sense
 - `common.expand([''])`: returns `['']`
 - `common.expand([5])`: either throw an error or return `[5]`, whichever makes more sense
