### ISSUE TITLE
Cant get encoding buffer to work on exec

### ISSUE THREAD

**Issue by vongohren** [shelljs/shelljs#675]
### Node version (or tell us if you're using electron or some other framework):
7.6.0

### ShellJS version (the most recent version/Github branch you see the bug on):
"version": "0.7.6"

### Operating system:
Mac OS

### Description of the bug:
Im trying to run 
```git archive --remote repo HEAD keystores/keystore.jks | tar -xO```
But the encoding get fucked up when running through shelljs synchronous command.
I need to have buffer as encoding.

### Example ShellJS command to reproduce the error:
```exec(`git archive --remote=${url} ${branch} ${path}${file} | tar -xO`)```
If you have a keystore anywhere, try that
The keystore becomes invalid.

I have noe used node directly where "buffer" works as encoding

**Comment by nfischer** [comment]
Assigning @freitagbr because this is similar to the root cause of #645 (both deal with encoding issues)

**Comment by vongohren** [comment]
No action or close? Im doing something else now

**Comment by nfischer** [comment]
ping @freitagbr any action to take here?

**Comment by freitagbr** [comment]
Well, I'm pretty sure this would fix the problem:
```
var result = exec('git archive ...');
var keystone = Buffer.from(result.stdout, 'utf8');
```
This just converts the keystone string back into a buffer.

However, this seems like a good opportunity to add an `"encoding"` option to `exec`, so I will work on that.
