### ISSUE TITLE
*CRITICAL data loss* shell.cp() Content of file is erased when trying to copy it to the folder it already belongs to

### ISSUE THREAD

**Issue by dperetti** [shelljs/shelljs#678]
### Node version (or tell us if you're using electron or some other framework):
7.5.0
### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.5
### Operating system:
Mac OS X
### Description of the bug:
If you try to copy a file to the folder it already belongs to, the content of the file is erased.
### Example ShellJS command to reproduce the error:

```bash
echo "blah" > /home/test
```

```javascript
shell.cp('/home/test', '/home')
```

```bash
cat /home/test
```

`/home/test` is now empty.

**Comment by nfischer** [comment]
@dperetti thank you for reporting this. I will try later today to repro.

**Comment by freitagbr** [comment]
I've been able to reproduce this, and I am working on a fix. @nfischer, I don't have a linux env to test with, so what do you get on stderr when you run this?
```
echo test > test.txt
cp test.txt test.txt
```

**Comment by nfischer** [comment]
```sh
$ echo test > test.txt
$ cp test.txt test.txt
cp: 'test.txt' and 'test.txt' are the same file
$ cp test.txt .
cp: 'test.txt' and './test.txt' are the same file
$ cat test.txt # no changes to the file
test
```
