### ISSUE TITLE
Switch to os.homedir() when we move to v4+

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#683]
NodeJS added support for `os.homedir()` to get the user's home directory in a reliable way. When we drop support for v4, let's switch to that to reduce the amount of code we need to maintain.

**Comment by freitagbr** [comment]
If os.homedir is not reliant on native code, maybe we could polyfill it?

**Comment by freitagbr** [comment]
If os.homedir is not reliant on native code, maybe we could polyfill it?

**Comment by nfischer** [comment]
We already have our [own implementation](https://github.com/shelljs/shelljs/blob/master/src/common.js#L158-L169). I was suggesting we remove that implementation once we switch to v4+.

**Comment by nfischer** [comment]
Already fixed in #725
