### ISSUE TITLE
Would you be interested in a PR for `open`?

### ISSUE THREAD

**Issue by mathiasrw** [shelljs/shelljs#692]
I wanted to open a file as part of a workflow, but realised I need to `.exec('open ...')` on linux and `.exec('start ...')` on windows. 

Would you be interested in a PR providing a new function `.open(...)` that opens a file/folder ?

**Comment by nfischer** [comment]
Check out the [plugin](https://github.com/shelljs/shelljs/wiki/Derivative-works-and-related-projects#plugins)

`open` is not a standard POSIX command, so we thought it safer to implement as an example plugin. When we announce official plugin support, we'll add a better link in our README (so this is clearer to users 😄 )

If you encounter bugs with that module, file an issue on its own repo and I'll take a look.
