### ISSUE TITLE
source command not working via exec method.

### ISSUE THREAD

**Issue by praveenpuglia** [shelljs/shelljs#693]
### Node version (or tell us if you're using electron or some other framework):
7.7.4

### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.7

### Operating system:
Ubuntu 16.04

### Description of the bug:
Trying to execute the `source` command using `shell.exec()` but it isn't working. I get `source` not found error. 
```
/bin/sh : 1: source: not found
```
### Example ShellJS command to reproduce the error:

```javascript
var shell = require('shelljs');
shell.exec('source somefile.sh');
```

**Comment by nfischer** [comment]
`source` isn't supported from `exec`.

If you want to execute a script, invoke it directly: `shell.exec('bash name-of-script.sh')`. This isn't very portable, which makes me wonder if ShellJS would provide any advantages for you.

If you really need the to source a script like `somefile.sh` (e.g. to modify your environment), you'll need to transpile that to ShellJS as well. You can take a look at https://github.com/nfischer/shelljs-transpiler for help.

If this doesn't answer your question, please ping this issue and we can reopen it.
