### ISSUE TITLE
SORT command

### ISSUE THREAD

**Issue by rpjan** [shelljs/shelljs#697]
Node version: v6.9.4
ShellJS version:0.7.7
OS: Windows 10

Description of the issue:
hi, I am a beginner and I am trying to use the sort command. When i run it, it gives no error, but the file content remains the same. I have attached the files I used. thank you for your help.
[file_sort.zip](https://github.com/shelljs/shelljs/files/880844/file_sort.zip)

**Comment by nfischer** [comment]
The command does not modify your file, it returns the sorted contents. If you want to overwrite your file, you'll need to do `sort(filename).to(filename)`. @rpjan are you saying that the returned contents is not sorted?

```js
var sortedValue = shell.sort('foo.txt');
// if sortedValue should be sorted linewise at this point
// the contents in foo.txt are not modified
sortedValue.to('foo.txt'); // now foo.txt is modified
```

**Comment by rpjan** [comment]
amazing! it works beautifully. I was using it incorrectly. thank you so much for the quick help and the wonderful too.
