### ISSUE TITLE
Makefile `this` Binding

### ISSUE THREAD

**Issue by tech4him1** [shelljs/shelljs#698]
Just for the docs, it might be good to note that in shelljs makefiles `target`s, `this` is set to the function itself, not the main `target` object as some might expect.  This is because `this` is explicitly rebound to each `target` function in the duplicate prevention wrapper ([make.js#L36](https://github.com/shelljs/shelljs/blob/353138c5e006adbff1763b9483b1b70a0f6d318e/make.js#L36)).

**Comment by nfischer** [comment]
We don't really support `make` anymore (there are dedicated node task runners like grunt and gulp). If you'd like to update the docs, feel free to change the wiki page for it.
