### ISSUE TITLE
`ls` does not always show subfolder paths correctly

### ISSUE THREAD

**Issue by tech4him1** [shelljs/shelljs#700]
### Node version (or tell us if you're using electron or some other framework):
7.8.0
### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.7
### Operating system:
Windows 10
### Description of the bug:
When you run `ls *` in Bash, it shows items listed by subdirectory.  When you run `ls('*')` in shelljs, the items are listed without the rest of the path showing the directory they are in.
### Example ShellJS command to reproduce the error:

```javascript
> ls('*');
[ 'a',
  'b',
  'c' ]
```
#### Expected Output:

```javascript
> ls('*');
[ 'a',
  'b\c' ]
```
or 
```javascript
> ls('*');
[ 'a',
  'b',
  'b\c' ]
```

**Comment by nfischer** [comment]
@tech4him1 Maybe you're looking for `ls('-R', '.')`? Remember, when bash `ls` outputs something like:

```sh
$ ls *
a:

b:
c
```

the `a:` and `b:` aren't entries in the output, they're labels so you can tell where `c` belongs. Just like if you ran `ls -R .` in bash, you would see `.:` as a label, not an entry.
