### ISSUE TITLE
use cp('-r', './src', './dist') bug

### ISSUE THREAD

**Issue by lemonleon** [shelljs/shelljs#705]
### Node version (or tell us if you're using electron or some other framework):
Node version: 4.3.0
### ShellJS version (the most recent version/Github branch you see the bug on):
ShellJS version: 0.7.7
### Operating system:
Windows 7
### Description of the bug:
use cp command copy 2 directory to destination directory 
if destination is non-existent, the 2 directory cannot be created correctly

```javascript
require('shelljs/global');

cp('-r','./src/testA', './dist/');
cp('-r','./src/testB', './dist/');
```

```javascript
    |-src
        |-testA
            |-testA.txt
        |-testB
            |-testB.txt
```

if destination is non-existent, the directory structure is created as follows:

```javascript
    |-dist
        |-testB
            |-testB.txt
        testA.txt
```

**Comment by freitagbr** [comment]
Hi @lemonleon, what behavior are you expecting?

When I test this in bash, I get the following result:
```
$ ls
src
$ ls -r src/*
src/testB:
testB.txt

src/testA:
testA.txt
$ cp -r ./src/testA ./dest/
$ ls
dest  src
$ ls dest
testA.txt
$ cp -r ./src/testB ./dest/
$ ls dest
testA.txt  testB
$ ls dest/*
dest/testA.txt

dest/testB:
testB.txt
```
This is looks like the same behavior as shelljs.

**Comment by lemonleon** [comment]
Hi~ i means 2 cp(xxx) command run together
like: 
```javascript
cp('-r','./src/testA', './dist/');
cp('-r','./src/testB', './dist/');
```
one of them directory not created correctly;
I hope the result is:
```javascript
|-dist
    |-testA
        |testA.txt
    |-testB
        |testB.txt
```
but in fact:
```javascript
|-dist
    |-testB
        |testB.txt
    |-testA.txt
```
testA dir not created.
And the premise of this mistake is 'dist' created by shelljs, `2 cp(xxx) command run together`, would happened

**Comment by freitagbr** [comment]
If you run this in bash, where the directory `dist` doesn't exist yet:
```
$ cp -r ./src/testA ./dist/
$ cp -r ./src/testB ./dist/
```
you will get the second result:
```
|-dist
    |-testB
        |testB.txt
    |-testA.txt
```
So, this is not a bug with ShellJS because it has the same behavior as `cp`. If you want the first directory structure, the destination directory should be created first:
```
mkdir('dist');
cp('-r', './src/testA', './dist/');
cp('-r', './src/testB', './dist/');
```

**Comment by lemonleon** [comment]
Oh~ I see~!  thanks very much~ (:
