### ISSUE TITLE
Copying hidden files fails on Windows 10

### ISSUE THREAD

**Issue by rajsite** [shelljs/shelljs#711]
### Node version (or tell us if you're using electron or some other framework):
v6.9.5

### ShellJS version (the most recent version/Github branch you see the bug on):
shelljs 0.7.7 via shx 0.2.2

### Operating system:
Windows 10 64-bit

### Description of the bug:
On Windows trying to copy files in a directory that contain only a single file named `.nojekyll` results in error:

`cp: no such file or directory: Documents/DocumentsRoot/*`

Directory structure:
/gh-pages/
/Documents/DocumentsRoot/.nojekyll

command run: `shx cp Documents/DocumentsRoot/* gh-pages`

The following comment specifies that should be fixed:
https://github.com/shelljs/shelljs/issues/140#issuecomment-149642901

But I still have to do the workaround of including a `.` before the wildcard like:
`shx cp Documents/DocumentsRoot/.* gh-pages`

I see the behavior both with and without the -r flag when using shx. Have not tried using shelljs directly.

**Comment by freitagbr** [comment]
Hey @rajsite, thank you for reporting this. I will look into this issue in the next day or two.

**Comment by nfischer** [comment]
@rajsite That is not a 'workaround' in this case, it's intended behavior:

```sh
$ cp dir/* dest/ # copies all non-hidden files in the directory
$ cp -R dir/ dest/ # copies the directory and all files in it (hidden or otherwise)
$ cp dir/.* dest/ # copies all hidden files in the directory
$ cp dir/* dir/.* dest/ # copies all files in the directory, without the directory itself
```

This is the POSIX shell behavior, and ShellJS should be compliant. If shelljs or shx behave other than how I've described, let us know.

**Comment by rajsite** [comment]
@nfischer when running `cp dir/.*` on linux I get the following output

```
> shx cp Documents/DocumentsRoot/.* gh-pages && shx cp Documents/DocumentsRoot/* gh-pages
cp: omitting directory 'Documents/DocumentsRoot/.'
cp: omitting directory 'Documents/DocumentsRoot/..'
```
resulting in a non-zero error code.

Should `shx cp` ignore the `.` and `..` inodes while allowing other hidden files?
What would be the cross-platform way to use shx cp to wildcard copy files starting with `.` without an error?

**Comment by nfischer** [comment]
> Should shx cp ignore the . and .. inodes while allowing other hidden files?
> What would be the cross-platform way to use shx cp to wildcard copy files starting with . without an error?

Ah, that's because Bash expands the `.*` to include `.` and `..` (my mistake). Unfortunately, this is very difficult to get right in Bash (other shells handle things more sensibly). If you need it to work in bash, this usually works:

```sh
$ shx cp dir/.??* out/ # this works if you have no 1-2 letter hidden files
```

> ```
> > shx cp Documents/DocumentsRoot/.* gh-pages && shx cp Documents/DocumentsRoot/* gh-pages
> cp: omitting directory 'Documents/DocumentsRoot/.'
> cp: omitting directory 'Documents/DocumentsRoot/..'
> ```

This approach fails under at least a couple scenarios. I strongly recommend going with something like:

```sh
$ # If you want something like:     gh-pages/.nojekyll
$ shx rm -rf gh-pages/ && shx cp -R Documents/DocumentsRoot/ gh-pages/
$ # or, if you want:                gh-pages/DocumentsRoot/.nojekyll
$ mkdir -p gh-pages/ && shx cp -R Documents/DocumentsRoot/ gh-pages/
```

If neither of those work for you, there's an shx-only trick you can do:

```sh
$ shx cp "dir/*" out/ # don't let bash expand wildcards, rely on shx's internal expansion
$ # this won't expand to '.' and '..'
```
