### ISSUE TITLE
exec command hanging when pipe empty to `awk`

### ISSUE THREAD

**Issue by Secbone** [shelljs/shelljs#718]
exec `awk` command will hang on when the pre-command pipe empty.

```javascript
shell.exec('echo 1 > /dev/null').exec('awk {print}')
```

**Comment by nfischer** [comment]
I'll see if I can investigate over the weekend

**Comment by nfischer** [comment]
This is related to #551. In both issues, the stdin to the second command is empty. When the second command is something like `grep()`, it will claim that it was provided no input and terminate. In the case of `exec()`, the awk command inside will hang forever waiting for input.

**Comment by nfischer** [comment]
Marking this as a duplicate of #551.
