### ISSUE TITLE
Can't make sed perform global replace

### ISSUE THREAD

**Issue by dsl101** [shelljs/shelljs#719]
### Node version (or tell us if you're using electron or some other framework):
Node 6.9.2 with VueJS and Quasar
### ShellJS version (the most recent version/Github branch you see the bug on):
shelljs@0.7.7
### Operating system:
Debian 7.11
### Description of the bug:
I'm trying to use `shell.sed()` inside a node build script to adjust the contents of a CSS file. The file has already been processed by various other optimisers, and so is on a single line. Therefore, I need to use a 'global' replace in the sed call, and I can't figure out how to do that - otherwise it just replaces the first occurance.
### Example ShellJS command to reproduce the error:
To 'repoint' font source references which currently read `src: url(app/Roboto...` and should read `src: url(Roboto...`, I'm using this (not sure why double-escape is needed on the 'find' param, but it errors out otherwise):

    shell.sed('-i', 'src:url\\(app\\/', 'src:url\\(', cssFiles)

The end result is that the very first reference to `src: url(app/Roboto...` has been replaced, but the others are all still wrong. It's not clear how to tell `shell.sed()` to add a 'g' to the search term.

**Comment by dsl101** [comment]
Sorry - just realised I can pass a RegExp in. Still, it might be interesting to add this, so global string replacement is supported:

	cmdOptions: {
		'i': 'inplace',
		'g': 'global',
	},

and:

	if (typeof regex === 'string') {
		regex = RegExp(regex, options.global ? 'g', '');
	}

**Comment by nfischer** [comment]
Sure, seems reasonable. @dsl101 might be a good contribution 😄

**Comment by nfischer** [comment]
Actually, just looked at this again. Sed doesn't have a `-g` flag itself, but takes a `/g` modifier to the regex. So I think we should keep this as-is, not add the command option (since that would be inconsistent with unix).

**Comment by dsl101** [comment]
Yeah, I'd been thinking about that - I was thinking about the other flags
the regex can take and whether that could be an additional parameter rather
than a set of options. But maybe not necessary since you can just pass the
regex.

**Comment by dragGH102** [comment]
@nfischer Could you clarify **how to pass /g** flag since as far I see `shelljs` doesn't use the standard / / regex delimiters?

For example in this case:

> shell.sed('-i', `\\[${variable}\\]`, eval(variable), `${localPath}/${entry.name}`);

which **aims** to:

> replace [any_string] with any_string variable (without brackets)

(Note that variable is used in the search as variable's name, but it's replaced with variable's value

Thanks in advance

**Comment by nfischer** [comment]
The `/g` flag is poorly documented, I'd gladly review a PR adding another example to the `sed()` documentation.

However, you can find an example of how to use it under the [pipes documentation](https://github.com/shelljs/shelljs#pipes) (`/g` is **not** pipe-specific, that's just our only documentation right now). Also, take a look at our [unit tests](https://github.com/shelljs/shelljs/blob/master/test/sed.js) for non-pipe examples.

---

I don't think you can use `/g` with ES6 template literals. I suspect it only works with a `Regex` object (which looks like `/my pattern/g`).

**Comment by dragGH102** [comment]
@nfischer Thanks for your answer.

I've tried to use /g even by containing the string with `+`. 

Could you explain me how to it in my example (see previous comment)? I don't mind with or without square brackets (if easier for you, just put `__`in the regex in front of the variable value, instead of sorrounding it with square brackets

**Comment by nfischer** [comment]
@dragGH102 have you tried backreferences? Unix `sed` uses the `\1` syntax to reference the first group, while `shell.sed()` uses `$1`. You can match groups with parentheses.

I think you want a regex like `/\[([^\]]*)\]/g`.

Also, avoid `eval()` whenever possible. If these are attributes on `global` (or some other object), please consider `global[variableName]` (security implications).
