### ISSUE TITLE
is rechoir used anywhere?

### ISSUE THREAD

**Issue by jchip** [shelljs/shelljs#723]
https://github.com/shelljs/shelljs/blob/master/package.json#L54

Is the dependencies rechoir used somewhere?  A grep didn't find it in any code.

```
$ find . -name "*.j*" | xargs grep rechoir
./package.json:    "rechoir": "^0.6.2"
```

**Comment by freitagbr** [comment]
Hi @jchip, rechoir is used in [bin/shjs](https://github.com/shelljs/shelljs/blob/master/bin/shjs).

**Comment by jchip** [comment]
yeah, just found it. :)  thanks.  would be nice if I could get the shelljs module w/o the command line program though.

**Comment by nfischer** [comment]
@jchip I agree (see #500). We should probably get on that before the v0.8 release so we can deprecate the binary within the main package.
