### ISSUE TITLE
exec returning null from command

### ISSUE THREAD

**Issue by webOS101** [shelljs/shelljs#724]
### Node version (or tell us if you're using electron or some other framework):
v6.2.1

### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.7

### Operating system:
MacOS X 10.10

### Description of the bug:
Occasionally, the `exec` command returns `null` instead of something valid.  I have an automated build script that executes.  Some time during the execution of the script, it fails with the error:

```
.../scripts/DocParser.js:51
		if (output.code === 0) {
		          ^

TypeError: Cannot read property 'code' of null
```

### Example ShellJS command to reproduce the error:

```javascript
const output = shelljs.exec(cmd, {silent: true});
```

These `exec`s are called in a loop and it's not the first one that fails.  If I call the script outside of the automation procedure, it runs to completion without issue.  I'm super stumped on this one and could use any help debugging the problem.

**Comment by nfischer** [comment]
@webOS101 how often can you reproduce this?

**Comment by webOS101** [comment]
Fairly consistently.  I can reproduce it at will.

**Comment by nfischer** [comment]
@webOS101 would you be willing to pull down a copy of shelljs and try it out locally?

```sh
$ shelljsPath=path/to/your/project/node_modules/shelljs/
$ rm -rf "$shelljsPath"
$ git clone https://github.com/shelljs/shelljs.git "$shelljsPath"
$ cd "$shelljsPath"
$ git checkout debug-724-null-exec
$ cd -
$ # try to reproduce the bug again and paste the console output on this bug
```

**Comment by webOS101** [comment]
I saw your commit and added it to my repo. I went with:
```
    "shelljs": "github:shelljs/shelljs#debug-724-null-exec",
```
in my `package.json` since this is run on a separate box through automation.

**Comment by webOS101** [comment]
https://gist.github.com/webOS101/adc7ce330079c24bb8d30e725779c6c5

**Comment by nfischer** [comment]
@webOS101 Still can't quite identify the error, but the `exec: internal error` indicates a bug in our code. Could you try pulling in the latest version of that branch and reproducing again? Thanks

**Comment by webOS101** [comment]
Perhaps unsurprisingly it clocks in at about 64K.  I don't know why this passes for some builds and fails for others, though.  Our largest output file is 262K and it can complete without issue.

**Comment by nfischer** [comment]
Yeah, it seems to be pretty sizable. You can try increasing `exec`'s buffer size:

```js
shell.exec('your-command-here', { maxBuffer: 1024*1024 });
// default is 200 * 1024
```

If this does fix the issue, this is probably something we should look out for specifically, so that we can give a better error message.

**Comment by nfischer** [comment]
Whoops, made a mistake. ShellJS has a higher default size (`20 * 1024 * 1024`). So maybe try `1024 * 1024 * 1024`

**Comment by webOS101** [comment]
```
{ Error: ENOENT: no such file or directory, open '/var/folders/bn/4f4fcly97sx1g8_3nryzfqxh0000gp/T/shelljs_2bf8e16a4a7cabfe73b1'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at execSync (/Users/xxx/workspace/xxx-docs/xxx-docs/node_modules/shelljs/src/exec.js:165:24)
    at Object._exec (/Users/xxx/workspace/xxx-docs/xxx-docs/node_modules/shelljs/src/exec.js:289:14)
    at Object.exec (/Users/xxx/workspace/xxx-docs/xxx-docs/node_modules/shelljs/src/common.js:353:23)
    at /Users/xxx/workspace/xxx-docs/xxx-docs/scripts/DocParser.js:42:26
    at Set.forEach (native)
    at getDocumentation (/Users/xxx/workspace/xxx-docs/xxx-docs/scripts/DocParser.js:36:13)
    at init (/Users/xxx/workspace/xxx-docs/xxx-docs/scripts/DocParser.js:151:4)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/folders/bn/4f4fcly97sx1g8_3nryzfqxh0000gp/T/shelljs_2bf8e16a4a7cabfe73b1' }
exec: internal error
```

**Comment by webOS101** [comment]
I tried using the larger buffer, as suggested, but it didn't make a difference.  The drive is not full, which was my first thought.  Other ideas?

**Comment by freitagbr** [comment]
It looks like one of the temp file storing the process ext code created by `exec` is being removed before the process finishes.

@nfischer Remind me why `execSync` needs to create the temporary files and execute them in node. Is it because we want the stdout/stderr of the spawned process to update in real time?

**Comment by nfischer** [comment]
> It looks like one of the temp file storing the process ext code created by exec is being removed before the process finishes.

If `child_process.exec()` in the temp script invokes its callback, then we know the `codeFile` is actually created on disk, before the child process terminates. If that file is created on disk, then we'll definitely be able to read it by the time we get to that line of code. So that must mean we *aren't* calling the callback (due to an exception in `child_process.exec`), or we get some exception early on in the callback.

This sort of thing is actually plausible. Here's a minimal example:

```js
// This example requires unix (since it uses the `yes` command
require('child_process').exec('yes', function (code) { // overflow the maxBuffer with lots of stdio
  console.log('I will never get called');
});
```

It sounds like our external command has tons of output, so this makes some sense. If this really is the case, then I think we can make some progress by wrapping `child_process.exec()` in a try-catch.

Unfortunately, I can't find a command that will consistently break `shell.exec()`. For some reason `yes` does not repro the bug in shelljs. I need help getting a consistent repro before I can fix this.

> @nfischer Remind me why execSync needs to create the temporary files and execute them in node. Is it because we want the stdout/stderr of the spawned process to update in real time?

Yes, that's exactly the reason

**Comment by nfischer** [comment]
@webOS101 Would you be able to try the latest version of the branch again? I added a couple more debug logs that should help confirm my suspicions. Thanks!

**Comment by webOS101** [comment]
I will try to do this.  I had to replace that bit in my code so that I could get my build working again.  I can probably check out an older version of my scripts to see what happens.

**Comment by nfischer** [comment]
Thanks, I appreciate the help debugging. This is a long-time bug we've never been able to repro, and I'd like to get a fix out.

I'm convinced that we need to follow my try-catch suggestion regardless, but I'd like to dig deeper and see if that's really causing this issue.

**Comment by mikeweaver** [comment]
FYI: I believe I have a reproducing case of this bug as well.

**Comment by nfischer** [comment]
@mikeweaver what happens if you try out that branch? What do the logs show?

```sh
$ rm -rf node_modules/shelljs
$ npm install 'github:shelljs/shelljs#debug-724-null-exec'
```

**Comment by nfischer** [comment]
We did a big refactor of `exec()` (0.8.1) I think this is resolved. Let me know if that's not the case.

**Comment by Morphexe** [comment]
Sadly no, I just hit this when running a script.

`const mkdir = shell.mkdir(....)`

`if (mkdir.code == 0)`
This throws a error saying mkdir is undefined.

shell.ls('-Rl', '.').forEach -> same drill " Cannot read property 'forEach' of null"

**Comment by nfischer** [comment]
@Morphexe please file a new issue, Your problem appears to not be exec-related, but I need the info from the bug template to diagnose.

**Comment by yuanhaisu** [comment]
`ShellJSInternalError: ENOENT: no such file or directory, open '/tmp/shelljs_22c2372f7902a33382c6'
    at Object.openSync (fs.js:434:3)
    at Object.readFileSync (fs.js:339:35)
    at execSync (/home/reporter-skynet/node_modules/shelljs/src/exec.js:89:17)
    at Object._exec (/home/reporter-skynet/node_modules/shelljs/src/exec.js:202:12)
    at Object.exec (/home/reporter-skynet/node_modules/shelljs/src/common.js:335:23)`
I met the same promble in v0.8.2, How can I debug this error , please help me!

**Comment by nfischer** [comment]
@yuanhaisu please file a new Github issue. We need all info from the bug template.

**Comment by jbcpollak** [comment]
I'm having the same issues as @webOS101 and @yuanhaisu - node 10.9.0, shelljs 0.8.1 _and_ 0.8.2, and macOS 10.14.

Interestingly this was working two days ago, I came back to the computer and now it doesn't work.

**Comment by nfischer** [comment]
@jbcpollak I'm sorry, but this should be on a separate Github issue. For example, it's not clear if you're using electron or not.
