### ISSUE TITLE
Exec not working in Electron !

### ISSUE THREAD

**Issue by akshaygarg834** [shelljs/shelljs#726]
shell.exec not working showing this error

> Uncaught Error: exec: internal error
>     at Object.error (common.js:130)
>     at Object._exec (exec.js:292)
>     at Object.eval [as exec] (common.js:334)
>     at dialog.showOpenDialog.filepaths (Accordion.js?36f0:53)
>     at CallbacksRegistry.apply (C:\Users\aksgarg\Desktop\JARVIS\node_modules\electron\dist\resources\electron.asar\common\api\callb…:48)
>     at EventEmitter.<anonymous> (C:\Users\aksgarg\Desktop\JARVIS\node_modules\electron\dist\resources\electron.asar\renderer\api\rem…:299)
>     at emitThree (events.js:116)
>     at EventEmitter.emit (events.js:197)

`let shell=require('shelljs');
        shell.config.fatal=true;
        shell.cd(require('path').resolve(filepaths[0]));
        shell.exec(`git clone ${clone_url}`);`

**Comment by nfischer** [comment]
Please see the relevant wiki page:

https://github.com/shelljs/shelljs/wiki/Electron-compatibility

**Comment by nfischer** [comment]
Please reopen if that doesn't help you out.

**Comment by kayvanbree** [comment]
@akshaygarg834 Do you have shelljs running in Electron? If so, would you care to help me set it up for an open source project?
