### ISSUE TITLE
Installation fails w/ NPM 5.0.1 and Node.js 8.0.0 on macOS 10.12

### ISSUE THREAD

**Issue by tylucaskelley** [shelljs/shelljs#728]
### Node version (or tell us if you're using electron or some other framework):

8.0.0

### ShellJS version (the most recent version/Github branch you see the bug on):

0.7.7

### Operating system:

macOS Sierra 10.12

### Description of the bug:

Install fails with Node 8.0.0 on Mac:

![screen shot 2017-06-01 at 10 29 37 pm](https://cloud.githubusercontent.com/assets/5448759/26708438/d2a44dc4-4719-11e7-81da-c8ae667844e7.png)

### Example ShellJS command to reproduce the error:

N/A; fails on install with NPM 5.0.1, Node 8.0.0

**Comment by tylucaskelley** [comment]
Had similar issue with some other packages; turns out deleting my ~/.npm folder to clear the cache fixed the issue.

**Comment by nfischer** [comment]
Glad it's resolved!

**Comment by tylucaskelley** [comment]
Yeah, seems like something NPM shoulda handled automatically w/ the upgrade from 4.x to 5.x, wasn't super obvious it was a caching issue
