### ISSUE TITLE
Merge 'exec: internal error' with ShellJSInternalError

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#734]
I can't actually remember why we have both `ShellJSInternalError` and `exec: internal error`, but they mean the same thing: there's a bug in ShellJS code somewhere. These should probably get merged together, so that we can actually keep the exception stack for bugs in `exec`. This would help immensely in debugging.

While it's true that `exec()` sometimes crashes unavoidably (like if we overrun the max buffer), it's definitely still helpful to have the stack trace, and it still makes sense to report it as an exception, instead of with `shell.error()` (that should be reserved for the external command's stderr).

**Comment by nfischer** [comment]
@freitagbr can you investigate this?

**Comment by freitagbr** [comment]
Yes, I will look into this.

**Comment by nfischer** [comment]
@freitagbr is this something we can land for v0.8.0?

**Comment by freitagbr** [comment]
Yeah, I can put something together in the next few days.

**Comment by nfischer** [comment]
I think we'll have to bump this back to v0.9.0, didn't quite sort out the PR in time.
