### ISSUE TITLE
Add a config option to not actually mutate filesystem.

### ISSUE THREAD

**Issue by qm3ster** [shelljs/shelljs#747]
It is often valuable to just preview the commands without letting them run wild on your machine.
Proposed api:
```js
Object.assign(config, {verbose: true, noop: true})
```
Read-only commands like ls should probably still run.

**Comment by nfischer** [comment]
I don't think many of the GNU core-utils actually implement `--dryrun` flags.

When I'm scripting, I usually fallback on `echo` as my own sort of "dry run". If I want to run:

```sh
for k in *.txt; do
  cp "$k" "out/$k.bak"
done
```

I'll first run:

```sh
for k in *.txt; do
  echo "$k" "out/$k.bak" # Let's double check that the command will do what I intend
done
```

@qm3ster did you have a different use case in mind?

**Comment by qm3ster** [comment]
This is totally my usecase.
It is not just for dev, it would be useful for end users as well when learning to use the package.
Currently I have things like 
```js
const doIt = PROD
  ? command => exec(command, {async: true})
  : log

const doRm = PROD
  ? file => rm('-rf', file)
  : file => log(`rm -rf ${file}`)
```
but it would be useful to have this included in the lib by default, including all options and ShellString subcomands, etc.

**Comment by nfischer** [comment]
I don't quite see how end users would use this, perhaps you could elaborate?

To me, this doesn't sound very useful. I think of a script as a sequence of sections, where each section depends on those before it. If you're developing section C, you might temporarily want NOOPs. However, if it depends on the results of sections A and B (already written and debugged), then you would definitely want those to **not** be NOOPs. Disabling A and B too would make dependent sections impossible to develop.

**Comment by qm3ster** [comment]
The end users are writing something in a DSL, or a config, and can preview the results to see if they are sensible without waiting for execution after every change.

**Comment by nfischer** [comment]
It's hard to predict what kind of logging users would want, or if they would want all functions mocked or only some. I think it's best to leave this to users to implement as they choose. I think [your workaround](https://github.com/shelljs/shelljs/issues/747#issuecomment-309297332) is a good approach.

This gives the user total control, and it doesn't bloat the module with something only a few users would want anyway.

---

If you're really set on integrating this with shelljs, you could implement a [plugin](https://github.com/shelljs/shelljs/wiki/Using-ShellJS-Plugins) named `shelljs-plugin-noop`, which would overwrite each command with NOOPs. An example usage:

```js
var shell = require('shelljs');
require('shelljs-plugin-noop'); // comment this line to get real implementations back

shell.rm('file.txt'); // aliased to `console.log('file.txt')` by the plugin
```

You would need to make use of the [overWrite](https://github.com/shelljs/shelljs/blob/master/src/common.js#L419) option.

**Comment by freitagbr** [comment]
Another way to go about this would be to mock the `fs` module, using [`mock-fs`](https://www.npmjs.com/package/mock-fs) for example. You could set up the mock fs before `shelljs` is required, so that any ShellJS calls hit the mock fs, not the real one.

**Comment by nfischer** [comment]
Good suggestion @freitagbr. I'm closing this, because I think there are reasonable workarounds available outside of ShellJS that will ultimately work better for the end user. Please ping this thread if there are important use cases we're overlooking.
