### ISSUE TITLE
cat doesn't support '-n' option

### ISSUE THREAD

**Issue by maunier** [shelljs/shelljs#750]
### Node version (or tell us if you're using electron or some other framework):
v7.9.0
### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.8
### Operating system:
osx
### Description of the bug:
cat method don't support options, 
### Example ShellJS command to reproduce the error:
i need to cat a file with line number, but now it dosen't support it
```javascript

```

**Comment by nfischer** [comment]
Yeah, we never implemented options on `cat()`. Pull requests are welcome!

This feature request calls for the `-n` option I believe.
