### ISSUE TITLE
Question: async callback ordering

### ISSUE THREAD

**Issue by shmuel-krakower** [shelljs/shelljs#751]
Hello,
I have a question regarding the order in which the stdout.on callback is being called.
I use it to recieve the command output and it seems to me that it is always being called in the right order.
If I make print to console the stdout in async - I always get the right output.

I want to make sure this is to be expected ?
Can I count on the callback to always get the data in the right order?

Best,
Shmuel.

**Comment by nfischer** [comment]
I'm not sure I completely understand your question. Could you provide some example code?

**Comment by shmuel-krakower** [comment]
If I run a command, would it be safe to assume that the stdout events are fired/processed in the right order, so I can concat stdout pieces like in the following example and manipulate it on close?
`
  var child = shell.exec(cmd, {async:true, silent: true});
  var stdoutBuffer = "";

  child.stdout.on('data', function(data) {
    //console.log("Piece of data:" + data);
    stdoutBuffer += data;
  });

  child.on('close', function(){
    console.log("Full data: \n" + stdoutBuffer);
  });
`

**Comment by nfischer** [comment]
Yes, `stdout` callbacks are expected to be called in the correct order.

**Comment by shmuel-krakower** [comment]
Thank you!
