### ISSUE TITLE
Cannot set property to of [object String] which has only a getter

### ISSUE THREAD

**Issue by ilex0208** [shelljs/shelljs#752]
### Example ShellJS command to reproduce the error: shelljs.rm

```javascript
gulp.task('clean', () => {
  if (fs.existsSync(resolveCwd('lib'))) {
    shelljs.rm('-rf', resolveCwd('lib'));
  }
});
```

the error details is：
pipeMethods: [ 'cat','exec','grep', 'head', 'sed','sort','tail', 'to', 'toEnd', 'uniq' ]
cmd cat
cmd exec
cmd grep
cmd head
cmd sed
cmd sort
cmd tail
cmd to
  error TypeError: Cannot set property to of [object String] which has only a getter
cmd toEnd
cmd uniq

that is to say, the 'to' method cannot set property!

**Comment by ilex0208** [comment]
When I used the version less than or equal to 0.6.0, it ran successfully

**Comment by nfischer** [comment]
Why are you trying to set the `.to` property? I don't even see where that's happening in your code.

Full stack trace?

**Comment by ilex0208** [comment]
I don't know why. I just used the code above in gulp.
The exception occurs in shelljs/src/common.js at line 151.
Source code: 
`
pipeMethods.forEach(function (cmd) {
    that[cmd] = shellMethods[cmd].bind(that);
  });
`

**Comment by nfischer** [comment]
@ilex0208 

I have no problems:

```js
// gulpfile.js
var fs = require('fs');
var path = require('path');

var gulp = require('gulp');
var shelljs = require('shelljs');

gulp.task('clean', () => {
  if (fs.existsSync(path.resolve('lib'))) {
    shelljs.rm('-rf', path.resolve('lib'));
  }
});
```

```sh
$ ls -d lib/ &>/dev/null && echo 'The folder exists'
The folder exists
$ gulp clean
[21:57:20] Using gulpfile ~/foobar/gulpfile.js
[21:57:20] Starting 'clean'...
[21:57:20] Finished 'clean' after 6.33 ms
$ ls -d lib/ &>/dev/null || echo 'The folder was deleted'
The folder was deleted
```

Node v6.7.0
Gulp 3.9.1
ShellJS 0.7.8

**Comment by nfischer** [comment]
Can you try to repro with my steps?

**Comment by ilex0208** [comment]
I'm sorry that I can't reply you in time due to too many affairs to deal with recently.

Create a NPM module, directory is as follows

```
ptool/
  bin/
    s-tool.js
  index.js
  package.json
```
s-tool.js

```javascript
    #!/usr/bin/env node

    const program = require('commander');

    program.on('--help', () => {
      console.log('  Usage:');
      console.log('  clean');
    });

    program.parse(process.argv);
    const task = program.args[0];

    if (!task) {
      program.help();
    } else {
      const gulp = require('gulp');
      require('../index');
      gulp.start(task);
    }
```
index.js

```javascript
    const path = require('path');
    const fs = require('fs-extra');
    const shelljs = require('shelljs');

    const gulp = require('gulp');

    function resolveCwd() {
      const args = [].slice.call(arguments, 0);
      args.unshift(process.cwd());
      return path.join.apply(path, args);
    };

    // clean
    gulp.task('clean', () => {
      if (fs.existsSync(resolveCwd('lib'))) {
        shelljs.rm('-rf', resolveCwd('lib'));
      }
    });

    // other task ...
```
package.json

```json
    {
        "name": "s-tool",
        "version": "1.0.0",
        "bin": {
            "s-tool": "./bin/s-tool.js"
        },
        "scripts": {
            "pub": "npm publish"
        },
        "license": "ISC",
        "dependencies": {
            "commander": "~2.9.0",
            "shelljs": "~0.7.8",
            "fs-extra": "^0.26.7",
            "gulp": "^3.9.1"
        }
    }
```

useage:

$ npm install -g s-tool

$ cd workspace
$ s-tool clean

If the folder lib exists, the error occurs.

However, when I used the version less than or equal to 0.6.0, it ran successfully

**Comment by nfischer** [comment]
I still have no repro on Linux.

Please provide a full stack trace from when you reproduce.

Also, please give a repro case using no other modules (only shelljs). I don't know if those other modules are tampering with us.

**Comment by nfischer** [comment]
@ilex0208 any update?

**Comment by nfischer** [comment]
Closing due to lack of response. Please ping this thread again if you can provide more information.

**Comment by zombieJ** [comment]
I found some package modify prototype of `String` makes [`pipeMethods`](https://github.com/shelljs/shelljs/blob/master/src/common.js#L148) add failed failed.

**Comment by nfischer** [comment]
@zombieJ we do not modify the prototype unless you import with `shelljs/global` (which we no longer recommend).

**Comment by zombieJ** [comment]
hi @nfischer ,
I do not mean shelljs change that. I mean other package change the prototype of String makes `that[cmd] = shellMethods[cmd].bind(that)` throw `Cannot set property to of [object String] which has only a getter` error.

**Comment by nfischer** [comment]
@zombieJ ah, thanks for explaining. I would argue this is a bug in the other package, since packages should not modify global prototypes.

Regardless, perhaps we can work around this with #651.

**Comment by ahungrynoob** [comment]
> hi @nfischer ,
> I do not mean shelljs change that. I mean other package change the prototype of String makes `that[cmd] = shellMethods[cmd].bind(that)` throw `Cannot set property to of [object String] which has only a getter` error.

The package you mean is `colorful`, right? https://github.com/lepture/colorful

**Comment by nfischer** [comment]
I don't believe there's anything for us to address here, kindly raise this issue with the `colorful` module.
