### ISSUE TITLE
follow semantic versioning

### ISSUE THREAD

**Issue by dcantelar** [shelljs/shelljs#755]
Hi all!

I think this module is really helpful and many others rely on its functionality. Great job guys!

But, at least for me, it is a little bit confusing to understand why this module doesn't follow [semantic versioning](http://semver.org/), as all the npm modules should do (as described [here](https://docs.npmjs.com/misc/semver)).
The main point here is: if there are breaking changes, it should be a major version increase, so any other breaking change right now should point to 1.0.0 version.

What do you think?

**Comment by nfischer** [comment]
We do follow semantic versioning. Breaking changes are indicated by bumping the minor version if under 1.0.0. I would rather hold off on 1.0.0 at least until we fix security issues surrounding `exec`.

You can get the desired behavior if you specify shelljs as a dependency with something like `^0.7.8`.
