### ISSUE TITLE
  save a string to   file?  (like echo str > outfile.html)

### ISSUE THREAD

**Issue by moorthi07** [shelljs/shelljs#757]
Any ways  to save a string to a file?  (like echo str > outfile.html). 

I'm wondering if I can do this with 'cp' as it solves my rest of the problems in storing a file.. Tx..

**Comment by nfischer** [comment]
https://github.com/shelljs/shelljs#shellstringprototypetofile

If this doesn't answer your question, please ping this bug 😄

**Comment by moorthi07** [comment]
Nope. 
  cat(str).to(dist + '/output.html'); 
throws error -
**cat: no paths given**
and 
creating an empty file output.html

**Comment by freitagbr** [comment]
Do you mean `echo(str).to(dist + '/output.html')`? `cat` prints the contents of a file to stdout, whereas `echo` prints a string to stdout. Judging from your first comment, that's what you wanted to do.

**Comment by moorthi07** [comment]
@freitagbr , great.. echo(str).to(dist + '/output.html')  - works. Thx. But this outputs all 'str' values (I'm doing a recursive loop) in terminal. I'm looking something that does 'copy string to a file' . Is there an option to silent the terminal outputs? or any other options?

**Comment by freitagbr** [comment]
Setting `shell.config.silent = true` should silence terminal output.

**Comment by moorthi07** [comment]
I like to have this feature within shell.js , so I don't need to do fs.writeFile or any other libs. I'm using this for binding templates like cptpl - https://github.com/SBoudrias/mem-fs-editor/blob/master/lib/actions/copy-tpl.js. 
I think a cptpl would be a great add on to the shelljs. 
I'm working on it , I might be able to contribute.

**Comment by moorthi07** [comment]
shell.config.silent = true , not working!

**Comment by nfischer** [comment]
> shell.config.silent = true , not working!

Doesn't work for `echo()`. Please use `new ShellString('foo').to('filename')`.

> I'm looking something that does 'copy string to a file'

The meaning of this isn't very clear. You should either use `.to()` or `.toEnd()` depending on your needs. If you want to copy files, you should use `shell.cp()`.

**Comment by moorthi07** [comment]
sh.ShellString('foo').to('filename') - Worked . Thanks.

**Comment by nickdex** [comment]
@nfischer Hi can you please give an example for typescript? Since ShellString is exported as a type is wont let me create an object ( or use it as a function)

**Comment by nfischer** [comment]
@nickdex I'm sorry, we don't manage the typescript type information (I'm not a typescript user, so I didn't feel comfortable taking on the maintenance burden).

One of these methods should work--if they don't, then I think that's a bug in the type information:

```js
shell.ShellString('foo').to('filename');
new shell.ShellString('foo').to('filename');
```
