### ISSUE TITLE
Results of ls differs: ls('projs/*.js') vs ls(c:/projs)

### ISSUE THREAD

**Issue by moorthi07** [shelljs/shelljs#759]
modelsrcdir = 'c:/somedir/';
 mdirlist = sh.ls('-R',  path.join( modelsrcdir , '/*.json')  );
=> returns:  
c:/somedir/a.json
c:/somedir/b.json

But ,
 mdirlist = sh.ls('-R',  path.join( modelsrcdir)  );  // or even  modelsrcdir + '/'
=> returns:  
a.json
b.json

**Comment by nfischer** [comment]
This is working as intended.

```sh
# show all files matching the name somedir/*.json, relative to the current directory
ls somedir/*.json

# show all contents of somedir/, relative to somedir/
ls somedir/
```

**Comment by moorthi07** [comment]
It is showing content. But one shows with 'Full path' and the other doesn't. Can you post your output for both cases pls.

**Comment by nfischer** [comment]
```
# show all files matching the name somedir/*.json, relative to the current directory
$ ls somedir/*.json
somedir/a.json
somedir/b.json

# show all contents of somedir/, relative to somedir/
$ ls somedir/
a.json
b.json
```

See my comments about "relative to..." That tells you what kind of paths you should expect to see
