### ISSUE TITLE
Discussion: migrate all imports to es6 import

### ISSUE THREAD

**Issue by amilajack** [shelljs/shelljs#762]
Would a PR for this be welcome?

**Comment by freitagbr** [comment]
Well, I'm not sure if this is useful. ShellJS only runs on node, which does not support ES2015 imports (nor does any browser). For the time being, ShellJS will be written using only ES5 constructs for compatibility reasons.

**Comment by amilajack** [comment]
It's useful when used with a module bundler since es6 imports allow for dead code stripping. I'm using shelljs with webpack and electron.

**Comment by freitagbr** [comment]
I see. Module bundlers and tree-shaking are useful for client-side code, where you want to send as little over-the-wire as possible. However, I'm not sure it's so useful for desktop electron apps, which are not sent over-the-wire.

Also, I think ShellJS's use of node's synchronous APIs are more of a performance consideration than dead code is.

I am open to the idea, though. ES2015+ can be transpired to ES5, and our unit tests are already written in ES2015.

**Comment by nfischer** [comment]
I think it's best to postpone until we only support Node versions with native ES2015 support, or we switch to transpiling. I'm going to close this, since there's no immediate action to take.
