### ISSUE TITLE
Shell.js uses wrong terminal shell

### ISSUE THREAD

**Issue by wldcordeiro** [shelljs/shelljs#767]
### Example ShellJS command to reproduce the error:

```javascript
const shell = require("shelljs");
const chalk = require("chalk");
const path = require("path");
const _ = require("lodash");
const minimist = require("minimist");
const emoji = require("node-emoji");

/**
 * Checks for intermittents with one of two strategies:
 * 1. runs each test a number of times
 * 2. groups tests until failing tests are isolated
 *
 * params:
 *  --group enable test grouping
 *  --runs <number> set the number of test runs (default: 10)
 *  --path filters tests given a path
 */

const args = minimist(process.argv.slice(2), {
  boolean: ["group"],
  number: ["runs"],
  string: ["path"]
});

const runs = args.runs || 10;
const testPath = args.path ? `--testPathPattern ${args.path}` : "";
const child = shell.exec(`jest --listTests ${testPath}`, { silent: true });
```

**Comment by nfischer** [comment]
It isn't designed to use your default shell. We use `child_process.execSync`, which uses `/bin/sh` on unix.

Take a look at our [docs](https://github.com/shelljs/shelljs#execcommand--options--callback):

> Not seeing the behavior you want? exec() runs everything through sh by default (or cmd.exe on Windows), which differs from bash. If you need bash-specific behavior, try out the {shell: 'path/to/bash'} option.

---

You don't really need to change the shell for this, you just need to change you `$PATH`. I would recommend doing something like:

```js
shell.env.PATH += path.delimiter + '/path/to/jest/directory';
shell.exec('jest ...');
```

Docs for `path.delimiter` are [here](https://nodejs.org/api/path.html#path_path_delimiter).

**Comment by wldcordeiro** [comment]
@nfischer Thank you! I was getting confused because I had tried setting `$SHELL` and using `SHELL="path/to/shell" node file.js` and had no luck. The docs should surface that a little higher up imo.

**Comment by nfischer** [comment]
@wldcordeiro feel free to send a pull request for a better spot for the docs. Like I said, the real fix is to make sure your `$PATH` is correct, not to change your shell.

**Comment by wldcordeiro** [comment]
@nfischer yeah clearing up in the docs would be best. I was able to modify the `$PATH` like I needed to. 😄
