### ISSUE TITLE
getting different result from terminal and with shelljs 

### ISSUE THREAD

**Issue by anupamvijayvergia** [shelljs/shelljs#769]
### Node version (or tell us if you're using electron or some other framework):
v6.11.3
### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.8
### Operating system:
Ubuntu 16.04 (AWS instance)
### Description of the bug:
I'm trying to execute a shell script from node js file. When I'm executing this script from terminal I'm getting different result from what it returns when executed from nodejs using shelljs 
### Example ShellJS command to reproduce the error:

```javascript
var shell = require('shelljs');
shell.exec('./alphanet.sh status', function(code, stdout, stderr) {
  console.log('Exit code:', code);
  console.log('Program output:', stdout);
  console.log('Program stderr:', stderr);
});
```

here's the link for the script https://github.com/tezos/tezos/blob/alphanet/scripts/alphanet.sh

**Comment by nfischer** [comment]
@anupamvijayvergia is this still an issue?

**Comment by anupamvijayvergia** [comment]
@nfischer it was related to this https://github.com/shelljs/shelljs/issues/680 thanks for checking in!
