### ISSUE TITLE
exec hangs when starting postgres

### ISSUE THREAD

**Issue by ccorcos** [shelljs/shelljs#770]
### Node version (or tell us if you're using electron or some other framework):
v7.10.0

### ShellJS version (the most recent version/Github branch you see the bug on):
^0.7.8

### Operating system:
MacOS

### Description of the bug:

Prerequisites: 
```
brew install postgres
initdb ./db
```

From the commandline, I can start and stop postgres like this:

```
pg_ctl start -w -D ./db
pg_ctl stop -D ./db
```

However when I use shelljs, the command never ends like it does in terminal. 

```
> const shell = require("shelljs")
undefined
> shell.exec("pg_ctl start -w -D ./db")
waiting for server to start....LOG:  database system was shut down at 2017-09-12 21:17:54 PDT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started
```

I'm not sure if there's some low-level thing going on that I don't know about but I'm just trying to start and stop postgres from a Node.js application...

**Comment by nfischer** [comment]
@ccorcos could you please try doing this with a shell script?

```sh
#!/bin/bash
# pg.sh

pg_ctl start -w -D ./db
exit 0
```

And then execute it with:

```sh
$ bash pg.sh
```

Do you see the same results as with Node.js?

**Comment by ccorcos** [comment]
`shell.exec("bash pg.sh")` still hangs.

**Comment by nfischer** [comment]
@ccorcos No, I mean run `bash pg.sh` from your shell (no Node involved)

**Comment by nfischer** [comment]
You can also try `bash pg.sh | cat` and see if that affects anything

**Comment by ccorcos** [comment]
Oh yeah, bash works just the same as running pg_ctl alone. Once the
database starts, it returns control back to the shell. The point is, I'm
coordinating my entire build system using node.js so I need some way of
running this command without it hanging...

**Comment by nfischer** [comment]
Right. My suspicion is that the `pg_ctl` command behaves differently whether it detects a TTY or not.

You can also try using `child_process.execSync('pg_ctl ...')`. and `child_process.execSync('pg_ctl ...', { stdio: 'inherit' })`.

If those provide different results, we can investigate if this can easily be fixed/worked-around for ShellJS.

**Comment by ccorcos** [comment]
Ah yes, this one returned! `child_process.execSync('pg_ctl start -w -D ./db', {stdio: "inherit"})`

**Comment by nfischer** [comment]
Sounds like `pg_ctl` requires running in a TTY (confirming [my suspicion](https://github.com/shelljs/shelljs/issues/770#issuecomment-329307412)).

As a workaround, you can use `child_process.execSync(... { stdio: 'inherit' })` or `shell.exec(... { stdio: 'inherit' })`.

If you need to actually get the stdout from the command, you'll need a different command to script postgres. If there's a trusted npm module for postgres, that would be even better.

Closing this, as there's nothing shelljs can actually do here.
