### ISSUE TITLE
Preserve timestamps on cp?

### ISSUE THREAD

**Issue by goloroden** [shelljs/shelljs#771]
Basically, the title already says it all: Is it possible to preserve the timestamps of files and directories when using the `cp` command?

**Comment by nfischer** [comment]
I don't think we have this functionality. We would need the `-p` flag (see [man page](https://linux.die.net/man/1/cp)).

We also have support for long options, so someone could implement the full `--preserve=` flag if they're ambitious.

PRs are welcome. The unit tests for `touch()` show some examples of checking timestamps.

**Comment by goloroden** [comment]
Okay, thanks :-)

**Comment by iamnapo** [comment]
I'd like to work on that 😃

**Comment by dwi2** [comment]
If no one is working on it, I'd like to give it a shot.

**Comment by nfischer** [comment]
@dwi2 thanks! Go right ahead.

**Comment by michael-ts** [comment]
just noticed that the "-p" option fails under WSL2 when copying to an NTFS destination:

```
(node:3896) UnhandledPromiseRejectionWarning: ShellJSInternalError: EPERM: operation not permitted, fchown
    at Object.fchownSync (fs.js:1068:3)
    at copyFileSync (/home/michael/<...>/node_modules/shelljs/src/cp.js:78:10)
    at /home/michael/<...>/node_modules/shelljs/src/cp.js:308:7
    at Array.forEach (<anonymous>)
    at Object._cp (/home/michael/<...>/node_modules/shelljs/src/cp.js:253:11)
    at Object.cp (/home/michael/<...>/node_modules/shelljs/src/common.js:411:25)

```
Since this has to do with ownership, and all I really need is timestamp preservation, I tried `--preserve=timestamps` but it appears to not be implemented:

    cp: option not recognized: -

**Comment by nfischer** [comment]
If you want `--preserve=timestamps`, please file a new feature request.
