### ISSUE TITLE
Is it possible to get a js library(file) for ShellJS

### ISSUE THREAD

**Issue by parasdiwan** [shelljs/shelljs#776]
Hi 

I wanted to include ShellJs in my project, i wanted to know if it is possible to get JS file for the shellJS library. Is it possible to include it just as a js file or will it be bundled along with nodejs?

**Comment by nfischer** [comment]
I'm a bit confused by the question. We support installing shelljs via `npm`.

You won't be able to get very far using shelljs without node. We rely on tons of node APIs (`fs`, `os`, etc.).

**Comment by parasdiwan** [comment]
Thanks for the quick reply
