### ISSUE TITLE
shell.exec does not recognize 'webpack'

### ISSUE THREAD

**Issue by sriyan** [shelljs/shelljs#781]
### Node version (or tell us if you're using electron or some other framework):
v6.11.2

### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.8

### Operating system:
Windows 10

### Description of the bug:
I tried to run a webpack command through shelljs exec method. But got 
`
'webpack' is not recognized as an internal or external command,
operable program or batch file.
`

### Example ShellJS command to reproduce the error:

```
var command = 'webpack --optimize-minimize --config webpack.config.js';
if (shell.exec(command).code !== 0) {
        shell.echo(`Error occurred while executing: ${command}`);
        shell.exec('pause');
}
```

**Comment by nfischer** [comment]
Check `shell.env.PATH`?

If webpack lives inside your `node_modules/` folder, make sure that you take a look at our [FAQ](https://github.com/shelljs/shelljs/wiki/FAQ).

**Comment by sriyan** [comment]
Thanks, @nfischer. FAQ did the trick.

**Comment by nfischer** [comment]
Glad it worked!
