### ISSUE TITLE
Prevent require()ing executable-only files

### ISSUE THREAD

**Issue by nfischer** [shelljs/shelljs#789]
This was a point raised in #786. We can prevent `require()`ing files with:

```js
if (require.main === module) {
    // everything goes here
}
```

This might be a good idea for files which we only intend to execute (e.g. `bin/shjs`).

I would also consider rewriting as:

```js
if (require.main !== module) {
  throw new Error('Module should not be required');
}
// everything goes here
```

**Comment by freitagbr** [comment]
Failing loudly sounds like a good behavior. That way, you can't even accidentally require the file without node exiting.
