### ISSUE TITLE
Unable to delete multiline between two pattern matching with sed?

### ISSUE THREAD

**Issue by tanepiper** [shelljs/shelljs#806]
### Description of the bug:

Don't seem to be able to pass a sed pattern that will replace the content between two patterns.

In an existing bash script, the line is:

`sed -i '' "/^#BOOTSTRAP_START/,/^#BOOTSTRAP_END/d" ./pipeline_branch.yml`

Trying with:

```javascript
// As sed pattern
sh.sed('-i', '^#BOOTSTRAP_START/,/^#BOOTSTRAP_END', '', 'file.yml');
```

To get this working I had to called exec instead:

```javascript
sh.exec(`sed -i "/^#BOOTSTRAP_START/,/^#BOOTSTRAP_END/d" ${file}`);
sh.exec(`sed -i "/^#RELEASE_START/,/^#RELEASE_END/d" ${file}`);
```

Is there a `shelljs` way of doing this?

**Comment by nfischer** [comment]
Unfortunately, our `sed()` isn't as featureful as unix `sed`, so we only support in-line replacements (the `s/pat/replace/` mode).

---

We do something similar to your request in our [docs-generation script](https://github.com/shelljs/shelljs/blob/master/scripts/generate-docs.js#L30). We wipe out all the text between `## Command reference` and `## Team` using the builtin `String.prototype.replace()` (we actually delete the wrapping text and manually insert it back, but you could just leave that part out). This should be platform-independent.

**Comment by tanepiper** [comment]
@nfischer OK thanks.  I'll stick with the sh.exec for now so I can just use the existing patterns, but thanks for the alternative version in your code.

**Comment by freitagbr** [comment]
Closing this, because the problem was resolved.
