### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by uclides** [shelljs/shelljs#820]
### Node version: 
v8.9.4

### electron version: 
v1.7.11

### ShellJS version: 
v0.8.1

### Operating system: 
Windows 10 x64

### Description of the bug: 

exec: Unable to find a path to the node binary. Please manually set config.execPath

### Example ShellJS command to reproduce the error:

```javascript
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import App from './App'
import router from './router'
import shelljs from '../node_modules/shelljs'

Vue.config.productionTip = false

shelljs.exec('dir')

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  components: { App },
  template: '<App/>'
})

```

**Comment by nfischer** [comment]
Working as intended. Please see https://github.com/shelljs/shelljs/wiki/Electron-compatibility

Is there a way we can document this better? Feedback is welcome 😄
