### ISSUE TITLE
stdout not generated for unrecognised commands

### ISSUE THREAD

**Issue by mrt123** [shelljs/shelljs#821]
### Node version (or tell us if you're using electron or some other framework):
v8.9.1
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.1
### Operating system:
MacOS:  10.12.6
### Description of the bug:
stdout not generated for unrecognised commands
### Example ShellJS command to reproduce the error:

```javascript
const exec = shell.exec('echo hello', {silent: true});
console.log(exec.stdout);    // logs "hello" !

const exec2 = shell.exec('blarg blarg', {silent: true});
console.log(exec2.stdout);    // logs EMPTY LINE!
```
Expected result : should log ```command not found: blarg``` on exec2.stdout

**Comment by nfischer** [comment]
Should be in the `.stderr` attribute instead (because that's an error message). If that's not the case, let's reopen this.
