### ISSUE TITLE
shelljs knows only stuff from /usr/bin and not ~/.bashrc but It's the same shell...

### ISSUE THREAD

**Issue by ffischer1984** [shelljs/shelljs#822]
Hi,
shelljs knows only stuff from /usr/bin and no environment variables from ~/.bashrc but It's the same shell like my terminal window(bin/dash)... tested at ubuntu 16.04, node 7.10.1 and shelljs from npm.

**Comment by nfischer** [comment]
Here's some examples using environmental variables

```js
if (shell.env.ZSH) { // a conditional
  shell.echo('my cache dir is', shell.env.ZSH_CACHE_DIR); // native shelljs command
  shell.exec('git -C ' + shell.env.ZSH + ' show'); // using in exec()
}
```

I advise against `shell.exec('... $some_variable')` -- it's not cross-platform.

@ffischer1984 how does that work for you?

**Comment by nfischer** [comment]
Also, I assume this issue is about `exec()` specifically. `shell.exec()` uses `/bin/sh` on unix. On Ubuntu, `/bin/sh` is implemented by a shell named dash. `/bin/sh` should never look at `.bashrc` though.

**Comment by ffischer1984** [comment]
Hi,
i used a jetbrains-IDE and started my script with the runtimeconfiguration from the IDE. It seems that this runtime-configuration has it own environmental vars because the start from terminal works well ;)
