### ISSUE TITLE
Not able to use shell.exec() command.

### ISSUE THREAD

**Issue by horcrux2301** [shelljs/shelljs#836]
Node version :- v8.10.0
ShellJS version :- 0.8.1
Operating system: macOS Sierra.

Description of the bug:

I am not able to use the shell.exec command. The command I am trying to run is `shell.exec('g++ del.cpp -o del.o')` .Every time I try to use this I get the following error.

`Unable to find a path to the node binary. Please manually set config.execPath`

**Comment by nfischer** [comment]
Well, what's the path to your node binary? Are you using some framework like electron?

**Comment by horcrux2301** [comment]
I am developing a package for the Atom text editor. How do I give it the path to the node binary? And also will this be platform independent, considering I will have to publish this package for others as well.

**Comment by nfischer** [comment]
Atom uses electron, which we don't support. Please see the [wiki](https://github.com/shelljs/shelljs/wiki/Electron-compatibility).
