### ISSUE TITLE
git command does not work with exec

### ISSUE THREAD

**Issue by juliandavidmr** [shelljs/shelljs#839]
- Node version: **8.11.1**
- ShellJS version: **0.8.1**
- Operating system: **MS Windows 8.1**

### Description of the bug:

When I run a git command with the `exec` function it does not work, if I run the same command from the command terminal it does work. When running from Shelljs it returns correct results, i.e. the output code is 0.

### Example ShellJS command to reproduce the error:

I'm trying to remove the proxy settings from git. There are several git command statements for cleaning up the proxy settings, but for this Issue I will refer to one because the problem exists for all other commands.

To recreate the problem, you can quickly create a proxy configuration with the following command _(later you will see how to restore to the initial configuration)_:  `git config --global http.proxy http://username:thepassword%40@server.edu.co:8081` <== _For this example you can use this command as it appears._

Assuming that the previous command has been executed, then we can run `git config --global --get http.proxy` to quickly view the current proxy configuration:

I'm trying to execute the command:

Command line terminal _(If you have configured the git proxy settings with `git config --global http.proxy http.....` then you can delete it with the following command)_:

```bash
git config --global --unset http.proxy
```

app.js 
```javascript
const sh = require('shelljs')

if (sh.exec('git config --global --unset http.proxy').code !== 0) {
    sh.echo('Error: Git unset proxy http failed')
}
```

It is assumed that if you executed the js file then the proxy configuration should be removed as if it were done from the command terminal.

**Comment by nfischer** [comment]
@juliandavidmr Your post seems to contradict itself:

> When running from Shelljs it returns correct results, i.e. the output code is 0.

vs.

> ```js
> if (sh.exec('git config --global --unset http.proxy').code !== 0) {
> ```

What actually happens when you run the git command, wrt exit code?

---

> When I run a git command with the exec function it does not work

Could you clarify, do you mean "when I run **any git** command," "when I run **any command at all**," or "when I run **my specific git command** and not for any other git command?"

---

> if (sh.exec('git config --global --unset http.proxy').code !== 0) {

Ok, but could you give us more information? Like, what is the value of `.stderr` and `shell.error()`? What console output do you see when you run this?

---

Other basic stuff: I assume `git` is a binary in your `PATH`, right?

**Comment by nfischer** [comment]
@juliandavidmr Hmm I see. I'm not as familiar with Windows, so you'll have to do some of the debugging for us. Could you try running these scripts?

In cmd.exe on Windows:

```
> git config --global http.proxy http://username:thepassword%40@server.edu.co:8081
# verify the last command worked by looking at the output
> git config --global http.proxy
> git config --global --unset http.proxy
# verify the last command worked by looking at the output
> git config --global http.proxy
```

And then in shelljs:

```js
var sh = require('shelljs');
sh.exec('git config --global http.proxy http://username:thepassword%40@server.edu.co:8081');
// verify the last command worked by looking at the output
sh.exec('git config --global http.proxy');
sh.exec('git config --global --unset http.proxy');
// verify the last command worked by looking at the output
sh.exec('git config --global http.proxy');
```

Please post the full script output.

**Comment by juliandavidmr** [comment]
**The results obtained are:**

In cmd.exe on Windows:

```bash
> git config --global http.proxy http://username:thepassword%40@server.edu.co:8081
# Successfully executed. It doesn't show anything, it's assumed that he executed correctly.
> git config --global http.proxy
# Return: http://username:thepassword%40@server.edu.co:8081
> git config --global --unset http.proxy
# It doesn't show anything, it's assumed that he executed correctly
> git config --global http.proxy
# It doesn't show anything. The proxy has been eliminated.
```

And then in shelljs:

```js
var sh = require('shelljs');
sh.exec('git config --global http.proxy http://username:thepassword%40@server.edu.co:8081');
// stdout: '',  String: '', stderr: '', code: 0

sh.exec('git config --global http.proxy');
// stdout: '',  String: '', stderr: '', code: 0

sh.exec('git config --global --unset http.proxy');
// stdout: '',  String: '', stderr: '', code: 0

// verify the last command worked by looking at the output
sh.exec('git config --global http.proxy');
// stdout: '',  String: '', stderr: '', code: 0
```

> Note that all previous operations were executed with the cmd.exe administrator mode, it was also attempted without this mode.

**Comment by juliandavidmr** [comment]
The whole code is [here](https://github.com/juliandavidmr/state_proxy_git). I'm actually making an npm library to quickly change the proxy settings of various tools. Thanks for the help :)

**Comment by nfischer** [comment]
> For some unknown reason, the cmd is minimized every time I run a shelljs function. Maybe this is relevant, I'm not sure if it has anything to do with it.

Hmm you mean the terminal window gets minimized, then un-minimized? Or do you mean that `sh.exec()` spawns a new `cmd.exe` window? I'm not familiar with either happening in shelljs, but the latter sounds a lot like how vim-plug spawns processes on Windows, so I suppose it might happen for shelljs too.

> ```js
> // verify the last command worked by looking at the output
> sh.exec('git config --global http.proxy');
> // stdout: '',  String: '', stderr: '', code: 0
> ```

This is unexpected. It seems like all of your git operations are NOOPs.

---

According to [this post](https://superuser.com/questions/207707/what-is-windows-equivalent-of-the-which-command-in-unix-is-there-an-equivale), `where` is Windows' equivalent to unix's `which`. Could you try running this in `cmd.exe`?

```
> where git
> node -p "require('shelljs').which('git')"
> node -p "require('shelljs').exec('where git')"
> # Make sure all of these match.
```

**Comment by juliandavidmr** [comment]
Apparently the difference in outputs from the `where` is the problem. I have renamed the file `git.js` to `git_lib.js`, now the git commands are executed correctly and the `.exec('where git')"` shows only the `git.exe`. I think this is a reproducible problem, you could try to create it to evaluate the functionality of where in Shelljs.

**Comment by nfischer** [comment]
@juliandavidmr this has to do with how Windows handles executing commands. I think the priority is: if trying to execute a command `foo`, search in the CWD for `foo.exe`, `foo.bat`, etc. (based on the PATHEXT variable), then search similarly through each directory in PATH until a match is found.

On your machine, `.js` files can be executed by `node`, so the extension is in PATHEXT. So, `git` matches `./git.js` first. I'll wager you're running your script from the `state_proxy_git/` folder, and you'll see different behavior if you move `git.js` into a sub folder.

Renaming the file like you did is probably the best workaround :smile: Another idea:

```js
var git = shell.which('git');
shell.exec(`${git} config ...`);
```

Out of curiosity, what's the output of:

```
> echo %PATH%
> echo %PATHEXT%
```

---

It's not clear if shelljs can/should do anything about this. `exec()` just defers to the OS to do most of the work.

> I think this is a reproducible problem, you could try to create it to evaluate the functionality of where in Shelljs.

Again, not clear if we can/should change. It's weird that `shell.which('foo')` returns one `foo`, but `shell.exec('foo')` executes a different one. On the other hand, if we change `which()`'s algorithm, then it would return different results on windows vs. unix, which is also bad.

**Comment by juliandavidmr** [comment]
Hi @nfischer, the output of:

```bash
> echo %PATH%
C:\ProgramData\Anaconda2;C:\ProgramData\Anaconda2\Library\mingw-w64\bin;C:\ProgramData\Anaconda2\Library\usr\bin;C:\ProgramData\Anaconda2\Library\bin;C:\Pro
nda2\Scripts;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System3
Shell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files\Micr
form Installer\;C:\cygwin64\bin\;C:\Windows\System32;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\wamp64\bin\php\php5.6.25;C:\composer;C:\Program Files\do
rogram Files (x86)\GtkSharp\2.12\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Use
pData\Local\.meteor\;C:\Users\jul.mora\AppData\Local\GitHubDesktop\bin;C:\Program Files (x86)\Nmap;C:\Program Files\Microsoft VS Code\bin;C:\Windows\System3
.mora\AppData\Roaming\Composer\vendor\bin;C:\wamp64\bin\php\php5.6.25;C:\Users\jul.mora\AppData\Local\atom\bin;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Us
ppData\Roaming\npm;C:\Users\jul.mora\AppData\Local\Yarn\bin;C:\Program Files\heroku\bin

> echo %PATHEXT%
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
```

**Comment by nfischer** [comment]
Thanks. Based on that, I'm not sure if there's anything we can do. It would appear that `.` is a magic entry: windows seems to prefer executing local files (in `.`) over anything in `PATH`. It seems this is an inherent difference in how unix and windows operate, with no clear way to workaround windows quirks.

I'll close this, because it seems that renaming your js file is the optimal workaround.
