### ISSUE TITLE
silent does not always work

### ISSUE THREAD

**Issue by GuyMograbi** [shelljs/shelljs#851]
node 8.9.1
shelljs 0.8.1
mac osx

I expect this code to not produce any output but it does. 

```
const shell = require('shelljs');

shell.exec('git rev-parse --abbrev-ref  master2@{upstream}', {silent:true});
```

Run it in a git repository that does not have a branch `master2` and you should see an error printed

```
exec: fatal: no such branch: 'master2'
```

**Comment by nfischer** [comment]
Thanks for reporting. I can repro:

```js
> exec('ls somefakefilethatdoesntexist')
ls: cannot access 'somefakefilethatdoesntexist': No such file or directory
exec: ls: cannot access 'somefakefilethatdoesntexist': No such file or directory

> exec('ls somefakefilethatdoesntexist', { silent: true })
exec: ls: cannot access 'somefakefilethatdoesntexist': No such file or directory
```

This is a regression after v0.7.x. We should not output the lines with the `exec` prefix. I'll try to write up a quick fix.

**Comment by uttpal** [comment]
@nfischer Hey, can I try to fix this issue?

**Comment by nfischer** [comment]
@uttpal sure thing. This issue fell off my radar.

**Comment by uttpal** [comment]
@nfischer I raised a pr can you take a look, thanks!

**Comment by RamyRais** [comment]
when can we have the PR merged?

**Comment by nfischer** [comment]
@RamyRais the PR should be good, but I want to fix CI first. I'll try to work on this.
