### ISSUE TITLE
TypeError: spawn is not a function

### ISSUE THREAD

**Issue by ankitakhatri** [shelljs/shelljs#853]
### Node version (or tell us if you're using electron or some other framework):
Node Version: v8.11.2
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.2
### Operating system:
Mac OS High Sierra
### Description of the bug:
I am trying to run a test.sh file that prints "hello world" through my react app using shelljs.
This line: const ls = spawn('ls', ['-lh', '/usr']); is throwing a Type Error: spawn is not a function 
### Example ShellJS command to reproduce the error:
const { spawn } = require('child_process');
const ls = spawn('ls', ['-lh', '/usr']);
const child_process = require('child_process');
const { exec } = child_process.exec;
exec('./test.sh', (err, stdout, stderr) => {
  if (err) {
    return;
  }
// the *entire* stdout and stderr (buffered)
  console.log(`stdout: ${stdout}`);
  console.log(`stderr: ${stderr}`);
});
```javascript

```

**Comment by nfischer** [comment]
Your example code never uses shelljs. We do not maintain the child_process module.

**Comment by nfischer** [comment]
I assume this was filed by mistake, but let me know if I've misunderstood.
