### ISSUE TITLE
How to open multiple separate instances of shells in one .js file?

### ISSUE THREAD

**Issue by adityank** [shelljs/shelljs#865]
### Example ShellJS command to reproduce the error:

```javascript

```

**Comment by nfischer** [comment]
We don't support this. The shelljs module depends on (and manipulates) global state, such as working directory, env variables, file system, etc.

If you could elaborate more on your specific use-case, perhaps we can advise a solution.

**Comment by adityank** [comment]
I want to execute commands in parallel and keep them separate. I do that manually by opening multiple terminals. But now I want to automate it.

**Comment by nfischer** [comment]
The way to do this in bash is to use multiple shells (which of course happens when you open multiple terminals).

I recommend you write multiple `.js` files, and run each one in a separate process (which you could spawn from one master/bootstrap script). It would look something like:

```js
// bootstrap.js

var shell = require('shelljs');

shell.exec('node file1.js', { async: true });
shell.exec('node file2.js', { async: true });
// ...

// Each of file{*}.js will run in a separate process, and can each use shelljs without
// interference.

// bootstrap.js will automatically wait until all exec()s have finished
```

**Comment by adityank** [comment]
Thank you! I will try.

**Comment by nfischer** [comment]
Right. You can provide CLI arguments like so:

```js
// bootstrap.js

shell.exec('node file1.js foo bar', { async: true });
```

And you can retrieve these arguments with:

```js
// file.js

var args = process.argv.slice(2); // optionally, check out the minimist module
// `args` is [ 'foo', 'bar' ]
```
