### ISSUE TITLE
Variable usage with shell.sed() doesn't recognize JS variable

### ISSUE THREAD

**Issue by srashee** [shelljs/shelljs#875]
Node version (or tell us if you're using electron or some other framework): v8.11.3
ShellJS version (the most recent version/Github branch you see the bug on): 0.8.2
Operating system: Windows 10
Description of the bug: Sed command unable to interpret variables from JS file.
Example ShellJS command to reproduce the error:

I'm using const shell = require('shelljs')
and in my post function i run the following command

shell.sed('-i', TEXTTOREPLACE, '${REPLACEMENTVARIABLE}', 'textfile.txt')

**Comment by srashee** [comment]
I apologize, here's the output I get below.

ERROR: '${REPLACEMENTVARIABLE}' is an invalid name. Valid names MUST begin with a letter or number, have between 2-50 chars, including letters, n
umbers, underscore, dot and dash

**Comment by nfischer** [comment]
@srashee it's hard to understand what the expected result is. Could you elaborate?

Are `TEXTTOREPLACE` and `REPLACEMENTVARIABLE` supposed to be JS variables? `'${REPLACEMENTVARIABLE}'` is not correct syntax for es6 template literals (and, you don't need template literals for this example).

---

For future reference, [fenced code blocks](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) help with formatting. Also, the bug template's default formatting helps a bit with readability too.

**Comment by srashee** [comment]
I apologize for being vague. Yes they are JS results that I retrieve using bodyparser. I store it in a variable called replacementvariable

**Comment by srashee** [comment]
I apologize, very silly mistake. Your comment about my variable using the wrong syntax is why the error was occurring. I needed to change it to backticks.
