### ISSUE TITLE
passphrase

### ISSUE THREAD

**Issue by rakesh-agrawal** [shelljs/shelljs#882]
### Description of the bug:

We are executing a ssh command using shelljs. It works perfectly fine when the pem file in not protected via passphrase. Is there a way that we can pass the passphrase using shelljs ?

### Example ShellJS command to reproduce the error:

```javascript

```

**Comment by nfischer** [comment]
This is not currently supported. To clarify, do you mean:

 1. Launch `ssh` via `shell.exec()`, and allow the user to interactively type their passphrase in the console when `ssh` prompts them, or
 2. Launch `ssh` via `shell.exec()`, and programmatically supply credentials.

(1) is a design goal for #866. (2) has obvious security implications.

---

You can also take a look at [shelljs-plugin-ssh](https://github.com/MatthieuLemoine/shelljs-plugin-ssh). This is a 3rd party plugin which we do not maintain, but it may have better support for what you're trying.

**Comment by nfischer** [comment]
Closing this.

 * I think the ssh use-case is probably best solved by the 3rd party ssh plugin. I haven't reviewed this plugin yet, so I can't comment on the security/implementation of the code.
 * I think general input concerns will be resolved by #866.
