### ISSUE TITLE
How to exit shell.exec async?

### ISSUE THREAD

**Issue by bantilan** [shelljs/shelljs#884]
Guys, I am new to node js.. I am running shell.exec with async and found out it still running on the background inside stdout.on.. How to exit the shell.exec in async?

Here is my code..

```
var child = shell.exec('echo test', {async:true});

child.stdout.on('data', function(data) {
  console.log(data);
  //how to exit and to stop this from running in the background..
});
```

**Comment by nfischer** [comment]
You can exit with [`child.kill()`](https://nodejs.org/api/child_process.html#child_process_subprocess_kill_signal). But why would you want to? The process is not done after the first `data` event. If you're waiting for a particular line of output, and terminating after that, then `child.kill()` might be more reasonable.

**Comment by csomakk** [comment]
i for one want to kill it, when i need to restart the process ;) thanks for answer 👍
