### ISSUE TITLE
shell.exec('npm pack') painfully slow

### ISSUE THREAD

**Issue by pfms84** [shelljs/shelljs#885]
### Node version (or tell us if you're using electron or some other framework):
10.9.0
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.2
### Operating system:
Windows 10
### Description of the bug:
With the version 6 of NPM, shell.exec('npm pack') or shell.exec('npm publish') became painfully slow.

### Example ShellJS command to reproduce the error:

```javascript
console.time('execution-time');
if (shell.exec(`npm pack`).code !== 0) {
    process.exit(-1);
}
console.timeEnd('shell.exec(\'npm pack\')'); // shell.exec('npm pack'): 189658.260ms
```

**Comment by nfischer** [comment]
> With the version 6 of NPM, shell.exec('npm pack') or shell.exec('npm publish') became painfully slow.

Hmmm this wasn't slow with `npm@v5`? Can you provide timing values for v5 so we can compare?

Can you also give us timing values for running `npm pack` in the terminal?

**Comment by pfms84** [comment]
with npm@v5, 2111.266ms for the same folder.
with npm@v6, npm pack runs almost instantly if used directly, but I noticed something strange and probably the problem isn't related with shelljs, but with npm itself.
Running Measure-Command { npm pack } took 188976,3689ms, which is basically the same time it took with shelljs.
Ok, I think you can close this issue, the problem is with npm itself (or maybe node.js). npm starts 2 node.js processes and they keep running for ages.

**Comment by nfischer** [comment]
Closing for now, but let me know if there's anything we need to do on the shelljs-side. Thanks for further investigation!
