### ISSUE TITLE
Do not spam terminal with logging messages

### ISSUE THREAD

**Issue by cschroeter** [shelljs/shelljs#887]
### Node version (or tell us if you're using electron or some other framework):
10.8.0

### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.2

### Operating system:
MacOS

### Description of the bug:
Logs sdterror on console if you try to execute an unknown command. 

### Expected behavior:
Do not log stderror on console

### Example ShellJS command to reproduce the error:

```javascript
const { stdout } = await shell.exec(`dpkg -l | grep ${packageName} | awk '{print $3}'`);
```

```
dpkg-query: error: failed to open package info file '/usr/local/var/lib/dpkg/status' for reading: No such file or directory```

**Comment by nfischer** [comment]
```js
shell.config.silent = true;
// Or, for exec-only fix...
shell.exec(someCommand, { silent: true });
```

https://github.com/shelljs/shelljs#configsilent
