### ISSUE TITLE
typescript definition has to be updated

### ISSUE THREAD

**Issue by tanekim88** [shelljs/shelljs#888]
### Node version (or tell us if you're using electron or some other framework):
most recent
### ShellJS version (the most recent version/Github branch you see the bug on):
most recent
### Operating system:
any
### Description of the bug:
shelljs typescript definition misses ShellString method.
### Example ShellJS command to reproduce the error:
after installing through npm i -D @types/shelljs
import shell from 'shelljs'
shell.ShellString throws an error saying the method does not exists.
```javascript

```

**Comment by nfischer** [comment]
We don't maintain those definitions currently. We're discussing moving them into this repository (#736)

**Comment by nfischer** [comment]
Closing this old ticket. We don't currently maintain the typing information in this repo. Please file a bug against https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/shelljs/index.d.ts if you're still running into this.
