### ISSUE TITLE
Garbled

### ISSUE THREAD

**Issue by xcsweb** [shelljs/shelljs#912]
### Example ShellJS command to reproduce the error:

![image](https://user-images.githubusercontent.com/20693737/49267175-26514e80-f494-11e8-970f-ec0be5346296.png)
![image](https://user-images.githubusercontent.com/20693737/49267183-323d1080-f494-11e8-82a6-635dc50c7b13.png)

**Comment by nfischer** [comment]
Related to #675 perhaps? @xcsweb can you try @freitagbr's `{ encoding: 'buffer' }` option?

**Comment by xcsweb** [comment]
![image](https://user-images.githubusercontent.com/20693737/49273602-81913a00-f4b0-11e8-86f7-3bd68d8f53db.png)
![image](https://user-images.githubusercontent.com/20693737/49273614-89e97500-f4b0-11e8-99be-aaa71bda33b9.png)
@nfischer

**Comment by nfischer** [comment]
@xcsweb it's not clear where the output is coming from. Can you paste the full contents of `copy.js`?

Also, I would recommend you to rewrite that code snippet as:

```js
var shell = require('shelljs');
var os = require('os');

shell.cd('../../backstageupload');
// I assume you actually want to exclude files ending with ".svn", which your
// original regex didn't correctly specify.
var nonSvnFiles = shell.ls().grep('-v', '\\.svn$').split(os.EOL);
shell.rm('-rf', nonSvnFiles);
```

**Comment by xcsweb** [comment]
var child_process = require('child_process');
var readline = require('readline')
var util = require('util');
var shell = require("shelljs");
function copy(source, target, callback) {
    child_process.exec(
        util.format('cp -r %s/* %s', source, target), callback);
}

//清空目录
shell.exec(`cd ../../backstageupload;ls | grep -v .svn | xargs rm -rf`,{encoding:'buffer'})

// shell.exec(`ls`)
// shell.exec(`cd ../../backstageupload;rm -rf !(.svn)`)
// shell.exec(`ls | grep -v .svn | xargs rm -rf`)
//复制
copy("./dist", '../../backstageupload', function(err) {
    if (err) {
        console.log(err)
    }
});
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});
rl.question('是否提交(y/n)', (answer) => {
    if (answer === 'y') {
        submit()
    } else {
        rl.close();
    }
})

function submit() {
    rl.question('请输入提交信息:  ', (answer) => {
        //提交文件
        shell.exec(`svn propset svn:ignore node_modules`)
        shell.exec(`svn add * --no-ignore`)
        shell.exec(`svn ci -m ${answer}`);

        rl.close();
    });
}

**Comment by nfischer** [comment]
Not sure why you're seeing bad output. Might be an issue if your locale is not `utf-8`, although I don't think any of those commands should be creating output.

Also, you should try to avoid `exec()` whenever possible.

**Comment by nfischer** [comment]
You might try looking at the return value from `shell.exec()`. In particular, look at its `.stdout` and `.stderr` properties (I would expect them to be empty).

Not sure how else I can help debug. But if you can explain if there's a specific bug with `exec()`, I'm happy to take another look.

**Comment by xcsweb** [comment]
![](https://user-gold-cdn.xitu.io/2018/11/30/167643e669e2c462?w=460&h=38&f=png&s=3856)
![](https://user-gold-cdn.xitu.io/2018/11/30/167643f625ec9548?w=156&h=45&f=png&s=2590)
it's ok
but
![](https://user-gold-cdn.xitu.io/2018/11/30/167643ee17711061?w=379&h=26&f=png&s=3434)
![](https://user-gold-cdn.xitu.io/2018/11/30/1676440162aa28c6?w=150&h=57&f=png&s=3389)

![](https://user-gold-cdn.xitu.io/2018/11/30/1676440772365171?w=963&h=81&f=png&s=11707)
![](https://user-gold-cdn.xitu.io/2018/11/30/16764412af72d262?w=585&h=84&f=png&s=7181)

**Comment by nfischer** [comment]
I don't understand why `cd path;` would spit output while `cd path` does not. I can't reproduce this.

I can't help anymore unless you fill out the required fields in the Github issue template (node version, shelljs version, operating system).

And again, you can fix your bug by rewriting this to use real ShellJS methods, **not** `exec()`. Check out `shell.cd()` API docs.

**Comment by Hunlongyu** [comment]
@xcsweb 大兄弟我也出现乱码的情况，你的这个问题解决了么
