### ISSUE TITLE
Only get stdout from `exec`

### ISSUE THREAD

**Issue by SBoudrias** [shelljs/shelljs#92]
When running `exec` in sync mode, you only have access to `output` which is a merge of `stdout` + `stderr`.

Would it be possible to have the content of each one of these individually when using the sync exec?

**Comment by agoston** [comment]
+1

**Comment by rexim** [comment]
+1

**Comment by Zhongtang** [comment]
+1

**Comment by nfischer** [comment]
@SBoudrias Thanks for reporting this! This should be fixed in v0.6. The new preferred attribute is `stdout` (because `output` sounds ambiguous). `stdout` only contains `stdout` (and now there's a new `stderr` attribute as well!). If this is not correct, please feel free to re-open

**Comment by Newlifer** [comment]
+1
