### ISSUE TITLE
find returns empty array even though directory has files

### ISSUE THREAD

**Issue by jamestharpe** [shelljs/shelljs#922]
### Example ShellJS command to reproduce the error:

```javascript

```

**Comment by nfischer** [comment]
@jamestharpe it's not clear why you closed this--was this filed by mistake?

`find()` should work (we integration-test it), but please note that the syntax is quite different from unix `find`.

**Comment by jamestharpe** [comment]
Yes, filed by mistake. Thought I was searching :). Issue was on my end.
