### ISSUE TITLE
what is the sed result without -i ?

### ISSUE THREAD

**Issue by qiulang** [shelljs/shelljs#930]
### Node version (or tell us if you're using electron or some other framework):
10.15
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.3
### Operating system:
macOS
### Description of the bug:
What is the the sed result without -i ?    `shell.sed(/search/, 'replaced', files)`

I can't find the document about that, I tried it and have no idea of the result.

**Comment by nfischer** [comment]
The return value is the same. The difference is that `-i` means to modify the file in-place as a side-effect (without `-i`, the file is unmodified).

**Comment by nfischer** [comment]
This is going to change in the next shelljs release for unix compatibility: #959
