### ISSUE TITLE
Unable to run commands after using a non return command

### ISSUE THREAD

**Issue by SibeeshVenu** [shelljs/shelljs#931]
Hi, 

Thanks a lot for the wonderful plugin. I am using this plugin to build an app manager tool, which basically updates my docker containers running in my machine. From my node application, I am starting the Angular CLI application using this plugin, and it works fine. 

```
app.get('/', (req, res) => {
  runAppManager();
  res.send('Server started');
});

function runAppManager(){
  shell.exec('npm start --prefix /home/ApplianceManager', { silent: false, async: true }).stdout;
}
```

But the issue is whenever we run any non-returning commands as `ng serve`, the next commands are not executing. Basically once my angular application is loaded I need to check the docker container versions and execute `docker-compose up`, as my docker-compose file have an asp.net core image to run, after running, I am facing the same issue. 

> user@lz:~/node$ node server
 
> app-manager@0.0.0 start /home/ApplianceManager
> ng serve

>** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

>Date: 2019-01-26T16:05:29.039Z
>Hash: 5e2842c7dbd96ca17a27
>Time: 38630ms
>chunk {main} main.js, main.js.map (main) 35 kB [initial] [rendered]
>chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 236 kB [initial] [rendered]
>chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
>chunk {styles} styles.js, styles.js.map (styles) 179 kB [initial] [rendered]
>chunk {vendor} vendor.js, vendor.js.map (vendor) 7.03 MB [initial] [rendered]
>ℹ ｢wdm｣: Compiled successfully.

What should I do in this case? Any help is really appreciated.

**Comment by nfischer** [comment]
> But the issue is whenever we run any non-returning commands as ng serve, the next commands are not executing.

I'm afraid I don't quite follow. Where is `ng serve` in your example?

**Comment by SibeeshVenu** [comment]
> > But the issue is whenever we run any non-returning commands as ng serve, the next commands are not executing.
> 
> I'm afraid I don't quite follow. Where is `ng serve` in your example?

I am using `npm start` which internally call `ng serve`. The issue I am facing is applicable for all the non-returning commands, for example, `docker-compose up` and `docker run` `npm start` `ng serve` etc.

**Comment by SibeeshVenu** [comment]
So in this case, should I start a new node with a different port and run the non-returning commands there?

**Comment by SibeeshVenu** [comment]
Sorry if it is not clear enough. Let me say it in detail. I have an Angular application and a node server when the Angular application loads I will find the local docker containers running (`docker ps --format "{{.Image}}"`), using the node middleware api. 

```
app.get('/version', (req, res) => {
  let commands = req.query.commands;
  let objCommands = JSON.parse(commands);
  if (objCommands) {
    if (objCommands.length === 1) {
      // Making asynch true will give you TypeError: Converting circular structure to JSON at JSON.stringify (<anonymous>)
      res.send(shell.exec(objCommands[0], { silent: false, async: false }).stdout);
    } else {
      objCommands.forEach((command) => {
        shell.exec(command, { silent: false, async: false }).stdout;
      });
      res.send('Successfully executed all the commands');
    }
  }
});
```
Now after running non returning queries like `docker run`, if I again run the api with any commands like `docker ps --format "{{.Image}}"` the API won't run, as the previous command didn't return anything. My ultimate aim is to show a progress bar, and show the command output in the Angular Component.

Please let me know if you need any further details.

**Comment by nfischer** [comment]
This is outside of the scope of shelljs, and I think you'll find better results asking on stackoverflow (I really don't know what your app's requirements are).

Keep in mind, `shell.exec(cmdWhichNeverFinishes)` will never finish, and your event loop will be tied-up forever. You'll need look carefully at the async API (we have docs for this on the README).
