### ISSUE TITLE
How to execute `wasm-gc in.wasm -o out.wasm` in my JS function??

### ISSUE THREAD

**Issue by AchalaSB** [shelljs/shelljs#932]
### Node version
11.7.0

### ShellJS version 
0.8.3

### Operating system:
Linux

### Description of the bug:
This code is not giving me expected result. Here input is `.wasm` file, the code is taking the input and giving back output in `.wasm` format only. But `wasm-gc` operation is not happening. Instead it giving the original input file
```
async function wasmGC(wasmFile) {
  if (!await exists(wasmFile)) {
    throw new Error("wasm is not found")
  }
  await exec(joinCmd([wasmGCCmd, wasmFile]));
  return wasmFile;
}
```
The command  exported like this `exports.wasmGCCmd = homeDir + '/.cargo/bin/wasm-gc';`

How to reproduce it/ what is the way to get correct result?? 

By using shelljs how can I write my code?? Am not getting to write it using shelljs

TIA

**Comment by nfischer** [comment]
@AchalaSB I don't see where you're using ShellJS in your code snippet, so I don't know how to help.

Does `wasm-gc` work as expected on the bash command line?

**Comment by AchalaSB** [comment]
@nfischer In the above code I did not use shelljs. For the above code I didn't get expected result so I thought of using Shelljs( hope it may work)
Or if you know to correct the above code plz help

But I don't know the way to write code

Yeh the above command working fine in command line

**Comment by nfischer** [comment]
Can you provide a complete code sample? It's not clear where you're importing/defining `exec()` or `joinCmd()`.

**Comment by nfischer** [comment]
Is this still an issue?
