### ISSUE TITLE
shell.which returns object

### ISSUE THREAD

**Issue by chrispahm** [shelljs/shelljs#933]
### Node version (or tell us if you're using electron or some other framework):
Using Shell.js in an Atom (1.34) plugin, => Electron 2.0.12
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.3
### Operating system:
macOS
### Description of the bug:
`shell.which('command')` returns an object instead of a string
### Example ShellJS command to reproduce the error:
```javascript
const test = shell.which('git')
console.log(typeof test) // yields 'object' instead of 'string'
```
### Current workaround (hack) until fix is available
```javascript
let test = shell.which('git')
if (test) {
  test = JSON.parse(JSON.stringify(test))
}
```

**Comment by nfischer** [comment]
By design, this returns a [ShellString](https://github.com/shelljs/shelljs#shellstringstr). For your use-case, just call `shell.which('git').toString()`.

**Comment by nfischer** [comment]
Let me know if you think there's anything we should do to make this clearer.

**Comment by chrispahm** [comment]
Thanks a lot @nfischer for the clarification! I didn’t read the whole Readme, but only the shell.which part and got confused where it says “returns string...”. My bad! However, if this part would say “returns ShellString” with a link to that part of the documentation I guess it would be even  clearer. If you like, I could do a quick PR, if not, it’s absolutely fine as well.

**Comment by nfischer** [comment]
Ah, that is a docs bug. PRs would be welcome.

**Comment by nfischer** [comment]
Actually, I realized most of our docs should get updated. I'll handle this.

**Comment by chrispahm** [comment]
@nfischer thanks a lot!
