### ISSUE TITLE
Solution to apostrophes within filenames used in shell commands?

### ISSUE THREAD

**Issue by HaveAGitGat** [shelljs/shelljs#938]
### Node version (or tell us if you're using electron or some other framework):
v10.15.3
### ShellJS version (the most recent version/Github branch you see the bug on):
"shelljs": "^0.8.3",
### Operating system:
Windows 10
### Description of the bug:
Apostrophes in filenames causing this error:
`Syntax Error "(" unexpected`

### Example ShellJS command to reproduce the error:

`nice -n 10 HandBrakeCLI -i '/home/haveagitgat/Desktop/Input/Test's.mp4' -o '/home/haveagitgat/Desktop/Output/Test's.mp4' -Z "Very Fast 1080p30`

I've tried using double quotes around the file names but then I get errors when filenames contain special characters such as '$'.

References:
https://github.com/HaveAGitGat/HBBatchBeast/issues/21
https://github.com/HaveAGitGat/HBBatchBeast/issues/32

Any solutions without having to rename the files?

**Comment by chrispahm** [comment]
Hey there,

I used to run into the same issue, but stumbled upon [this stackoverflow](https://stackoverflow.com/a/7685469/6213343) post back then, which presents the following simple function as a solution to escape the shell command string:

```js
function escapeShell(cmd) {
  return '"'+cmd.replace(/(["\s'$`\\])/g,'\\$1')+'"'
}
``` 

Hope this is what you are looking for!

**Comment by tracker1** [comment]
Minor variation/addition to @chrispahm's reply...

```
const e = p => `"${p.replace(/(["\s'$`\\])/g,'\\$1')}"`;
...
const in = '/home/haveagitgat/Desktop/Input/Test's.mp4';
const out = '/home/haveagitgat/Desktop/Output/Test's.mp4';
shell.exec(`doSomethingWith -i ${e(in)} -o ${e(out)}`);
```

NOTE: window's shell doesn't support apostrophes/single-quote as a parameter enclosure...

**Comment by HaveAGitGat** [comment]
@chrispahm @tracker1

Thank you. Yeah I haven’t had any problems on Windows as I put double quotes around the commands. I’ll try your suggestions on my following code:

```
workerCommand ="nice -n "+runPriority+" HandBrakeCLI -i '" + currentSourceLine + "' -o '" + currentDestinationLine + "' " + preset

shellWorker = shell.exec(workerCommand, function(code, stdout, stderr,stdin) {

});
```

**Comment by nfischer** [comment]
This was an explicit goal for [nfischer/shelljs-exec-proxy](https://github.com/nfischer/shelljs-exec-proxy), although I can't remember how close the project is to working on Windows (some [tests are failing](https://ci.appveyor.com/project/shelljs/shelljs-exec-proxy/build/job/uxm03r5ogojgcia6), but that could be bugs in the test rather than the project).

**Comment by HaveAGitGat** [comment]
@nfischer  thanks for that. I tried it on Linux with the following but no luck:

```
var shell = require('shelljs-exec-proxy')
var currentSourceLine = "/home/haveagitgat/Desktop/1/1'.mp4"
var currentDestinationLine = "/home/haveagitgat/Desktop/2/1'.mp4"
workerCommand ="HandBrakeCLI -i '" + currentSourceLine + "' -o '" + currentDestinationLine + "' " + "-Z \"Very Fast 1080p30\"";

shellWorker = shell.exec(workerCommand, function(code, stdout, stderr,stdin) {});
```

I get this error due to an unterminated string:

`Missing output file name.`

**Comment by nfischer** [comment]
You're **not** supposed to call `shell.exec()`. The point of the `shelljs-exec-proxy` project is to use it like:

```js
shell.HandBrakeCLI('-i', currentSourceLine, '-o', currentDestinationLine, '-Z', 'Very Fast 1080p30');
```

**Comment by HaveAGitGat** [comment]
Thanks that actually works perfectly, much appreciated.

**Comment by nfischer** [comment]
We're looking to add a similar (and more secure) solution to ShellJS proper. That work is tracked in #495. For now, I believe `shelljs-exec-proxy` should handle most security/usability concerns.
