### ISSUE TITLE
No option is provided for shelljs.rm() to first remove files to the system recycle bin.

### ISSUE THREAD

**Issue by alloutnow** [shelljs/shelljs#941]
### Node version (or tell us if you're using electron or some other framework):
Node 12.3.1 (64-bit)

### ShellJS version (the most recent version/Github branch you see the bug on):
v: 0.8.3

### Operating system:
Microsoft Windows 10 Pro - V: 10.0.17763 Build 17763

### Description of the bug:
No option is provided for shelljs.rm() to first remove files to the system recycle bin.

### Example ShellJS command to reproduce the error:
shell.rm('-r', path.join(sourceDir, nameOfFile));

```javascript

```

**Comment by nfischer** [comment]
For this, I think you need to just use `shell.mv()`.

This seems to not be implemented for WSL, and I'd prefer to wait until there's precedent before we add non-standard options: https://github.com/MicrosoftDocs/WSL/issues/257. Please let me know if you know of other Windows implementations of `rm` which support this.
