### ISSUE TITLE
shell.exec('bash') don't work on debian 9 konsole

### ISSUE THREAD

**Issue by shubhamrsangle** [shelljs/shelljs#942]
### Example ShellJS command to reproduce the error:

```javascript

var shell = require('shelljs');
shell.exec('bash');
//shell.cd('/home/ssangle/');
//shell.cd('..');
shell.exec('. nova.sh');
shell.exec('nova list');

```

**Comment by nfischer** [comment]
Can you include the error output too?

Could you also show the output of:

```js
console.log('ls output: ' + shell.ls('/home/ssangle/'));
console.log('is dir: ' + shell.test('-d', '/home/ssangle/'));
```

**Comment by shubhamrsangle** [comment]
> Can you include the error output too?
> Could you also show the output of:
> console.log('ls output: ' + shell.ls('/home/ssangle/'));
> console.log('is dir: ' + shell.test('-d', '/home/ssangle/'));

I have updated an actual issue

**Comment by nfischer** [comment]
Yes, the path must be visible to your user. Sounds like there's nothing for us to do here?
