### ISSUE TITLE
Is the wait command supported?

### ISSUE THREAD

**Issue by Teebo** [shelljs/shelljs#953]
### Node version (or tell us if you're using electron or some other framework):
v.10.15.3
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.3
### Operating system:
Windows 10
### Description of the bug:
Is it possible to wait for a process to finish and then start another one using the `wait` command in a windows system in a NodeJS script?
### Example ShellJS command to reproduce the error:
There are no errors, but the echoes are not printed and the script `some_npm_script` is not executed, is it possible? like I did below? This works in a Linux machine BTW. The `truncate` command works fine in the Windows environment
```javascript
    shell.exec(`
    echo "Installing"
    yarn add some_npm_package &
    pid=$!
    wait $pid
    echo "Done installing"
    yarn some_npm_script
    `);
```
If this command is not supported, any explanation or resources to read why it is not working is appreciated, any links to read up on so that I understand or the package works, as I am new to shell scripting.

**Comment by nfischer** [comment]
Not directly supported. You could probably figure something out with the async version of `shell.exec()`/`child_process.exec()`.

**Comment by Teebo** [comment]
Thanks, I have figured out something.
