### ISSUE TITLE
不能拷贝 “.” 开头的文件

### ISSUE THREAD

**Issue by dahuzix** [shelljs/shelljs#954]
### Operating system:
macOs mojave 10.14.5
### Description of the bug:
问题：cp命令不能拷贝"."开头文件
场景：想实现拷贝前端工程下一些配置文件到另一个工程，以实现升级效果
.babelrc
.editerconfig
.eslintrc

### Example ShellJS command to reproduce the error:

```javascript
cp('-rf','registry/WebCodes/sample-web/*','./app')
```

**Comment by nfischer** [comment]
Hello! I'm not familiar with this language, and can generally only respond to Github issues in English. I apologize for the inconvenience. Google translate suggests this report is about copying files which begin with `.` character. Assuming I've understood you correctly, here's an explanation:

---

Files starting with a dot are "hidden" files on unix. Glob (wildcard, `*`) semantics require that we do not match hidden files. If you want to match hidden files, you will need to explicitly say so in the pattern by using a leading dot.

```sh
$ ls *.txt # "*" only matches unhidden files by default
bar.txt  foo.txt
$ ls .*.txt # ".*" will match hidden files only
.secret.txt
$ ls *.txt .*.txt # if you want to match everything, you need both patterns
bar.txt  foo.txt  .secret.txt
```

In ShellJS, you should try:

```js
// Use both patterns:
shell.cp('-rf', 'registry/WebCodes/sample-web/*', 'registry/WebCodes/sample-web/.*', './app');

// Or even better, copy the entire folder recursively (this assumes app/ does not yet exist):
shell.cp('-rf', 'registry/WebCodes/sample-web/', 'app/');
```

**Comment by nfischer** [comment]
This glob behavior is intentional. Assuming this answers your question, I'll consider this working-as-intended. I'm happy to reopen if I've not adequately answered your question (or have misunderstood the question).

**Comment by zhuhengtan** [comment]
> This glob behavior is intentional. Assuming this answers your question, I'll consider this working-as-intended. I'm happy to reopen if I've not adequately answered your question (or have misunderstood the question).

You did not misunderstand his meanings, because I've got the save problem. I did as you replyed above, but it still doesn't copy the files which begin with `.` character.
Operating system: Windows10
