### ISSUE TITLE
Shelljs Object not found 

### ISSUE THREAD

**Issue by mxamusic** [shelljs/shelljs#955]
### Node version (or tell us if you're using electron or some other framework):
```shell
┌─[microbot@parrot]─[~]
└──╼ $node -v
v12.4.0
```
### ShellJS version (the most recent version/Github branch you see the bug on):
+ shelljs@0.8.3

### Operating system:
Parrot Sec (Debian Based)
### Description of the bug:
```/bin/sh: 1: [object: not found```
### Example ShellJS command to reproduce the error:
shell.exec(cmd.toString());
```javascript
var restify = require('restify');
var shell = require('shelljs');

const server = restify.createServer({
  name: 'Spector',
  version: '1.0.0'
});
 
server.use(restify.plugins.acceptParser(server.acceptable));
server.use(restify.plugins.queryParser());
server.use(restify.plugins.bodyParser());
 
server.get('/echo/:name', function (req, res, next) {
  res.send(req.params);
  return next();
});
server.get('/exec/:cmd',function(req,res,next)
{
  cmd = req.params;
  res.send(shell.exec(cmd.toString()));
  

})
server.listen(8080, function () {
  console.log('%s listening at %s', server.name, server.url);
});
```
So The idea is to send cmd from REST API.  it will be executed and send the website back the result

**Comment by nfischer** [comment]
What would a possible value be for `req.params`? Given "params" is plural, I'm guessing some sort of list? If so, you would need to join this into a proper string with `req.params.join(' ')`.

---

I **strongly recommend** you do **not** build this functionality into your application. You're letting clients execute arbitrary commands on your server, which could include exfiltrating any sort of data (ex. `cat /etc/passwd`) or cause other havoc on your system (ex. `rm -rf ~`). Even if you only expose this to trusted clients, be extremely careful those clients don't pass shell characters (ex. `;`) or you could have unintended command injection.

**Comment by mxamusic** [comment]
So the idea the tool is built to visualize the hacking tool output and keep it stored in 1 DB :D so I want to execute commands from shelljs on my Kali box now I have another question if I want Async cmd execution and pulling results as it pops for example "Web directory discovery" when the scan start 2 min later it found this URL 3 min later it found another URL. how do I keep fetching whatever is in the child output

**Comment by mxamusic** [comment]
Now regarding ```req.params.join(' ').``` I fixed it using the following 
```javascript
server.get('/exec/:cmd',function(req,res,next)
{
  cmd = req.params
  console.log(cmd['cmd'])
  res.send(shell.exec(cmd['cmd'].toString()));
  })
```

**Comment by nfischer** [comment]
It's not clear from your comment how you're building this securely, but again, make sure you think twice before building this into your application, because it sounds like you're writing an endpoint to execute arbitrary commands. Even if you only permit commands you _think_ are safe, you could be vulnerable to command injection (where you run multiple commands in a single `shell.exec()` call, due to shell syntax) because you're not sanitizing input.

If you want to get the child process output bit by bit, you need to listen for the `data` event on the ChildProcess object returned by the method:

```js
var c = shell.exec(cmd, { async: true });
c.stdout.on('data', function (data) {
  // something
});
```

See https://nodejs.org/api/child_process.html#child_process_subprocess_stdout

**Comment by nfischer** [comment]
Sounds like this is a question, and doesn't require changes on our side. Closing this for now, but I'm happy to continue answering questions on this thread.
