### ISSUE TITLE
Launch a release to include #961

### ISSUE THREAD

**Issue by vilaboim** [shelljs/shelljs#968]
Hi @nfischer.
Great work with shelljs, :clap: 

Do you have any predictions about when launching a new version to include this [feature](https://github.com/shelljs/shelljs/pull/961)?

**Comment by nfischer** [comment]
I've slated this for v0.9.0. I don't have an estimate yet when this will be published, as there's other work we're hoping to get into the same release (to clump together breaking changes).

**Comment by nfischer** [comment]
Closing this since it's just a question, but I'm happy to continue the conversation if you have concerns.
