### ISSUE TITLE
Unable to find a path to the node binary. Please manually set config.execPath

### ISSUE THREAD

**Issue by devYoungyang** [shelljs/shelljs#972]
### Example ShellJS command to reproduce the error:  Unable to find a path to the node binary. Please manually set config.execPath

```javascript
shelljs.exec('ls') 
```

**Comment by nfischer** [comment]
This shouldn't happen in default node. Are you using electron or another framework? If so, please see https://github.com/shelljs/shelljs/wiki/Electron-compatibility
