### ISSUE TITLE
shell.exec('export NODE_OPTIONS=--max-old-space-size=4096') doesn't work

### ISSUE THREAD

**Issue by ihaichao** [shelljs/shelljs#980]
### Node version (or tell us if you're using electron or some other framework):
v10.15.0

### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.3

### Operating system:
macOS Mojave 10.14.6

### Description of the bug:
`shell.exec('export NODE_OPTIONS=--max-old-space-size=4096')` should set the max memory for Node to 4096, but it doesn't work

### Example ShellJS command to reproduce the error:

```javascript
import shell from 'shelljs';
import v8 from 'v8'

if (shell.exec('export NODE_OPTIONS=--max-old-space-size=4096').code !== 0) {
  shell.exit(1);
}

const validSize = v8.getHeapStatistics().total_available_size / 1024 / 1024

console.log(validSize)
```

**Comment by nfischer** [comment]
Try `shell.env.NODE_OPTIONS = '--max-old-space-size=4096'` instead. However, I'm not sure node supports setting this variable after startup (but that's out of the scope of ShellJS).
