### ISSUE TITLE
Removing 1st line from a file(s) using sed 

### ISSUE THREAD

**Issue by visaq** [shelljs/shelljs#983]
Hello - Can you please give me the exact sed command to remove 1st line from a set of files. Basically I have a bunch of csv files and they do contain header as their 1st line. I first want to delete their headers and then merge all of those files into a single file. Thanks for your help in advance!

MC

**Comment by nfischer** [comment]
I don't think we support this with `shell.sed()`. You could try something with [`shell.tail()`](https://github.com/shelljs/shelljs#tail-n-num-file--file-), but you'll have to count the number of lines yourself and do math to figure out how many lines to print (until issue #984 is fixed).

**Comment by visaq** [comment]
Thanks for your response. I was trying sed with different patterns of '1d' hoping that it would delete the first line. Your response helps me understand why it did not.

**Comment by nfischer** [comment]
I'm going to close this as wontfix. Users wanting this should use `tail` with the `+` feature. See #984.

**Comment by markusbkk** [comment]
I suppose the same is true for adding a line before the first line in every file? 
I'm trying to efficiently and portably add `// @ts-nocheck` to the top of every `.ts` file.

My non-functioning code:

```mjs
import shell from "shelljs";

let array = (shell.find("scripts/**/*.ts"));
array.forEach(element => shell.sed("-i", "1 s", "// @ts-nocheck", element));
```

Will I need to somehow chain this with head and `ShellString(string).to(file)` instead?

**Comment by nfischer** [comment]
Yeah, I would do something like what you suggested:

```javascript
var header = '// @ts-nocheck\n';
var fileContents = shell.cat(file);
new shell.ShellString(header + fileContents).to(file);
```
