### ISSUE TITLE
Any way to change Mac OS  password

### ISSUE THREAD

**Issue by ShivamJoker** [shelljs/shelljs#988]
Hey I am looking for some codes which can change the mac user's password without any prompt. Can anyone help me with that ?
Mac doesn't come with `chpasswd`
and also doing this doesn't work
```
$ echo -e "12345\n1234" | passwd
Changing password for shivam.
passwd: conversation failure
```

**Comment by nfischer** [comment]
Sorry, I'm not the best person to answer Mac-specific questions like this. This is out of the scope of ShellJS.
