### ISSUE TITLE
shellJS swallows Heroku CLI output and fails with undefined error

### ISSUE THREAD

**Issue by austinrivas** [shelljs/shelljs#990]
### Example ShellJS command to reproduce the error:

Install the Heroku CLI

I am evaluating the use of ShellJS in helping me move my deployment/CI pipeline to TS instead of a bunch of bash scripts.

Everything is currently working fine in bash land, but when I try running heroku commands in ShellJS it just errors out with no output of any kind.

For example

```javascript
      shell.set(`-v`)
      const result = shell.exec(`heroku --help`);
      console.log(result);

      const child = shell.exec(`heroku login`, {async: true});
      child.stdout.on('data', function(data) {
        console.log(data);
      });
```

Results in:

```
  console.log tests/create_app.test.ts:25
    [String: ''] {
      stdout: '',
      stderr: '',
      code: 0,
      cat: [Function: bound ],
      exec: [Function: bound ],
      grep: [Function: bound ],
      head: [Function: bound ],
      sed: [Function: bound ],
      sort: [Function: bound ],
      tail: [Function: bound ],
      to: [Function: bound ],
      toEnd: [Function: bound ],
      uniq: [Function: bound ]
    }
```

Some of the processes hang long enough that it makes me think something is happening, but without any way to debug it is hard to tell.

My current handler for exec looks like this,

```typescript
  static async execAsync(cmd, opts={}): Promise<string> {
    return new Promise(function(resolve, reject) {
      // Execute the command, reject if we exit non-zero (i.e. error)
      const child = shell.exec(cmd, {shell: '/bin/bash', ...opts}, function(code, stdout) {

        if (code != 0) return reject(new Error(stdout));
        return resolve(stdout);
      });
      child.stdout.on('data', function(data) {
        console.log(data);
      });
    });
  }
```

If this is problem with the Heroku CLI I understand, but I find that hard to believe considering that all of these commands work perfectly fine elsewhere.

Linking to the Heroku CLI ticket for reference: https://github.com/heroku/cli/issues/1478

**Comment by nfischer** [comment]
Can you log `child.stderr` as well?

**Comment by austinrivas** [comment]
```
      shell.set(`-v`)
      const child = shell.exec(`heroku login`, {async: true});
      // @ts-ignore
      child.stdout.on('data', function(data) {
        console.log(data);
      });
```

yields

```
    console.error node_modules/shelljs/src/common.js:327
    exec heroku login { async: true }
```

**Comment by nfischer** [comment]
> console.error node_modules/shelljs/src/common.js:327

It's unclear where this output is coming from. Might help to change your log line to something like:

```
      child.stdout.on('data', function(data) {
        console.log('from child stdout: ' + data);
      });
      child.stderr.on('data', function(data) {
        console.log('from child stderr: ' + data);
      });
```

You could also add `{ silent: true, async: true }` to the exec call, or else you'll get double-logging.

**Comment by austinrivas** [comment]
thanks @nfischer, I'll let you know what I find when I come back to this in a few days

**Comment by austinrivas** [comment]
@nfischer I'm closing this as the issue seems to be related to the shell executing the heroku commands and not your library, thanks for the help.
