### ISSUE TITLE
sed doesn't replace combination of name+parens+semicolon

### ISSUE THREAD

**Issue by uloco** [shelljs/shelljs#995]
### Node version (or tell us if you're using electron or some other framework):
v13.12.0
### ShellJS version (the most recent version/Github branch you see the bug on):
v0.8.4
### Operating system:
macOS 10.15.4 (19E287)
### Description of the bug:
When running `sed("-i", "someString();", "anything", "anyfile")`, sed will not replace.

Is this intended behavior? Do I have to escape something? In JS replace this should work ...

**Comment by nfischer** [comment]
I think `()` is treated as an empty capture group, so your regex is equivalent to `someString;`. Try `"someString\\(\\);"` instead.

**Comment by uloco** [comment]
But this is no regex, it’s just a string. Why do I need to escape in a string?
`/someString\(\);/` works of course

**Comment by nfischer** [comment]
Sed treats its first argument as a regex (that's why the [first arg is named "search\_regex."](https://github.com/shelljs/shelljs#sedoptions-search_regex-replacement-file--file-)). This is consistent with how unix `sed` behaves.

**Comment by uloco** [comment]
It’s not on mac… When I run sed directly on the shell it works without escapes.

**Comment by nfischer** [comment]
Right, unix `sed` defaults to unextended regex but `shell.sed()` defaults to something like extended regex (really, it's whatever syntax the [JavaScript RegExp constructor accepts](https://github.com/shelljs/shelljs/blob/a8452b89f2b9dd372da81e973a16074a5628b0b6/src/sed.js#L54-L57)). I filed #996 to track possibly changing the behavior in the future.

**Comment by uloco** [comment]
Thanks. Great work btw :)))
